stages:
  - build
  - lint
  - test

default:
  before_script:
    - make autoloads

.build:
  stage: build
  needs: []
  script:
    - make clean
    - emacs -Q -batch -L . -L test -l bytecomp
        --eval '(setq byte-compile-error-on-warn t)'
        -f batch-byte-compile *.el test/*.el

.lint:
  stage: lint
  needs: []
  variables:
    log_file: ${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}.log
  script:
    - ${HOME}/.local/bin/eldev lint all elisp 2>&1 | tee ${log_file}
  artifacts:
    name: ${log_file}
    public: true
    expire_in: 1 week
    when: always
    paths:
      - ${log_file}

.test:
  stage: test
  needs: []
  script:
    - make clean
    - emacs -Q -batch -L . -l bytecomp
        -f batch-byte-compile *.el
    - make test TESTS=tramp-tests

build-28:
  image: "silex/emacs:28-ci-eldev"
  extends: .build

build-29:
  image: "silex/emacs:29-ci-eldev"
  extends: .build

build-30:
  image: "silex/emacs:30-ci-eldev"
  extends: .build

build-master:
  image: "silex/emacs:master-ci-eldev"
  extends: .build

lint-28:
  image: "silex/emacs:28-ci-eldev"
  extends: .lint

lint-29:
  image: "silex/emacs:29-ci-eldev"
  extends: .lint

lint-30:
  image: "silex/emacs:30-ci-eldev"
  extends: .lint

lint-master:
  image: "silex/emacs:master-ci-eldev"
  extends: .lint

test-28:
  image: "silex/emacs:28-ci-eldev"
  extends: .test

test-29:
  image: "silex/emacs:29-ci-eldev"
  extends: .test

test-30:
  image: "silex/emacs:30-ci-eldev"
  extends: .test

test-master:
  image: "silex/emacs:master-ci-eldev"
  extends: .test

# Local Variables:
# add-log-current-defun-header-regexp: "^\\([-_.[:alnum:]]+\\)[ \t]*:"
# End:
