stages:
  - build
  - lint
  - test

default:
  before_script:
    - make autoloads

.build:
  stage: build
  needs: []
  script:
    - emacs -Q -batch -L . -l bytecomp
        --eval '(setq byte-compile-error-on-warn t)'
        -f batch-byte-compile *.el

.lint:
  stage: lint
  needs: []
  before_script:
    - curl -fsSL
        https://raw.github.com/emacs-eldev/eldev/master/bin/eldev > eldev
    - chmod a+x eldev
  script:
    - ./eldev lint all elisp

.test:
  stage: test
  needs: []
  script:
    - emacs -Q -batch -L . -l bytecomp
        -f batch-byte-compile *.el
    - make test TESTS=tramp-tests


build-28:
  image: "silex/emacs:28-ci"
  extends: .build

build-29:
  image: "silex/emacs:29-ci"
  extends: .build

build-30:
  image: "silex/emacs:30-ci"
  extends: .build

build-master:
  image: "silex/emacs:master-ci"
  extends: .build

lint-28:
  image: "silex/emacs:28-ci"
  extends: .lint

lint-29:
  image: "silex/emacs:29-ci"
  extends: .lint

lint-30:
  image: "silex/emacs:30-ci"
  extends: .lint

lint-master:
  image: "silex/emacs:master-ci"
  extends: .lint

test-28:
  image: "silex/emacs:28-ci"
  extends: .test

test-29:
  image: "silex/emacs:29-ci"
  extends: .test

test-30:
  image: "silex/emacs:30-ci"
  extends: .test

test-master:
  image: "silex/emacs:master-ci"
  extends: .test

# Local Variables:
# add-log-current-defun-header-regexp: "^\\([-_.[:alnum:]]+\\)[ \t]*:"
# End:
