;; -*- mode: eask; lexical-binding: t -*-

(package "php-fill"
         "1.1.1"
         "Additional fill commands for PHP code editing")

(website-url "https://github.com/arielenter/php-fill.el")
(keywords "php" "languages" "tools" "convenience")

(package-file "php-fill.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'nongnu)

(development
 (depends-on "php-mode"))

(depends-on "emacs" "27.1")
