#+title: ffs: form feed-separated plain text presentations
#+author: Amin Bandali
#+email: bandali@gnu.org
#+language: en
#+options: ':t toc:nil author:t email:t num:t
#+startup: content
#+macro: stable-version 0.1.0
#+macro: release-date 2022-05-19
#+macro: development-version 0.2.0-dev
#+macro: kbd (eval (org-texinfo-kbd-macro $1))
#+texinfo_filename: ffs.info
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_title: FFS: (ffs)
#+texinfo_dir_desc: Simple form feed-separated plain text presentations
#+texinfo_header: @set MAINTAINERSITE @uref{https://kelar.org/~bandali/,maintainer webpage}
#+texinfo_header: @set MAINTAINER Amin Bandali
#+texinfo_header: @set MAINTAINEREMAIL @email{bandali@@gnu.org}
#+texinfo_header: @set MAINTAINERCONTACT @uref{mailto:bandali@@gnu.org,contact the maintainer}
#+html_head: <link rel="stylesheet" href="../../dek.css?v=20260123" type="text/css" />
#+html_link_home: ../..

#+texinfo: @insertcopying

This manual, written by Amin Bandali, introduces =ffs= and its user
options, and provides every other piece of information pertinent to
it.

This manual corresponds to =ffs= stable version {{{stable-version}}},
released on {{{release-date}}}.  Any reference to a newer feature
which does not yet form part of the latest tagged commit is marked as
such.

Current development target is {{{development-version}}}.

- Package name (GNU ELPA): =ffs= (not available yet)
- Official manual: <https://kelar.org/~bandali/gnu/emacs/ffs.html>
- Change log: <https://kelar.org/~bandali/gnu/emacs/ffs-changelog.html>
- Git repository: <https://git.kelar.org/~bandali/ffs>
- Backronyms: fabulous foolproof slides - for freedom's sake -
  ffs flips slides

Dedicated to the loving memory of [[https://kelar.org/~bandali/life/farangis.html][Farangis Yousefinia]].

#+toc: headlines 8 insert TOC here, with eight headline levels

* COPYING
:PROPERTIES:
:COPYING: t
:CUSTOM_ID: copying
:END:

Copyright (c) 2022-2026 Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below.  A copy of the license is
included in the section entitled “GNU Free Documentation License.”

(a) The FSF’s Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

* Overview
:PROPERTIES:
:CUSTOM_ID: overview
:END:

This package provides a simple presentation mode which can be applied
to any buffer for reading, writing, editing, and presenting slides.
Slides are separated using the ~page-delimiter~, by default the =^L=
character, known as the form feed, which can be inserted using
{{{kbd(C-q C-l)}}}.  Commands are provided for moving between those
pages, aka slides.  These motions work even when narrowing is in
effect (and they preserve it).  Through detailed explanations and
concrete examples, this manual hopes to demonstrate that ~ffs~ is
designed to be simple and flexible, and easy to use and extend.

ffs does not define any global key bindings.  You can define a key
binding for ~ffs-mode~ in the ~global-map~ like so:

#+begin_src elisp
(global-set-key (kbd "C-c f s") #'ffs-mode)
#+end_src

On Emacs 29 or later, you can use the newer keymap functions, for
instance:

#+begin_src elisp
(keymap-global-set "C-c f s" #'ffs-mode)
#+end_src

For convenience, ~ffs~ is provided as an alias for ~ffs-mode~.

Once enabled, ~ffs-mode~ puts the buffer in read-only mode by setting
~buffer-read-only~, and provides convenient key bindings for moving
between, editing, and inserting slides.  These are available in the
~ffs-mode-map~ keymap.

#+findex: ffs-present-mode
#+vindex: ffs-default-face-height
#+vindex: ffs-hide-cursor
#+vindex: ffs-hide-mode-line
#+vindex: ffs-hide-header-line
When ready to present your slides, you can enable ~ffs-present-mode~,
by default bound to the {{{kbd(s)}}} key in ~ffs-mode-map~ to start a
presentation.  Several user options are provided for customizing the
appearance of the buffer during presentations, for using a different
=height= for the ~default~ face (~ffs-default-face-height~), hiding
the cursor (~ffs-hide-cursor~), hiding the mode line
(~ffs-hide-mode-line~), and hiding the header line
(~ffs-hide-header-line~).

* Installation
:PROPERTIES:
:CUSTOM_ID: installation
:END:

** GNU ELPA package
:PROPERTIES:
:CUSTOM_ID: installation-gnu-elpa
:END:

The package is available as =ffs=.  Simply do:

: M-x package-refresh-contents
: M-x package-install

And search for it.

GNU ELPA provides the latest stable release.  Folks who prefer to
follow the development process in order to report bugs or suggest
changes can use the version of the package from the GNU-devel ELPA.

** Manual installation
:PROPERTIES:
:CUSTOM_ID: installation-manual
:END:

Assuming your Emacs files are found in =~/.emacs.d/=, execute the
following commands in a shell:

#+begin_src sh
# Make a directory for local lisp files and packages
mkdir ~/.emacs.d/lisp

# Go to the new directory
cd ~/.emacs.d/lisp/

# Clone the ffs source repository
git clone https://git.kelar.org/~bandali/ffs
#+end_src

Then, in your ~user-init-file~ (=init.el= or equivalent) add:

#+begin_src emacs-lisp
;; Make Elisp files in the directory available
(add-to-list 'load-path "~/.emacs.d/lisp/ffs")
#+end_src

Then restart your Emacs session or simply evaluate that expression
(using {{{kbd(C-x C-e)}}}) so Emacs can find the package.

On Emacs 31 or later, you can use the new User Lisp feature, where
Emacs Lisp files in the directory specified by ~user-lisp-directory~
and its subdirectories will be recursively byte-compiled, scraped for
autoload cookies, and ensured to be in ~load-path~.  So all you need
is to designate =~/.emacs.d/lisp/= as your ~user-lisp-directory~ in
your ~early-init-file~ (=early-init.el=) like so:

#+begin_src elisp
(setq user-lisp-directory (locate-user-emacs-file "lisp/"))
#+end_src

* Indices
:PROPERTIES:
:CUSTOM_ID: indices
:END:

** Function index
:PROPERTIES:
:INDEX: fn
:CUSTOM_ID: indices-fn
:END:

** Variable index
:PROPERTIES:
:INDEX: vr
:CUSTOM_ID: indices-vr
:END:

** Concept index
:PROPERTIES:
:INDEX: cp
:CUSTOM_ID: indices-cp
:END:

* COMMENT Local Variables

# Local Variables:
# org-html-postamble-format: (("en" "<hr />
# <p><a href=\"%i\">Org source</a></p>"))
# End:
