#+title: ffs: simple form feed-separated plain text presentations
#+author: Amin Bandali
#+email: bandali@gnu.org
#+language: en
#+options: ':t toc:nil author:t email:t num:t
#+startup: content
#+macro: stable-version 0.1.0
#+macro: release-date 2022-05-19
#+macro: development-version 0.2.0-dev
#+texinfo_filename: ffs.info
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_title: FFS: (ffs)
#+texinfo_dir_desc: Simple form feed-separated plain text presentations
#+texinfo_header: @set MAINTAINERSITE @uref{https://kelar.org/~bandali/,maintainer webpage}
#+texinfo_header: @set MAINTAINER Amin Bandali
#+texinfo_header: @set MAINTAINEREMAIL @email{bandali@@gnu.org}
#+texinfo_header: @set MAINTAINERCONTACT @uref{mailto:bandali@@gnu.org,contact the maintainer}

#+texinfo: @insertcopying

This manual, written by Amin Bandali, introduces =ffs= and its user
options, and provides every other piece of information pertinent to
it.

This manual corresponds to =ffs= stable version {{{stable-version}}},
released on {{{release-date}}}.  Any reference to a newer feature
which does not yet form part of the latest tagged commit is marked as
such.

Current development target is {{{development-version}}}.

- Package name (GNU ELPA): [[https://elpa.gnu.org/packages/ffs.html][=ffs=]]
- Official manual: <https://kelar.org/~bandali/gnu/emacs/ffs.html>
- Change log: <https://kelar.org/~bandali/gnu/emacs/ffs-changelog.html>
- Git repository: <https://git.kelar.org/~bandali/ffs>
- Backronyms:
  - fabulous foolproof slides
  - for freedom's sake
  - ffs flips slides

Dedicated to the loving memory of [[https://kelar.org/~bandali/life/farangis.html][Farangis Yousefinia]].

#+toc: headlines 8 insert TOC here, with eight headline levels

* COPYING
:PROPERTIES:
:COPYING: t
:CUSTOM_ID: copying
:END:

Copyright (c) 2022-2026 Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below.  A copy of the license is
included in the section entitled “GNU Free Documentation License.”

(a) The FSF’s Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

* Overview
:PROPERTIES:
:CUSTOM_ID: overview
:END:

TBD
