#+title: dired-duplicates - Find duplicate files on local and remote filesystems

* Description
This Emacs package helps to find duplicate files on local and remote
filesystems.  It is similar to the fdupes command-line utility but written in
Emacs Lisp and should also work on every remote filesystem that TRAMP supports
and where executable commands can be called remotely.  The most common use case
for this is probably finding and deleting unneeded duplicate files.

dired-duplicates works by first searching files of the same size, then invoking
the calculation of the checksum for these files, and finally presenting the
grouped results in a Dired buffer that the user can work with similarly to a
regular Dired buffer.  It might be even possible to combine this with other
Dired extension packages, like =dired-narrow=.

The results will be grouped visually by using a temporary file serving as a
separator - the author has not yet found any way of making dired add an empty
line or similar to achieve some sort of separation, but this grouping with a
temporary file can also be deactivated.

* Requirements
For performance reasons, a checksum program like =md5= or =sha256sum= will be
used for generating checksums of file contents and therefore needs to be
available and executable on the local and/or remote hosts.  That way, no files
need to be read over possibly slow networks and calculating the checksum will
be much faster when directly executed on remote hosts.  The name of the
checksum program can be customized.

* Installation
The package can be installed via the Emacs package manager,
e.g. ~package-install~.  Or you use the following use-package snippet:
#+BEGIN_SRC emacs-lisp
(use-package dired-duplicates)
#+END_SRC

* Usage
Call ~dired-duplicates~ interactively and provide one or more directories
(usually separated by commas) to search in recursively.

* Configuration
You can find all available customization options with ~customize-group~,
entering =dired-duplicates= for the desired group.  These options are described
extensively there.

* License
This package is licensed under GPL-3.  See the =LICENSE= file for more
information.
