#+html: <a href="https://melpa.org/#/truename-cache"><img alt="MELPA" src="https://melpa.org/packages/truename-cache-badge.svg"/></a> <a href="https://stable.melpa.org/#/truename-cache"><img alt="MELPA Stable" src="https://stable.melpa.org/packages/truename-cache-badge.svg"/></a>
* truename-cache

#+begin_quote
[!WARNING]
This is a BETA release!
Breaking changes are possible.
#+end_quote

This Emacs library provides two things:

1. =truename-cache-get=: A caching alternative to =file-truename=.

2. =truename-cache-collect-files-and-attributes=: Basically an alternative to =directory-files-recursively= that pre-populates cache and returns truenames while minimizing calls to =file-truename=.

** Why?

Truenames are useful as a way to de-duplicate file lists and to cross-reference names in one list with names in another list.

But if you write code that just wraps every file name it encounters in =(file-truename FILE)=, it gets slow if you have large lists of file names. It takes 1,000 milliseconds to process 1,000 file names on my machine.

That is unacceptably slow, at least in the use-case where you often scan a list of directories to see if any new files have appeared or any files were modified or deleted.

That's the sort of thing that might be done as part of a user command.  If the command is to be pleasant to use, it must take less than 100 milliseconds so it feels "instant".  And you may be dealing with not 1,000 but 10,000 or even 100,000 files.

Sidenote for Elisp devs: It might occur to you that you can also de-dup by filesystem inodes.  See [[README.org#appendix-on-referring-to-inodes-instead-of-truenames][Appendix: On referring to inodes instead of truenames]].

** Bonus: Merging lists

The routine =truename-cache-collect-files-and-attributes= can be used to merge multiple file lists and return de-duplicated truenames.

Some example file-lists in Emacs that may overlap a lot:

- Variable =recentf-list=
- Variable =org-agenda-text-search-extra-files=
- Variable =org-id-files=
- Variable =org-id-extra-files=
- Output of =(org-files-list)=
- Output of =(hash-table-values org-id-locations)=

Even if you =append= and =seq-uniq= these lists, a given file may still be represented multiple times under different names.

To merge, pass all your file-lists in the argument =:infer-dirs-from=.  In truth, it doesn't operate directly on any of the files given, it just infers their parent directories and then scans each directory once.  That turns out to be efficient, even if it's likely to pull in more unique files than were mentioned by any name in the input.

** Bonus: Filtering

While you could simply let =truename-cache-collect-files-and-attributes= return a giant file list and filter it afterwards, there are two reasons to do some filtering through the arguments =:relative-file-deny=, =:relative-dir-deny= and/or =:full-dir-deny= (which take lists of regular expressions).

1. They filter early, so you can avoid recursing into directories that you were never gonna keep anyway -- e.g. the contents of =.git/= or =node_modules/=...

   It can easily be the difference between a runtime of 2.00 seconds and 0.02 seconds!

2. If you wanted to apply your filters to relative file names rather than absolute names ([[https://github.com/org-roam/org-roam/pull/2178][example use-case]]), you'd ordinarily have to use =(file-relative-name FILE DIR)= on every file, and that isn't completely free either, keeping in mind our aforementioned 100 millisecond budget.

   That's why it provides =:relative-file-deny=, =:relative-dir-deny=.  Another bottleneck dodged.

** Bonus: Abbreviation

Sometimes you do not want a true name but a name abbreviated with =abbreviate-file-name=.  Even that can blow our aforementioned 100 millisecond budget, all by itself.

So =truename-cache-collect-files-and-attributes= can pre-abbreviate names for you with the argument =:abbrev 'full=.  This does it slightly more efficiently (informal benchmark: 50-75% of normal runtime), and much more efficiently if you also pass the argument =:local-name-handlers nil= (informal benchmark: 20% of normal runtime).

** Appendix: On referring to inodes instead of truenames
:PROPERTIES:
:CUSTOM_ID: inodes
:END:

I have a theory that if de-dup is all you want, it could be possible with some loop that makes use of the function =file-attribute-file-identifier=.

I've not tried that, but there are other upsides to true names.

- It's a more human-friendly UI: when something needs debugging, better to see a file name than some meaningless inode number.

- Once you have a list of true names, it is very friendly to further manipulation.  You can use trivial string comparisons like =string-prefix-p= in place of =file-in-directory-p=.
