* truename-cache

This Emacs library provides two things:

1. =truename-cache-get=: A caching alternative to =file-truename=.

2. =truename-cache-collect-files-and-attributes=: Basically an alternative to =directory-files-recursively= that pre-populates cache and returns truenames while minimizing calls to =file-truename=.

** Why?

Truenames are useful as a way to de-duplicate file lists and to cross-reference names in one list with names in another list.

But if you write code that just wraps every file name it encounters in =(file-truename FILE)=, it gets slow if you have large lists of file names. It takes 1,000 milliseconds to process 1,000 file names on my machine.

That is unacceptably slow, at least in the use-case where you often scan a list of directories to see if any new files have appeared or any files were modified or deleted.

That's the sort of thing that might be done as part of a user command.  As we all know, the rule of thumb for an once-off command to feel "instant" is 100ms maximum.  (Some say 20ms, but that's for code triggered on every keystroke while typing -- i.e. in Emacs parlance, hooks run by =self-insert-command=).

Another way to de-dup is to refer to filesystem inodes i.e. =(file-attribute-file-identifier (file-attributes FILE))=, but that is not as human-friendly to work with as truenames.

** Bonus: Merging lists

The routine =truename-cache-collect-files-and-attributes= can merge multiple file lists and still return de-duplicated truenames, and tries to do this as efficiently as possible.

Some example file-lists in Emacs that may have a great deal of overlap between them:

- Variable =recentf-list=
- Variable =org-agenda-text-search-extra-files=
- Variable =org-id-files=
- Variable =org-id-extra-files=
- Output of =(org-files-list)=
- Output of =(hash-table-values org-id-locations)=

This is done through the argument =:infer-dirs-from=.  In truth, it doesn't operate directly on any file names, it just infers their parent directories and then scans each directory once.  That turns out to be efficient, even if it's likely to pull in more file names than were in the input.

** Bonus: Filtering

While you could simply let =truename-cache-collect-files-and-attributes= return a giant file list and filter it afterwards, there are two reasons to do some filtering through the arguments =:rel-file-deny=, =:rel-dir-deny= and/or =:full-dir-deny=.

1. It filters early, so it can avoid recursing into directories that you were never gonna keep anyway -- e.g. the contents of =.git/= or =node_modules/=...

   It can easily be the difference between a runtime of 2.00 seconds and 0.02 seconds!

2. If you wanted to apply your filters to relative file names rather than absolute names, you'd ordinarily have to use =(relative-file-name FILE DIR)= on every file, and that procedure isn't cheap either.

   That's why it provides =:rel-file-deny=, =:rel-dir-deny=.  Another bottleneck dodged.
