#+title: doc-follow.el: Synchronized dual window document viewing
#+author: Paul Nelson

* Overview

=doc-follow= is an Emacs package that synchronizes multiple windows showing the same document in =doc-view-mode= or =pdf-view-mode= (with the list of available modes customizable via =doc-follow-modes=).  When you navigate to a page in one window, the other windows automatically display neighboring pages.  A common setup is to have two pages side by side, in which case this mode gives a book-like view.

* Installation

Install =doc-follow= by, e.g., downloading the source and using =M-x package-install-file=.

* Usage

After installing the package, you can toggle it globally via =M-x global-dual-doc-view-mode=, locally via =M-x doc-follow-mode=.  To have it activate by default, add =(global-dual-doc-view-mode)= to your config.

1. Open a document in =doc-view-mode= or =pdf-view-mode= (the latter being part of the [[https://github.com/vedang/pdf-tools][pdf-tools]] package)
2. Split the window (e.g., =C-x 3= for vertical split)
3. Activate =doc-follow-mode= in either window (if not already activated)
4. Navigate through the document in either window (e.g. =n= or =p= to navigate by page)

The package will automatically keep the two views in sync, with the second always one page ahead of the first.  It works similarly with more than two windows.
