;;; gnosis-test-study.el --- Study workflow regressions -*- lexical-binding: t; -*-

(require 'ert)
(require 'gnosis-review)
(require 'gnosis-study)
(require 'gnosis-export-import)
(require 'gnosis-test-helpers)
(require 'gnosis-test-schema-v9)

(defmacro gnosis-test-study (&rest body)
  "Run BODY with real writers and disposable buffers and database."
  (declare (indent 0) (debug t))
  `(gnosis-test-with-db
     (let ((buffers (buffer-list))
           (gnosis-review-buffer-name "*Gnosis Test Recall*")
           (gnosis-monkeytype-enable nil)
           (gnosis-center-content nil)
           (register-alist nil))
       (save-window-excursion
         (unwind-protect (progn ,@body)
           (dolist (buf (seq-difference (buffer-list) buffers))
             (when (buffer-live-p buf)
               (with-current-buffer buf (set-buffer-modified-p nil))
               (kill-buffer buf))))))))

(defun gnosis-test-study-snapshot ()
  "Snapshot every scheduling authority and activity row."
  (mapcar (lambda (table) (gnosis-sqlite-select gnosis-db
                           (format "SELECT * FROM %s ORDER BY 1" table)))
          '(scheduler_config scheduler_active scheduler_baseline scheduler_state
            review_events review_voids review_activity_baseline)))

(defun gnosis-test-study-node (id &optional title)
  "Insert node ID with TITLE into the disposable index."
  (gnosis--insert-into 'nodes `([,id "fixture.org" ,(or title "Same title") "1" nil nil nil])))

(defun gnosis-test-study-state (ids mode)
  "Create a persisted session for IDS in MODE, returning its buffer."
  (let ((buf (gnosis-review--setup-buffer ids mode)))
    (with-current-buffer buf
      (setf (gnosis-review-state-persistent-p gnosis-review--state) t)
      (gnosis-review--save-session gnosis-review--state))
    buf))

(ert-deftest gnosis-study-selection-identity-cycle-and-composition ()
  (gnosis-test-study
    (gnosis-test-study-node "one")
    (gnosis-test-study-node "two")
    (gnosis--insert-into 'node-links '(["one" "two"] ["two" "one"]))
    (let* ((a (gnosis-test--add-basic-thema "due" "a"))
           (b (gnosis-test--add-basic-thema "future" "b"))
           (c (gnosis-test--add-basic-thema "suspended" "c" nil nil nil 1))
           (gnosis-new-themata-limit 0))
      (gnosis-update 'scheduler-state `(= due-day ,(gnosis--date-to-int (gnosis-date 3))) `(= thema-id ,b))
      (gnosis--insert-into 'thema-links `([,a "one"] [,a "two"] [,b "two"] [,c "one"]))
      (should (= 2 (length (gnosis-study-topic-candidates))))
      (should (equal '("one" "two") (mapcar #'cdr (gnosis-study-topic-candidates))))
      (should (equal (list a) (gnosis-study-topic-ids '("one"))))
      (should (equal (sort (list a b) #'<) (sort (gnosis-study-topic-ids '("one") nil 8 8) #'<)))
      (should (equal (list a) (gnosis-study-topic-ids '("one" "two") t)))
      (should (equal '(:total 2 :eligible 2 :suspended 0 :new 2 :due 1 :not-due 1)
                     (gnosis-study-composition (list a b a))))
      (cl-letf (((symbol-function 'completing-read-multiple)
                 (lambda (_ candidates &rest _) (mapcar #'car candidates))))
        (should (equal '("one" "two") (gnosis-study-read-topics))))
      (should-error (gnosis-study-topic-ids '("one") nil -1)))))

(ert-deftest gnosis-study-topic-labels-hide-ids-and-preserve-identity ()
  (gnosis-test-study
    (gnosis-test-study-node "unique-id" "Καρδιολογία")
    (gnosis-test-study-node "first-id" "Same title")
    (gnosis-test-study-node "second-id" "Same title")
    (gnosis-test-study-node "literal-id" "Same title — fixture.org")
    (let* ((candidates (gnosis-study-topic-candidates))
           (labels (mapcar #'car candidates)))
      (should (equal "unique-id" (cdr (assoc "Καρδιολογία" candidates))))
      (should (equal "literal-id" (cdr (assoc "Same title — fixture.org" candidates))))
      (should (= 4 (length (delete-dups (copy-sequence labels)))))
      (dolist (label labels)
        (should-not (string-match-p "id:" label)))
      (should (equal (car (rassoc "first-id" candidates))
                     (caar (gnosis-study-topic-candidates '("first-id"))))))
    (cl-letf (((symbol-function 'completing-read-multiple)
               (lambda (_ candidates &rest _)
                 (list (car (rassoc "second-id" candidates))
                       (car (rassoc "unique-id" candidates))))))
      (should (equal '("second-id" "unique-id") (gnosis-study-read-topics))))))

(ert-deftest gnosis-study-preview-cancel-and-empty-write-nothing ()
  (gnosis-test-study
    (gnosis-test-study-node "one")
    (let ((id (gnosis-test--add-basic-thema "Q" "A")) prompt)
      (gnosis--insert-into 'thema-links `([,id "one"]))
      (cl-letf (((symbol-function 'y-or-n-p) (lambda (s) (setq prompt s) nil)))
        (gnosis-practice-topic '("one")))
      (should (string-match-p (regexp-quote "1 thema (1 new, 0 not due)") prompt))
      (should (string-prefix-p "Practise without rescheduling: Same title" prompt))
      (should-not (string-match-p (rx (or "id:" "no cap" "Link depth")) prompt))
      (cl-letf (((symbol-function 'y-or-n-p) (lambda (s) (setq prompt s) nil)))
        (gnosis-practice-topic '("one") 1 2))
      (should (string-match-p "Link depth: 1 forward, 2 backward" prompt))
      (should-not (gnosis-select '* 'practice-events))
      (should-not (gnosis-select '* 'study-session))
      (gnosis-practice-topic '("missing"))
      (should-not (gnosis-select '* 'study-session)))))

(ert-deftest gnosis-study-real-practice-finite-tail-and-no-rescheduling ()
  (gnosis-test-study
    (let* ((a (gnosis-test--add-basic-thema "Q1" "A1"))
           (b (gnosis-test--add-basic-thema "Q2" "A2"))
           (before (gnosis-test-study-snapshot))
           (answers '("wrong" "A2" "wrong"))
           (calls 0) state)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) (pop answers)))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?n)))
        (setq state (gnosis-review-loop (lambda () (cl-incf calls) (list a b a)) 'practice)))
      (should (= 1 calls))
      (should-not answers)
      (should (equal before (gnosis-test-study-snapshot)))
      (should (= 3 (length (gnosis-select '* 'practice-events))))
      (should (equal (list a b a) (gnosis-select 'thema-id 'practice-events nil t)))
      (should (equal '(:selected 2 :unique 2 :attempts 3 :first-success 1 :first-failure 1
                       :retry-success 0 :retry-failure 1 :needs-work 1 :excluded 0 :unattempted 0)
                     (gnosis-review-summary state)))
      (should-not (gnosis-review-state-remaining (gnosis-review--read-session))))))

(ert-deftest gnosis-study-self-grade-reveal-both-modes-and-override ()
  (gnosis-test-study
    (dolist (mode '(practice due))
      (dolist (grade '(?y ?n))
        (let* ((id (gnosis-test--add-basic-thema "Explain mechanism" "Secret checklist" nil "Secret explanation"))
               (gnosis-review-basic-input 'self-grade)
               (before (gnosis-test-study-snapshot))
               (source (generate-new-buffer "*secret source*"))
               (keys (list ?\s grade ?o ?q))
               (checks 0))
          (with-current-buffer source (insert "Secret checklist"))
          (switch-to-buffer source)
          (delete-other-windows)
          (split-window-right)
          (cl-letf (((symbol-function 'read-char-choice)
                     (lambda (prompt &rest _)
                       (when (string-prefix-p "Recall first" prompt)
                         (cl-incf checks)
                         (should-not (get-buffer-window source))
                         (should-not (string-match-p "Secret" (buffer-string))))
                       (when (string-prefix-p "Recalled" prompt)
                         (should (string-match-p "Secret checklist" (buffer-string)))
                         (should (string-match-p "Secret explanation" (buffer-string))))
                       (pop keys))))
            (gnosis-review-loop (list id) mode))
          (should (= checks 1))
          (should (= 1 (gnosis-review-state-reviewed (gnosis-review--read-session))))
          (if (eq mode 'practice)
              (progn (should (equal before (gnosis-test-study-snapshot)))
                     (should (= (if (= grade ?y) 1 3)
                                (gnosis-get 'rating 'practice-events `(= thema-id ,id)))))
            (should (= (if (= grade ?y) 1 3)
                       (gnosis-get 'rating 'review-events `(= thema-id ,id)))))
          ;; Quit after a failure retains a retry; discard only the batch.
          (gnosis--delete 'study-session))))))

(ert-deftest gnosis-study-cancel-before-reveal-and-after-reveal ()
  (gnosis-test-study
    (dolist (reveal '(nil t))
      (let* ((id (gnosis-test--add-basic-thema "Q" "Answer"))
             (gnosis-review-basic-input 'self-grade)
             (before (gnosis-test-study-snapshot))
             (calls 0))
        (cl-letf (((symbol-function 'read-char-choice)
                   (lambda (&rest _) (cl-incf calls)
                     (if (and reveal (= calls 1)) ?\s (signal 'quit nil)))))
          (should (eq 'cancelled (condition-case nil (gnosis-review-loop (list id) 'practice)
                                   (quit 'cancelled)))))
        (should (equal before (gnosis-test-study-snapshot)))
        (should-not (gnosis-select '* 'practice-events))
        (should (equal (list id) (gnosis-review-state-remaining (gnosis-review--read-session))))
        (gnosis--delete 'study-session)))))

(ert-deftest gnosis-study-mid-session-removal-and-new-authoring ()
  (gnosis-test-study
    (let* ((a (gnosis-test--add-basic-thema "A" "a"))
           (b (gnosis-test--add-basic-thema "B" "b"))
           (c (gnosis-test--add-basic-thema "C" "c")) state)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) "a"))
                ((symbol-function 'read-char-choice)
                 (lambda (&rest _)
                   (gnosis--delete 'themata `(= id ,b))
                   (gnosis-toggle-suspend-themata (list c) 1 t)
                   (gnosis-test--add-basic-thema "New mid-batch" "d")
                   ?n)))
        (setq state (gnosis-review-loop (list a b c) 'practice)))
      (should (= 1 (plist-get (gnosis-review-summary state) :unique)))
      (should (= 2 (plist-get (gnosis-review-summary state) :excluded)))
      (should (= 2 (plist-get (gnosis-review-summary state) :unattempted)))
      (should (= 1 (length (gnosis-select '* 'practice-events)))))))

(ert-deftest gnosis-study-grade-checkpoint-atomic-failure-retry-and-reopen ()
  (gnosis-test-study
    (dolist (mode '(due practice))
      (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
             (buf (gnosis-test-study-state (list id) mode))
             (before (gnosis-test-study-snapshot)))
        (with-current-buffer buf
          (let ((pending (gnosis-review-algorithm id t))
                (saved (gnosis-get 'data 'study-session '(= id 1))))
            (cl-letf (((symbol-function 'gnosis-review--save-session)
                       (lambda (_) (error "Injected checkpoint failure"))))
              (should-error (gnosis-review-result id t pending)))
            (should (equal saved (gnosis-get 'data 'study-session '(= id 1))))
            (should (equal before (gnosis-test-study-snapshot)))
            (should-not (gnosis-select '* 'practice-events))
            (let ((real (symbol-function 'gnosis-review--write-result)) (calls 0))
              (cl-letf (((symbol-function 'gnosis-review--write-result)
                         (lambda (&rest args)
                           (cl-incf calls)
                           (if (= calls 1) (error "Transient write failure") (apply real args))))
                        ((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
                (gnosis-review--accept id t pending))
              (should (= calls 2)))
            (gnosis-review-result id t pending)
            (should (= 1 (gnosis-review-state-reviewed gnosis-review--state)))
            (gnosis-sqlite-close gnosis-db)
            (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
            (gnosis-db-init)
            (should-not (gnosis-review-state-remaining (gnosis-review--read-session)))
            (should (= 1 (gnosis-review-state-reviewed (gnosis-review--read-session))))))
      (gnosis--delete 'study-session)))))

(ert-deftest gnosis-study-undo-preserves-evidence-and-reanswers ()
  (gnosis-test-study
    (dolist (mode '(practice due))
      (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
             (buf (gnosis-test-study-state (list id) mode))
             (before (gnosis-test-study-snapshot)))
        (with-current-buffer buf
          (let* ((pending (gnosis-review-algorithm id nil)) event correction)
            (gnosis-review-result id nil pending)
            (let ((slot (gnosis-review-state-undo gnosis-review--state)))
              (setq event (plist-get slot :event-id) correction (plist-get slot :correction-id)))
            (gnosis-toggle-suspend-themata (list id) 1 t)
            (setq gnosis-review--state (gnosis-review-undo event correction))
            (gnosis-review-undo event correction)
            (should (gnosis-suspended-p id))
            (should (= 0 (gnosis-review-state-reviewed gnosis-review--state)))
            (should-error (gnosis-review-result id nil pending))
            (should-not (equal event (gnosis-review-state-event-id gnosis-review--state)))
            (gnosis-toggle-suspend-themata (list id) 0 t)
            (let ((next (gnosis-review-algorithm id t)))
              (gnosis-review-result id t next))
            (should (= 1 (gnosis-review-state-reviewed gnosis-review--state)))
            (if (eq mode 'practice)
                (should (equal before (gnosis-test-study-snapshot)))
              (should (= 1 (gnosis-get 'reps 'scheduler-state `(= thema-id ,id))))
              (should (= 2 (length (gnosis-select '* 'review-events `(= thema-id ,id)))))
              (should (= 1 (plist-get (gnosis-scheduler-replay-thema id 0) :reps))))))
      (gnosis--delete 'study-session)))))

(ert-deftest gnosis-study-retention-versioning-preview-race-and-replay ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
           (gnosis-review--state nil)
           (pending (gnosis-review-algorithm id t))
           (before (gnosis-test-study-snapshot)))
      (dolist (invalid '(0 1 -1 2 "0.9" 0.0e+NaN 1.0e+INF))
        (should-error (gnosis-scheduler-set-retention invalid)))
      (should (equal before (gnosis-test-study-snapshot)))
      (let ((new (gnosis-scheduler-set-retention 0.95)))
        (should (= new (gnosis-scheduler-set-retention 0.95)))
        (should-error (gnosis-review-result id t pending))
        (should (= 0 (gnosis-get 'reps 'scheduler-state `(= thema-id ,id))))
        (let ((pending (gnosis-review-algorithm id t))) (gnosis-review-result id t pending))
        (should (= new (gnosis-get 'config-id 'review-events `(= thema-id ,id))))
        (should (= new (gnosis-get 'config-id 'scheduler-state `(= thema-id ,id))))
        (gnosis-scheduler-set-retention 0.8)
        (let ((pending (gnosis-review-algorithm id t))) (gnosis-review-result id t pending))
        (should (= 2 (plist-get (gnosis-scheduler-replay-thema id 0) :reps)))
        (let ((new-id (gnosis-test--add-basic-thema "New" "Answer")))
          (should (= (gnosis-scheduler-active-config)
                     (gnosis-get 'config-id 'scheduler-state `(= thema-id ,new-id)))))
        (gnosis-sqlite-close gnosis-db)
        (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
        (should (= 0.8 (gnosis-scheduler--config-retention gnosis-db (gnosis-scheduler-active-config))))))))

(ert-deftest gnosis-study-v9-migration-and-rollback ()
  (gnosis-test-with-old-db
    (gnosis-test--create-v9-schema)
    (gnosis--insert-into 'themata '([1 "basic" "Q" ("") ("A") nil]))
    (gnosis--insert-into 'scheduler-baseline '([1 20260907 3 1]))
    (gnosis--insert-into 'scheduler-state '([1 1 nil nil nil nil 20260907 3 1 0]))
    (let ((before (gnosis-select '* 'scheduler-state))
          (set-version (symbol-function 'gnosis--db-set-version)))
      (cl-letf (((symbol-function 'gnosis--db-set-version)
                 (lambda (_) (error "Injected final migration failure"))))
        (should-error (gnosis-db--migrate-v10)))
      (should (= 9 (gnosis--db-version)))
      (should-not (gnosis-table-exists-p 'practice-events))
      (should (equal before (gnosis-select '* 'scheduler-state)))
      (funcall set-version 9)
      (gnosis-db-init)
      (should (= gnosis-db-version (gnosis--db-version)))
      (should (equal before (gnosis-select '* 'scheduler-state)))
      (should-not (sqlite-select gnosis-db "PRAGMA foreign_key_check"))
      (should (= 1 (gnosis-scheduler-active-config))))))

(ert-deftest gnosis-study-backup-keeps-evidence-content-export-does-not ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A" '("needs_work")))
           (buf (gnosis-test-study-state (list id) 'practice))
           (backup (expand-file-name "full.db" gnosis-dir))
           (content (expand-file-name "content.gnosis" gnosis-dir)))
      (with-current-buffer buf (gnosis-review-result id t (gnosis-review-algorithm id t)))
      (gnosis-backup-db backup)
      (should-error (gnosis-backup-db backup))
      (let ((copy (gnosis-sqlite-open backup)))
        (unwind-protect
            (progn
              (should (equal (gnosis-select '* 'practice-events)
                             (gnosis-sqlite-select copy "SELECT * FROM practice_events")))
              (should (equal (gnosis-select '* 'study-session)
                             (gnosis-sqlite-select copy "SELECT * FROM study_session"))))
          (gnosis-sqlite-close copy)))
      (gnosis-export-db content nil nil t)
      (let ((copy (gnosis-sqlite-open content)))
        (unwind-protect
            (progn (should-not (sqlite-select copy "SELECT name FROM sqlite_master WHERE name = 'practice_events'"))
                   (should (equal '(("needs_work")) (gnosis-sqlite-select copy "SELECT tag FROM thema_tag"))))
          (gnosis-sqlite-close copy))))))

(ert-deftest gnosis-study-repair-tag-real-editor-and-content-import ()
  (gnosis-test-study
    (let* ((gnosis-save-hook nil)
           (gnosis-review-editing-p nil)
           (id (gnosis-test--add-basic-thema "Original wording" "Answer"))
           (other (gnosis-test--add-basic-thema "Unrelated" "Other"))
           (before (gnosis-test-study-snapshot))
           (file (expand-file-name "flag.gnosis" gnosis-dir)))
      (gnosis-study-flag id)
      (gnosis-edit-thema id)
      (delete-region (line-beginning-position) (line-end-position))
      (insert "Clearer wording")
      (should (member "needs_work" (nth 6 (car (gnosis-export-parse-themata)))))
      (gnosis-save)
      (should (equal "Clearer wording" (gnosis-get 'keimenon 'themata `(= id ,id))))
      (should (member "needs_work" (gnosis-get-tags-for-ids (list id))))
      (should (equal "Unrelated" (gnosis-get 'keimenon 'themata `(= id ,other))))
      (should (equal before (gnosis-test-study-snapshot)))
      (gnosis-export-db file '("needs_work") nil t)
      (gnosis-study-flag id t)
      (gnosis-import--apply-changes file nil (list id)
                                    (gnosis-import--file-sha256 file))
      (should (member "needs_work" (gnosis-get-tags-for-ids (list id))))
      (gnosis-study-repair)
      (should (equal (list id) (mapcar #'car tabulated-list-entries)))
      (should (eq (keymap-lookup (current-local-map) "RET") #'gnosis-study-edit)))))

(ert-deftest gnosis-study-repair-binding-save-cancel-and-draft ()
  (dolist (source-kind '(standalone unindexed linked))
    (gnosis-test-study
      (let* ((gnosis-save-hook nil)
             (gnosis-review-editing-p nil)
             (gnosis-nodes-dir gnosis-dir)
             (org-id-track-globally nil)
             (context (if (eq source-kind 'standalone) ""
                        "[[id:source][Source]]"))
             (id (gnosis-test--add-basic-thema "Original wording" "Answer"
                                               '("needs_work") context))
             (file (expand-file-name "source.org" gnosis-dir))
             (source-text "* Source\n:PROPERTIES:\n:ID: source\n:END:\nSource passage\n"))
        (unless (eq source-kind 'standalone)
          (gnosis--insert-into 'thema-links `([,id "source"])))
        (when (eq source-kind 'linked)
          (with-temp-file file (insert source-text))
          (gnosis--insert-into 'nodes
                              '(["source" "source.org" "Source" "1" nil nil nil])))
        ;; Nonempty retained evidence makes deletion as well as writes visible.
        (gnosis-scheduler-accept-review (gnosis-scheduler-event-id) id
                                       'failure 1 20260901)
        (with-current-buffer (gnosis-test-study-state (list id) 'practice)
          (gnosis-review-result id nil (gnosis-review-algorithm id nil)))
        (let ((before (gnosis-test-study-snapshot))
              (practice (gnosis-select '* 'practice-events))
              (voids (gnosis-select '* 'practice-voids))
              (session (gnosis-select '* 'study-session)))
          (gnosis-study-repair)
          (goto-char (point-min))
          (should (equal id (tabulated-list-get-id)))
          (let ((repair (current-buffer)))
            (unless (eq source-kind 'linked)
              (should (equal '(user-error "No indexed source for this thema")
                             (should-error
                              (call-interactively (key-binding (kbd "v")))
                              :type 'user-error))))
            (call-interactively (key-binding (kbd "RET")))
            (should (derived-mode-p 'gnosis-edit-mode))
            (should (equal "*Gnosis Edit*" (buffer-name)))
            (when (eq source-kind 'linked)
              (should (get-buffer-window (get-file-buffer file)))
              (should (equal source-text
                             (with-current-buffer (get-file-buffer file)
                               (buffer-string)))))
            (delete-region (line-beginning-position) (line-end-position))
            (insert "Clearer wording")
            (let ((editor (current-buffer))
                  (draft (buffer-string))
                  (register (get-register :gnosis-edit)))
              (switch-to-buffer repair)
              (should-error (call-interactively (key-binding (kbd "RET")))
                            :type 'user-error)
              (should (eq (current-buffer) repair))
              (should (equal draft (with-current-buffer editor (buffer-string))))
              (should (eq register (get-register :gnosis-edit)))
              (switch-to-buffer editor))
            (call-interactively (key-binding (kbd "C-c C-c")))
            (should (equal "Clearer wording"
                           (gnosis-get 'keimenon 'themata `(= id ,id))))
            (should (equal context (gnosis-get 'parathema 'extras `(= id ,id))))
            (should (member "needs_work" (gnosis-get-tags-for-ids (list id))))
            (should (equal before (gnosis-test-study-snapshot)))
            (should (equal practice (gnosis-select '* 'practice-events)))
            (should (equal voids (gnosis-select '* 'practice-voids)))
            (should (equal session (gnosis-select '* 'study-session)))
            (switch-to-buffer repair)
            (call-interactively (key-binding (kbd "RET")))
            (should (derived-mode-p 'gnosis-edit-mode))
            (insert "Cancelled change ")
            (call-interactively (key-binding (kbd "C-c C-k")))
            (should-not (get-buffer "*Gnosis Edit*"))
            (if (eq source-kind 'linked)
                (progn
                  (should (equal file buffer-file-name))
                  (should (equal "source" (org-entry-get nil "ID")))
                  (should (equal source-text (buffer-string)))
                  (should-not (buffer-modified-p)))
              (should (eq repair (current-buffer))))
            (should (equal "Clearer wording"
                           (gnosis-get 'keimenon 'themata `(= id ,id))))
            (should (equal context (gnosis-get 'parathema 'extras `(= id ,id))))
            (should (equal before (gnosis-test-study-snapshot)))
            (should (equal practice (gnosis-select '* 'practice-events)))
            (should (equal voids (gnosis-select '* 'practice-voids)))
            (should (equal session (gnosis-select '* 'study-session)))))))))

(ert-deftest gnosis-study-delayed-evidence-excludes-practice-and-immediate ()
  (gnosis-test-study
    (let ((id (gnosis-test--add-basic-thema "Q" "A")))
      (cl-loop for day in '(20260901 20260903 20260903 20260905)
               for time from 1
               do (gnosis-scheduler-accept-review (gnosis-scheduler-event-id) id 'failure time day))
      (with-current-buffer (gnosis-test-study-state (list id) 'practice)
        (gnosis-review-result id nil (gnosis-review-algorithm id nil)))
      (should (equal (list (list id 2 2)) (gnosis-study-delayed-evidence)))
      (gnosis-study-repair)
      (should (equal (list id) (mapcar #'car tabulated-list-entries)))
      (should (equal "2 / 2" (aref (cadar tabulated-list-entries) 3))))))

(ert-deftest gnosis-study-source-id-and-editor-cancel ()
  (gnosis-test-study
    (gnosis-test-study-node "one")
    (gnosis-test-study-node "two")
    (let* ((id (gnosis-test--add-basic-thema "Q" "A" nil "[[id:two][Same title]]"))
           (source (generate-new-buffer "*Disposable source*"))
           (before (gnosis-test-study-snapshot)) visited)
      (gnosis--insert-into 'thema-links `([,id "two"]))
      (with-current-buffer source
        (org-mode)
        (insert "* Same title\n:PROPERTIES:\n:ID: two\n:END:\nSource content"))
      (gnosis-study-topic "two")
      (goto-char (point-min))
      (cl-letf (((symbol-function 'gnosis-nodes-goto-id)
                 (lambda (node) (setq visited node) (switch-to-buffer source))))
        (gnosis-study-edit)
        (should (equal "two" visited))
        (should (get-buffer-window source))
        (set-buffer-modified-p nil)
        (gnosis-edit-quit))
      (should (eq (current-buffer) source))
      (should (equal before (gnosis-test-study-snapshot)))
      (should-not (gnosis-select '* 'practice-events)))))

(ert-deftest gnosis-study-undo-stale-and-checkpoint-failure ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
           (buf (gnosis-test-study-state (list id) 'due)))
      (with-current-buffer buf
        (gnosis-review-result id t (gnosis-review-algorithm id t))
        (let* ((slot (gnosis-review-state-undo gnosis-review--state))
               (before (gnosis-test-study-snapshot))
               (data (gnosis-get 'data 'study-session '(= id 1))))
          (cl-letf (((symbol-function 'gnosis-review--save-session) (lambda (_) (error "Undo checkpoint failed"))))
            (should-error (gnosis-review-undo)))
          (should (equal before (gnosis-test-study-snapshot)))
          (should (equal data (gnosis-get 'data 'study-session '(= id 1))))
          (gnosis-scheduler-accept-review (gnosis-scheduler-event-id) id 'success
                                          (car (time-convert nil 1000000)) (gnosis--today-int))
          (should-error (gnosis-review-undo))
          (should-not (gnosis-select '* 'review-voids))
          (should-error (gnosis-review-undo (gnosis-scheduler-event-id) (plist-get slot :correction-id))))))))

(ert-deftest gnosis-study-resume-freezes-membership-and-input-style ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
           (gnosis-review-basic-input 'self-grade)
           (buf (gnosis-test-study-state (list id) 'practice))
           (state (with-current-buffer buf gnosis-review--state)))
      (should-error (gnosis-review-loop (list id) 'practice))
      (gnosis-test--add-basic-thema "New since pause" "B")
      (gnosis-sqlite-close gnosis-db)
      (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
      (let ((gnosis-review-basic-input 'typed) (keys '(?\s ?y ?n)))
        (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) (pop keys)))
                  ((symbol-function 'gnosis--read-string-with-input-method)
                   (lambda (&rest _) (ert-fail "Resume lost input policy"))))
          (gnosis-review-resume))
        (should-not keys))
      (should (equal (gnosis-review-state-session-id state)
                     (gnosis-review-state-session-id (gnosis-review--read-session))))
      (should (equal (list id) (gnosis-select 'thema-id 'practice-events nil t)))
      (should-not (gnosis-review-state-remaining (gnosis-review--read-session))))))

(ert-deftest gnosis-study-retention-rollback-and-immutable-configs ()
  (gnosis-test-study
    (let ((before (gnosis-test-study-snapshot))
          (real (symbol-function 'gnosis-sqlite-execute)))
      (cl-letf (((symbol-function 'gnosis-sqlite-execute)
                 (lambda (db sql &optional values)
                   (if (string-prefix-p "UPDATE scheduler_active" sql)
                       (error "Active pointer failed")
                     (funcall real db sql values)))))
        (should-error (gnosis-scheduler-set-retention 0.95)))
      (should (equal before (gnosis-test-study-snapshot)))
      (gnosis-scheduler-set-retention 0.95)
      (should (equal (car (car before)) (car (gnosis-select '* 'scheduler-config)))))))

(ert-deftest gnosis-study-post-commit-projection-failure-retry ()
  (gnosis-test-study
    (dolist (mode '(due practice))
      (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
             (buf (gnosis-test-study-state (list id) mode)))
        (with-current-buffer buf
          (let ((pending (gnosis-review-algorithm id nil))
                (read-session (symbol-function 'gnosis-review--read-session))
                (calls 0))
            (cl-letf (((symbol-function 'gnosis-review--read-session)
                       (lambda ()
                         (if (= (cl-incf calls) 2)
                             (error "Reply lost after commit")
                           (funcall read-session)))))
              (should-error (gnosis-review-result id nil pending)))
            (should (= 0 (gnosis-review-state-reviewed gnosis-review--state)))
            (let ((saved (gnosis-get 'data 'study-session '(= id 1))))
              (should (= 1 (plist-get saved :reviewed)))
              (gnosis-scheduler-set-retention 0.95)
              ;; A retained retry ignores later configuration changes.
              (gnosis-review-result id nil pending)
              (should (equal saved (gnosis-get 'data 'study-session '(= id 1)))))
            (should (= 1 (gnosis-review-state-reviewed gnosis-review--state)))
            (should (equal (list id) (gnosis-review-state-requeued gnosis-review--state)))
            (should (equal (list id) (gnosis-review-state-remaining gnosis-review--state)))
            (should (= 1 (length (gnosis-select '* (if (eq mode 'due) 'review-events 'practice-events)
                                                 `(= thema-id ,id)))))
            (should (gnosis-review-state-undo gnosis-review--state))))))))

(ert-deftest gnosis-study-stale-skip-preserves-authoritative-session ()
  (gnosis-test-study
    (dolist (mode '(due practice))
      (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
             (buf (gnosis-test-study-state (list id) mode))
             (stale (gnosis-review--read-session)))
        (with-current-buffer buf (gnosis-review-result id t (gnosis-review-algorithm id t)))
        (gnosis-toggle-suspend-themata (list id) 1 t)
        (let ((saved (gnosis-get 'data 'study-session '(= id 1))))
          (should-error (gnosis-review-session stale))
          (should (equal saved (gnosis-get 'data 'study-session '(= id 1)))))
        (gnosis-test-study-state (list id) mode)
        (let ((replacement (gnosis-get 'data 'study-session '(= id 1))))
          (should-error (gnosis-review--skip stale id))
          (should (equal replacement (gnosis-get 'data 'study-session '(= id 1)))))))))

(ert-deftest gnosis-study-preview-invalidated-by-review-void ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
           (event (gnosis-scheduler-event-id)))
      (gnosis-scheduler-accept-review event id 'success 1 20260901)
      (with-current-buffer (gnosis-test-study-state (list id) 'due)
        (let ((pending (gnosis-review--pending-result id t nil 2 20260905)))
          (gnosis-scheduler-void-review (gnosis-scheduler-event-id) event)
          (let ((before (gnosis-test-study-snapshot))
                (saved (gnosis-get 'data 'study-session '(= id 1))))
            (should-error (gnosis-review-result id t pending))
            (should (equal before (gnosis-test-study-snapshot)))
            (should (equal saved (gnosis-get 'data 'study-session '(= id 1))))))))))

(ert-deftest gnosis-study-practice-identity-conflict-and-write-rollback ()
  (gnosis-test-study
    (let ((id (gnosis-test--add-basic-thema "Q" "A")))
      (with-current-buffer (gnosis-test-study-state (list id) 'practice)
        (let ((pending (gnosis-review-algorithm id t))
              (execute (symbol-function 'gnosis-sqlite-execute))
              (before (gnosis-test-study-snapshot)))
          (cl-letf (((symbol-function 'gnosis-sqlite-execute)
                     (lambda (db sql &optional values)
                       (prog1 (funcall execute db sql values)
                         (when (string-prefix-p "INSERT INTO practice_events" sql)
                           (error "Failure after event insertion"))))))
            (should-error (gnosis-review-result id t pending)))
          (should-not (gnosis-select '* 'practice-events))
          (should (= 0 (gnosis-review-state-reviewed (gnosis-review--read-session))))
          (gnosis-review-result id t pending)
          (should-error (gnosis-study-accept-practice
                         (plist-put (copy-sequence pending) :outcome 'failure)))
          (should (equal before (gnosis-test-study-snapshot)))
          (should (= 1 (length (gnosis-select '* 'practice-events)))))))))

(ert-deftest gnosis-study-editor-preserves-source-and-existing-draft ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A" '("needs_work") "[[id:source][Source]]"))
           (source (generate-new-buffer "*Study source*"))
           (text "Source text must not be replaced"))
      (switch-to-buffer source)
      (insert text)
      (gnosis-edit-thema id)
      (should (equal "*Gnosis Edit*" (buffer-name)))
      (should (member "needs_work" (nth 6 (car (gnosis-export-parse-themata)))))
      (insert "Reworded ")
      (let ((draft (buffer-string)) (register (get-register :gnosis-edit)))
        (should-error (gnosis-edit-thema id))
        (should (equal draft (buffer-string)))
        (should (eq register (get-register :gnosis-edit))))
      (should (equal text (with-current-buffer source (buffer-string))))
      (let ((gnosis-save-hook nil)) (gnosis-save))
      (should (equal text (with-current-buffer source (buffer-string))))
      (should (equal "[[id:source][Source]]" (gnosis-get 'parathema 'extras `(= id ,id)))))))

(ert-deftest gnosis-study-replacement-and-discard-races ()
  (gnosis-test-study
    (let ((id (gnosis-test--add-basic-thema "Q" "A")) saved)
      (should-error
       (gnosis-review-loop
        (lambda ()
          (gnosis-test-study-state (list id) 'practice)
          (setq saved (gnosis-get 'data 'study-session '(= id 1)))
          (list id)) 'practice))
      (should (equal saved (gnosis-get 'data 'study-session '(= id 1))))
      (cl-letf (((symbol-function 'y-or-n-p)
                 (lambda (&rest _)
                   (gnosis-test-study-state (list id) 'practice)
                   (setq saved (gnosis-get 'data 'study-session '(= id 1)))
                   t)))
        (should-error (gnosis-review-discard)))
      (should (equal saved (gnosis-get 'data 'study-session '(= id 1)))))))

(ert-deftest gnosis-study-summary-flag-distinction-and-commit ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A" '("needs_work")))
           committed state)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method) (lambda (&rest _) "A"))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?n))
                ((symbol-function 'gnosis-review-commit) (lambda (n) (setq committed n))))
        (setq state (gnosis-review-loop (list id) 'practice)))
      (should (= 1 committed))
      (should (= 0 (plist-get (gnosis-review-summary state) :needs-work)))
      (gnosis-review--show-summary state)
      (should (string-match-p "Last-attempt failures (not manual flags): 0" (buffer-string)))
      (should (member "needs_work" (gnosis-get-tags-for-ids (list id)))))))

(ert-deftest gnosis-study-native-subtree-membership ()
  (gnosis-test-study
    (with-temp-buffer
      (org-mode)
      (insert "* Parent\n:PROPERTIES:\n:ID: root\n:END:\n** Child\n:PROPERTIES:\n:ID: child\n:END:\n*** ID-less\nProse\n* Outside\n:PROPERTIES:\n:ID: outside\n:END:\n")
      (goto-char (point-min))
      (search-forward "** Child")
      (let (selected)
        (cl-letf (((symbol-function 'gnosis-study--start)
                   (lambda (ids mode &rest _) (setq selected (cons mode ids)))))
          (gnosis-study-subtree)
          (should (equal '(practice "child") selected))
          (gnosis-study-subtree t)
          (should (equal '(due "child") selected)))))))

(ert-deftest gnosis-study-owned-buffer-boundaries ()
  (gnosis-test-study
    (let ((buf (get-buffer-create gnosis-review-buffer-name))
          (audit (get-buffer-create "*Gnosis History Evidence*")))
      (with-current-buffer buf (insert "Unrelated draft"))
      (with-current-buffer audit (insert "Unrelated history draft"))
      (should-error (gnosis-review--setup-buffer nil))
      (gnosis-study-history-audit)
      (should (equal "Unrelated draft" (with-current-buffer buf (buffer-string))))
      (should (equal "Unrelated history draft" (with-current-buffer audit (buffer-string)))))))

(ert-deftest gnosis-study-undo-refreshes-summary-after-commit ()
  (gnosis-test-study
    (dolist (mode '(due practice))
      (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
             (buf (gnosis-test-study-state (list id) mode)))
        (with-current-buffer buf
          (gnosis-review-result id t (gnosis-review-algorithm id t)))
        (let* ((slot (gnosis-review-state-undo (gnosis-review--read-session)))
               (event (plist-get slot :event-id))
               (correction (plist-get slot :correction-id))
               (show (symbol-function 'gnosis-review--show-summary)))
          (cl-letf (((symbol-function 'gnosis-review--show-summary)
                     (lambda (_) (error "Summary failed after correction commit"))))
            (should-error (gnosis-review-undo event correction)))
          (should (= 0 (gnosis-review-state-reviewed (gnosis-review--read-session))))
          (cl-letf (((symbol-function 'gnosis-review--show-summary)
                     (lambda (state)
                       (should (equal (gnosis-review--state-data state)
                                      (gnosis-get 'data 'study-session '(= id 1))))
                       (funcall show state))))
            (let ((restored (gnosis-review-undo event correction)))
              (should (= 0 (gnosis-review-state-reviewed restored)))
              (should (equal (list id) (gnosis-review-state-remaining restored)))
              (with-current-buffer (window-buffer (selected-window))
                (should (string-match-p "Accepted attempts: 0" (buffer-string)))))))
        (gnosis--delete 'study-session)))))

(ert-deftest gnosis-study-large-identities-in-checkpoint-and-evidence ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A" nil nil (1+ most-positive-fixnum)))
           (buf (gnosis-test-study-state (list id) 'practice)))
      (with-current-buffer buf
        (gnosis-review-result id nil (gnosis-review-algorithm id nil))
        (setq gnosis-review--state (gnosis-review--read-session))
        (let ((decoded (car (gnosis-review-state-remaining gnosis-review--state))))
          (should (equal id decoded))
          (should-not (eq id decoded))
          (gnosis-review-result decoded t (gnosis-review-algorithm decoded t))))
      (let ((summary (gnosis-review-summary (gnosis-review--read-session))))
        (should (= 1 (plist-get summary :unique)))
        (should (= 1 (plist-get summary :first-failure)))
        (should (= 1 (plist-get summary :retry-success)))
        (should (= 0 (plist-get summary :needs-work))))
      (cl-loop for day in '(20260901 20260903 20260905)
               for time from 1
               do (gnosis-scheduler-accept-review (gnosis-scheduler-event-id) id 'failure time day))
      (gnosis-study-repair)
      (should (equal "2 / 2" (aref (cadar tabulated-list-entries) 3))))))

(defun gnosis-test-study-reject-alternate-replacement (table migrated)
  "Check TABLE alternate-key replacement and hard deletion after MIGRATED setup."
  (gnosis-test-with-old-db
    (when migrated
      (gnosis-test--create-v9-schema)
      (should (= 9 (gnosis--db-version))))
    (gnosis-db-init)
    (should (= gnosis-db-version (gnosis--db-version)))
    ;; REPLACE must be rejected without depending on recursive delete triggers.
    (gnosis-sqlite-execute gnosis-db "PRAGMA recursive_triggers = OFF")
    (should (equal '((0)) (gnosis-sqlite-select gnosis-db "PRAGMA recursive_triggers")))
    (let ((id (gnosis-test--add-basic-thema "Q" "A")))
      (gnosis-scheduler-accept-review (make-string 64 ?a) id 'success 100 20260907)
      (gnosis-sqlite-execute gnosis-db
        "INSERT INTO practice_events VALUES ('practice-old', ?, 'session', 1, 100, 3)"
        (list id))
      (gnosis-sqlite-execute gnosis-db
        "INSERT INTO practice_voids VALUES ('practice-correction', 'practice-old')")
      (gnosis-sqlite-execute gnosis-db
        "INSERT INTO review_voids SELECT 'review-correction', event_id FROM review_events")
      (let* ((tables '(review_events review_voids practice_events practice_voids))
             (snapshot (lambda ()
                         (mapcar (lambda (name)
                                   (gnosis-sqlite-select gnosis-db
                                     (format "SELECT * FROM %s ORDER BY 1" name)))
                                 tables)))
             (before (funcall snapshot))
             (schedule (gnosis-test-study-snapshot)))
        (should (seq-every-p #'consp before))
        (should-error
         (gnosis-sqlite-execute gnosis-db
           (pcase-exhaustive table
             ('practice_events
              "INSERT OR REPLACE INTO practice_events
               SELECT 'practice-new', thema_id, session_id, attempt, 200, 1
                 FROM practice_events WHERE event_id = 'practice-old'")
             ('practice_voids
              "INSERT OR REPLACE INTO practice_voids
               VALUES ('practice-correction-new', 'practice-old')")
             ('review_voids
              "INSERT OR REPLACE INTO review_voids
               SELECT 'review-correction-new', event_id FROM review_events")))
         :type 'sqlite-error)
        (should (equal before (funcall snapshot)))
        (should (equal schedule (gnosis-test-study-snapshot)))
        (gnosis--delete 'themata `(= id ,id))
        (should-not (gnosis-select '* 'themata))
        (should (seq-every-p #'null (funcall snapshot)))
        (should-not (gnosis-sqlite-select gnosis-db "PRAGMA foreign_key_check"))))))

(ert-deftest gnosis-study-practice-event-alternate-replacement-fresh ()
  (gnosis-test-study-reject-alternate-replacement 'practice_events nil))

(ert-deftest gnosis-study-practice-event-alternate-replacement-v9 ()
  (gnosis-test-study-reject-alternate-replacement 'practice_events t))

(ert-deftest gnosis-study-practice-void-alternate-replacement-fresh ()
  (gnosis-test-study-reject-alternate-replacement 'practice_voids nil))

(ert-deftest gnosis-study-practice-void-alternate-replacement-v9 ()
  (gnosis-test-study-reject-alternate-replacement 'practice_voids t))

(ert-deftest gnosis-study-review-void-alternate-replacement-fresh ()
  (gnosis-test-study-reject-alternate-replacement 'review_voids nil))

(ert-deftest gnosis-study-review-void-alternate-replacement-v9 ()
  (gnosis-test-study-reject-alternate-replacement 'review_voids t))

(ert-deftest gnosis-study-summary-skipped-retry-is-not-unattempted ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
           (before (gnosis-test-study-snapshot))
           state)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) "wrong"))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?q)))
        (setq state (gnosis-review-loop (list id) 'practice)))
      (should (equal (list id) (gnosis-review-state-remaining state)))
      (gnosis-toggle-suspend-themata (list id) 1 t)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) (ert-fail "Suspended retry must not prompt"))))
        (gnosis-review-resume))
      (setq state (gnosis-review--read-session))
      (let ((summary (gnosis-review-summary state)))
        (should (= 1 (plist-get summary :selected)))
        (should (= 1 (plist-get summary :unique)))
        (should (= 1 (gnosis-review-state-reviewed state)))
        (should (= 0 (plist-get summary :unattempted)))
        (should (= 1 (plist-get summary :excluded))))
      (gnosis-review--show-summary state)
      (should (string-match-p "Unattempted: 0\nSkipped items (including retries): 1\n"
                              (buffer-string)))
      (gnosis-toggle-suspend-themata (list id) 0 t)
      (should (equal before (gnosis-test-study-snapshot))))))

(ert-deftest gnosis-study-repair-help-offers-only-contextual-actions ()
  (gnosis-test-study
    (gnosis-test-study-node "topic")
    (let (help)
      (cl-letf (((symbol-function 'keymap-popup)
                 (lambda (map &rest _)
                   (setq help (keymap-popup--render (keymap-popup--meta map 'descriptions))))))
        (gnosis-study-repair)
        (call-interactively (key-binding (kbd "?")))
        (dolist (text '("Review due" "Practise (no rescheduling)" "Create thema"))
          (should-not (string-match-p (regexp-quote text) help)))
        (dolist (key '("d" "p" "c"))
          (should (memq (key-binding (kbd key)) '(nil undefined))))
        (should (string-match-p "Open topic" help))
        (should (eq 'gnosis-study-topic (key-binding (kbd "o"))))
        (should (eq 'gnosis-study-edit (key-binding (kbd "RET"))))
        (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Same title")))
          (call-interactively (key-binding (kbd "o"))))
        (should (equal "topic" gnosis-study--topic))
        (call-interactively (key-binding (kbd "?")))
        (dolist (text '("Review due" "Practise (no rescheduling)" "Create thema"))
          (should (string-match-p (regexp-quote text) help)))
        (dolist (entry '(("d" . gnosis-study-due) ("p" . gnosis-study-practice)
                         ("c" . gnosis-study-create)))
          (should (eq (cdr entry) (key-binding (kbd (car entry))))))))))

(provide 'gnosis-test-study)
;;; gnosis-test-study.el ends here
