;;; gnosis-test-agent.el --- Native agent handoff regressions -*- lexical-binding: t; -*-

(require 'ert)
(require 'json)
(require 'gnosis-agent)
(require 'gnosis-test-helpers)
(require 'gnosis-test-schema-v8)

(defmacro gnosis-test-agent (&rest body)
  "Run BODY with isolated data, UI and deterministically captured timers."
  (declare (indent 0) (debug t))
  `(gnosis-test-with-db
     (let ((buffers (buffer-list))
           (gnosis-agent--launches nil)
           (gnosis-review--running nil)
           (gnosis-review-buffer-name "*Gnosis Agent Test*")
           (gnosis-review-basic-input 'typed)
           (gnosis-monkeytype-enable nil)
           (gnosis-center-content nil)
           (register-alist nil))
       (save-window-excursion
         (unwind-protect
             (cl-letf (((symbol-function 'run-with-timer) (lambda (&rest _) nil)))
                      ,@body)
           (mapc #'gnosis-agent--release (copy-sequence gnosis-agent--launches))
           (dolist (buffer (seq-difference (buffer-list) buffers))
             (when (buffer-live-p buffer)
               (with-current-buffer buffer (set-buffer-modified-p nil))
               (kill-buffer buffer))))))))

(defun gnosis-test-agent-start (ids &optional policy)
  "Start practice for IDS and optional POLICY, returning its identity."
  (plist-get (gnosis-agent-start-practice :thema-ids ids :limit (length ids) :policy policy)
             :session-id))

(defun gnosis-test-agent-grade (success)
  "Accept SUCCESS through the real core for the current queued thema."
  (let* ((gnosis-review--state (gnosis-review--read-session))
         (id (car (gnosis-review-state-remaining gnosis-review--state))))
    (gnosis-review-result id success (gnosis-review-algorithm id success))))

(defun gnosis-test-agent-snapshot ()
  "Return every scheduling authority row, including nonempty evidence."
  (mapcar (lambda (table) (gnosis-select '* table))
          '(scheduler-config scheduler-active scheduler-baseline scheduler-state
                             review-events review-voids review-activity-baseline)))

(ert-deftest gnosis-agent-policy-validation-and-streak ()
  (let ((policy (gnosis-review-practice-policy)))
    (should (equal policy '(:successes-required 1 :successes-after-failure 2
                                                :consecutive t :max-attempts-per-thema 5)))
    (should (equal "target-reached" (plist-get (gnosis-review-policy-progress policy '(t)) :reason)))
    (should (equal "unfinished" (plist-get (gnosis-review-policy-progress policy '(t nil t nil)) :reason)))
    (should (equal "attempt-limit" (plist-get (gnosis-review-policy-progress policy '(t nil t nil nil)) :reason)))
    (should (equal "target-reached" (plist-get (gnosis-review-policy-progress policy '(t t nil t nil)) :reason)))
    (should (equal "target-reached" (plist-get (gnosis-review-policy-progress
                                                (gnosis-review-practice-policy '(:consecutive nil))
                                                '(t nil t nil)) :reason)))
    (dolist (bad '((:unknown 1) (:successes-required 0) (:successes-after-failure -1)
                   (:max-attempts-per-thema 2.0) (:consecutive yes)
                   (:consecutive t :consecutive nil) (:consecutive) (a . b)))
      (should-error (gnosis-review-practice-policy bad) :type 'user-error))))

(ert-deftest gnosis-agent-selection-limit-empty-and-json ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (gnosis-test--add-basic-thema "B" "b" nil nil 102)
    (gnosis-test--add-basic-thema "C" "c" nil nil 103 1)
    (let* ((status (gnosis-agent-start-practice :thema-ids '(103 102 101 101 999) :limit 1))
           (id (plist-get status :session-id)))
      (should (equal "pending" (plist-get status :status)))
      (should (equal [101] (plist-get status :selected-ids)))
      (should (= 1 (plist-get (plist-get status :selection) :omitted-by-limit)))
      (should (equal [103 999] (plist-get (plist-get status :selection) :excluded-ids)))
      (should-not (gnosis-select '* 'practice-events))
      (should-not (get-buffer gnosis-review-buffer-name))
      (let ((json (json-serialize (gnosis-agent-results id) :false-object :false :null-object nil)))
        (should (string-match-p "\"schedule-updated\":false" json))
        (should (string-match-p "\"events\":\\[\\]" json))
        (should (string-match-p "\"deleted\":false" json)))
      (gnosis-agent-cancel id))
    (let* ((status (gnosis-agent-start-practice :thema-ids '(103 999) :limit 4))
           (id (plist-get status :session-id)))
      (should (equal "completed" (plist-get status :status)))
      (should (= 4 (plist-get (plist-get status :selection) :shortfall)))
      (should (equal [] (plist-get (gnosis-agent-results id) :items))))
    (dolist (args '((:thema-ids (101)) (:thema-ids (101) :limit 0)
                    (:thema-ids (101) :topic-ids ("topic") :limit 1)
                    (:thema-ids ("101") :limit 1) (:topic-ids (42) :limit 1)
                    (:thema-ids (101 . 102) :limit 1)))
      (should-error (apply #'gnosis-agent-start-practice args) :type 'user-error))))

(ert-deftest gnosis-agent-topic-direct-identity-and-shortfall ()
  (gnosis-test-agent
    (gnosis--insert-into 'nodes '(["one" "f.org" "Same" "1" nil nil nil]
                                  ["two" "f.org" "Same" "1" nil nil nil]))
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (gnosis-test--add-basic-thema "B" "b" nil nil 102)
    (gnosis--insert-into 'thema-links '([101 "one"] [101 "two"] [102 "two"]))
    (gnosis--insert-into 'node-links '(["one" "two"]))
    (let ((status (gnosis-agent-start-practice :topic-ids '("one" "one") :limit 3)))
      (should (equal [101] (plist-get status :selected-ids)))
      (should (= 2 (plist-get (plist-get status :selection) :shortfall)))
      (gnosis-agent-cancel (plist-get status :session-id)))
    (should-error (gnosis-agent-start-practice :topic-ids '("missing") :limit 1))))

(ert-deftest gnosis-agent-native-deferred-repetition-history-and-fsrs-isolation ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (gnosis-test--add-basic-thema "B" "b" nil nil 102)
    ;; Nonempty scheduling history makes the no-write assertion substantive.
    (gnosis-scheduler-accept-review (gnosis-scheduler-event-id) 101 'success
                                    1780000000000000 (gnosis--today-int))
    (let* ((before (gnosis-test-agent-snapshot))
           (session (gnosis-test-agent-start '(101 102)))
           (record (car gnosis-agent--launches))
           (answers '("wrong" "b" "a" "a")))
      (should (equal "pending" (plist-get (gnosis-agent-status session) :status)))
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) (should (equal "running" (plist-get (gnosis-agent-status session) :status)))
                   (pop answers)))
                ((symbol-function 'gnosis-review--read-action) (lambda (&rest _) ?n)))
        (gnosis-agent--launch record))
      (should-not answers)
      (should (equal '(101 102 101 101) (gnosis-select 'thema-id 'practice-events nil t)))
      (should (equal before (gnosis-test-agent-snapshot)))
      (let* ((result (gnosis-agent-results session))
             (summary (plist-get result :summary)))
        (should (equal "completed" (plist-get result :status)))
        (should (= 1 (plist-get summary :first-success)))
        (should (= 1 (plist-get summary :first-failure)))
        (should (= 2 (plist-get summary :retry-success)))
        (should (seq-every-p (lambda (item) (equal "target-reached" (plist-get item :reason)))
                             (plist-get result :items)))
        (gnosis-agent-start-practice :thema-ids '(102) :limit 1)
        (should (equal result (gnosis-agent-results session)))
        (should-error (gnosis-agent-resume session))
        (should-error (gnosis-agent-results "unknown"))
        ;; Reopen proves historical readback has no buffer/global dependence.
        (gnosis-sqlite-close gnosis-db)
        (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
        (should (equal result (gnosis-agent-results session)))))))

(ert-deftest gnosis-agent-cap-reset-and-interleaving ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (gnosis-test--add-basic-thema "B" "b" nil nil 102)
    (let ((session (gnosis-test-agent-start '(101 102) '(:successes-required 2))))
      (dolist (success '(nil nil t t nil nil t nil nil nil))
        (gnosis-test-agent-grade success))
      (should (equal '(101 102 101 102 101 102 101 102 101 102)
                     (gnosis-select 'thema-id 'practice-events nil t)))
      (let ((result (gnosis-agent-results session)))
        (should (equal "completed" (plist-get result :status)))
        (should (seq-every-p (lambda (item) (and (= 5 (plist-get item :attempts))
                                                 (equal "attempt-limit" (plist-get item :reason))))
                             (plist-get result :items)))))))

(ert-deftest gnosis-agent-cancel-stale-launch-and-successor ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (let* ((session (gnosis-test-agent-start '(101)))
           (old (car gnosis-agent--launches)))
      (should (equal "cancelled" (plist-get (gnosis-agent-cancel session) :status)))
      (should (equal "cancelled" (plist-get (gnosis-agent-cancel session) :status)))
      (let* ((new (gnosis-test-agent-start '(101)))
             (before (gnosis-agent-status new)))
        (let (launched)
          (cl-letf (((symbol-function 'gnosis-review--resume)
                     (lambda (&rest _) (setq launched t))))
            (gnosis-agent--launch old))
          (should-not launched))
        (should (equal before (gnosis-agent-status new)))
        (should-error (gnosis-agent-resume session))))))

(ert-deftest gnosis-agent-launch-owner-mismatch-and-quit-containment ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (let ((session (gnosis-test-agent-start '(101))))
      (let ((record (car gnosis-agent--launches)) (gnosis-db nil))
        (gnosis-agent--launch record)
        (should-not gnosis-db))
      (should (equal "unfinished" (plist-get (gnosis-agent-status session) :status)))
      (gnosis-agent-resume session)
      (let ((gnosis-dir (make-temp-name "/tmp/other-gnosis-")))
        (gnosis-agent--launch (car gnosis-agent--launches)))
      (should (equal "unfinished" (plist-get (gnosis-agent-status session) :status)))
      (gnosis-agent-resume session)
      (let ((gnosis-review--running "another"))
        (should-error (gnosis-agent-cancel session))
        (gnosis-agent--launch (car gnosis-agent--launches)))
      (should (equal "unfinished" (plist-get (gnosis-agent-status session) :status)))
      (gnosis-agent-resume session)
      (let (escaped)
        (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                   (lambda (&rest _) (signal 'quit nil))))
          (condition-case nil (gnosis-agent--launch (car gnosis-agent--launches))
            (quit (setq escaped t))))
        (should-not escaped))
      (should-not (gnosis-select '* 'practice-events))
      (should (equal "unfinished" (plist-get (gnosis-agent-status session) :status))))))

(ert-deftest gnosis-agent-resume-token-and-native-resume-invalidate-old-launch ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (let* ((session (gnosis-test-agent-start '(101))) (old (car gnosis-agent--launches)))
      (gnosis-agent-resume session)
      (let ((new (car gnosis-agent--launches)))
        (gnosis-agent--launch old)
        (should (memq new gnosis-agent--launches))
        (cl-letf (((symbol-function 'gnosis-review--run-state) (lambda (_ _state) nil)))
          (gnosis-review-resume))
        (let (launched)
          (cl-letf (((symbol-function 'gnosis-review--resume)
                     (lambda (&rest _) (setq launched t))))
            (gnosis-agent--launch new))
          (should-not launched))
        (should (equal "unfinished" (plist-get (gnosis-agent-status session) :status)))))))

(ert-deftest gnosis-agent-policy-undo-and-history-atomicity ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (let* ((policy (list :successes-required 2))
           (session (gnosis-test-agent-start '(101) policy)))
      (setcar (cdr policy) 99)
      (gnosis-test-agent-grade nil)
      (gnosis-test-agent-grade t)
      (let ((before (gnosis-agent-results session))
            (state (gnosis-review--state-data (gnosis-review--read-session))))
        (cl-letf (((symbol-function 'gnosis-review--save-history) (lambda (_) (error "History disk fault"))))
          (should-error (gnosis-test-agent-grade t))
          (should-error (gnosis-review-undo)))
        (should (equal before (gnosis-agent-results session)))
        (should (equal state (gnosis-review--state-data (gnosis-review--read-session))))
        (should-not (gnosis-select '* 'practice-voids)))
      (gnosis-review-undo)
      (let* ((result (gnosis-agent-results session))
             (events (plist-get (aref (plist-get result :items) 0) :events)))
        (should (= 2 (length events)))
        (should (eq :false (plist-get (aref events 1) :effective)))
        (should (stringp (plist-get (aref events 1) :correction-id)))
        (should (= 0 (plist-get (plist-get result :summary) :retry-success))))
      (gnosis-test-agent-grade t)
      (should (gnosis-review-state-remaining (gnosis-review--read-session)))
      (gnosis-test-agent-grade t)
      (should (equal "completed" (plist-get (gnosis-agent-results session) :status)))
      (should (= 2 (plist-get (plist-get (gnosis-agent-status session) :policy) :successes-required)))
      (should (= 4 (length (gnosis-select '* 'practice-events)))))))

(ert-deftest gnosis-agent-deletion-and-exclusion-do-not-invent-evidence ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (gnosis-test--add-basic-thema "B" "b" nil nil 102)
    (let ((session (gnosis-test-agent-start '(101 102))))
      (gnosis-test-agent-grade t)
      (gnosis--delete 'themata '(= id 101))
      (gnosis-update 'scheduler-state '(= suspended 1) '(= thema-id 102))
      (gnosis-agent--launch (car gnosis-agent--launches))
      (let ((result (gnosis-agent-results session)))
        (should (equal "completed" (plist-get result :status)))
        (should (= 0 (plist-get (plist-get result :summary) :attempts)))
        (should (seq-every-p (lambda (item) (equal "excluded" (plist-get item :reason)))
                             (plist-get result :items)))
        (should (eq t (plist-get (aref (plist-get result :items) 0) :deleted)))
        (should (equal [] (plist-get (aref (plist-get result :items) 0) :events)))))))

(ert-deftest gnosis-agent-reopen-retains-checkpoint-and-events ()
  (let* ((dir (make-temp-file "gnosis-agent-migrate-" t))
         (gnosis-dir dir) (gnosis-testing t)
         (gnosis-db (gnosis-sqlite-open (expand-file-name "gnosis.db" dir))))
    (unwind-protect
        (progn
          (gnosis-db-init)
          (gnosis-test--add-basic-thema "A" "a" nil nil 101)
          (let ((data '(:version 1 :session-id "old-session" :mode practice
                                 :initial 1 :total 2 :reviewed 1 :remaining (101)
                                 :requeued (101) :outcomes ((101)) :basic-input typed)))
            (gnosis-sqlite-execute gnosis-db "INSERT INTO study_session VALUES (1, ?)" (list data))
            (gnosis-sqlite-execute gnosis-db "INSERT INTO practice_events VALUES (?, ?, ?, ?, ?, ?)"
                                   '("old-event" 101 "old-session" 1 1000000 1))
            (let ((before (gnosis-select '* 'practice-events)))
              (gnosis-sqlite-execute gnosis-db "INSERT INTO study_history VALUES (?, ?)"
                                     (list "old-session" data))
              (gnosis-sqlite-close gnosis-db)
              (setq gnosis-db (gnosis-sqlite-open (expand-file-name "gnosis.db" dir)))
              (gnosis-db-init)
              (should (= 11 (gnosis--db-version)))
              (should (equal data (gnosis-get 'data 'study-history '(= session-id "old-session"))))
              (should (equal data (gnosis-get 'data 'study-session '(= id 1))))
              (should (equal before (gnosis-select '* 'practice-events)))
              (should-not (gnosis-review-state-policy (gnosis-review--read-session)))
              (cl-letf (((symbol-function 'run-with-timer) (lambda (&rest _) nil)))
                (let ((gnosis-agent--launches nil))
                  (gnosis-agent-start-practice :thema-ids '(101) :limit 1)))
              (should (plist-get (gnosis-get 'data 'study-history
                                            '(= session-id "old-session")) :cancelled-p))
              (should (equal before (gnosis-select '* 'practice-events))))))
      (gnosis-sqlite-close gnosis-db)
      (delete-directory dir t))))

(ert-deftest gnosis-agent-cap-summary-discloses-unmet-target-after-success ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (let* ((session (gnosis-test-agent-start '(101) '(:max-attempts-per-thema 2)))
           (answers '("wrong" "a")))
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) (pop answers)))
                ((symbol-function 'gnosis-review--read-action) (lambda (&rest _) ?n)))
        (gnosis-agent--launch (car gnosis-agent--launches)))
      (let ((result (gnosis-agent-results session)))
        (should (= 0 (plist-get (plist-get result :summary) :needs-work)))
        (should (= 1 (plist-get (plist-get result :targets) :attempt-limit)))
        (should (= 0 (plist-get (plist-get result :targets) :target-reached))))
      (with-current-buffer "*Gnosis Study Summary*"
        (should (string-match-p "Targets reached: 0" (buffer-string)))
        (should (string-match-p "Attempt limit (target unmet): 1" (buffer-string)))
        (should (string-match-p "cap: 2 effective attempts" (buffer-string)))))))

(ert-deftest gnosis-agent-minibuffer-and-timer-failure-leave-resumable-batch ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (let ((session (gnosis-test-agent-start '(101))))
      (let (launched)
        (cl-letf (((symbol-function 'active-minibuffer-window) (lambda () t))
                  ((symbol-function 'gnosis-review--resume)
                   (lambda (&rest _) (setq launched t))))
          (gnosis-agent--launch (car gnosis-agent--launches)))
        (should-not launched))
      (should (equal "unfinished" (plist-get (gnosis-agent-status session) :status)))
      (cl-letf (((symbol-function 'run-with-timer) (lambda (&rest _) (error "Timer fault"))))
        (should (equal "unfinished" (plist-get (gnosis-agent-resume session) :status))))
      (should-not gnosis-agent--launches)
      (should-not (gnosis-select '* 'practice-events)))))

(ert-deftest gnosis-agent-native-suspend-settles-required-continuation ()
  (dolist (case '(("wrong" nil "excluded")
                  ("a" (:successes-required 2) "excluded")
                  ("a" nil "target-reached")
                  ("wrong" (:max-attempts-per-thema 1) "attempt-limit")))
    (gnosis-test-agent
      (gnosis-test--add-basic-thema "A" "a" nil nil 101)
      (gnosis-scheduler-accept-review (gnosis-scheduler-event-id) 101 'success
                                     1780000000000000 (gnosis--today-int))
      (let* ((session (gnosis-test-agent-start '(101) (nth 1 case)))
             (choices (list ?s ?n))
             before)
        (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                   (lambda (&rest _) (car case)))
                  ((symbol-function 'gnosis-review--read-action)
                   (lambda (&rest _)
                     (when (equal choices '(?n))
                       ;; Suspension is intentional; acceptance must not reschedule.
                       (setq before (gnosis-test-agent-snapshot)))
                     (or (pop choices) (ert-fail "Unexpected extra presentation"))))
                  ((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
          (gnosis-agent--launch (car gnosis-agent--launches)))
        (should-not choices)
        (should (equal before (gnosis-test-agent-snapshot)))
        (let* ((result (gnosis-agent-results session))
               (summary (plist-get result :summary))
               (item (aref (plist-get result :items) 0))
               (excluded (if (equal (nth 2 case) "excluded") 1 0)))
          (should (equal "completed" (plist-get result :status)))
          (should (equal [] (plist-get result :remaining-ids)))
          (should (equal (nth 2 case) (plist-get item :reason)))
          (should (= excluded (plist-get (plist-get result :targets) :excluded)))
          (should (= 0 (plist-get (plist-get result :targets) :unfinished)))
          (should (= excluded (plist-get summary :excluded)))
          (should (= 1 (plist-get summary :attempts)))
          (should (= 0 (plist-get summary :unattempted)))
          (should (= 1 (length (plist-get item :events))))
          (should (equal (if (equal (car case) "a") "success" "failure")
                         (plist-get (aref (plist-get item :events) 0) :outcome)))
          (should (eq t (plist-get (aref (plist-get item :events) 0) :effective)))
          (gnosis-sqlite-close gnosis-db)
          (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
          (gnosis-update 'scheduler-state '(= suspended 0) '(= thema-id 101))
          (should (equal result (gnosis-agent-results session)))
          (gnosis-test-agent-start '(101))
          (should (equal result (gnosis-agent-results session))))))))

(ert-deftest gnosis-agent-exclusion-checkpoint-atomicity-and-undo ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (let ((session (gnosis-test-agent-start '(101))))
      (gnosis-update 'scheduler-state '(= suspended 1) '(= thema-id 101))
      (let ((before (gnosis-agent-results session))
            (checkpoint (gnosis-review--state-data (gnosis-review--read-session))))
        ;; Merely suspending does not rewrite history or settle a queued item.
        (should (= 0 (plist-get (plist-get before :targets) :excluded)))
        (cl-letf (((symbol-function 'gnosis-review--save-history)
                   (lambda (_) (error "History disk fault"))))
          (should-error (gnosis-test-agent-grade nil)))
        (should (equal before (gnosis-agent-results session)))
        (should (equal checkpoint (gnosis-review--state-data (gnosis-review--read-session))))
        (should-not (gnosis-select '* 'practice-events)))
      (gnosis-test-agent-grade nil)
      (should (= 1 (plist-get (plist-get (gnosis-agent-results session) :targets) :excluded)))
      (gnosis-review-undo)
      (let* ((result (gnosis-agent-results session))
             (item (aref (plist-get result :items) 0)))
        (should (equal [101] (plist-get result :remaining-ids)))
        (should (equal "unfinished" (plist-get item :reason)))
        (should (= 0 (plist-get item :attempts)))
        (should (= 1 (length (plist-get item :events))))
        (should (eq :false (plist-get (aref (plist-get item :events) 0) :effective)))))))

(ert-deftest gnosis-agent-ordinary-practice-suspend-summary ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (let ((choices (list ?s ?n)))
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) "wrong"))
                ((symbol-function 'gnosis-review--read-action) (lambda (&rest _) (pop choices)))
                ((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
        (gnosis-review-loop '(101) 'practice)))
    (let ((summary (gnosis-review-summary (gnosis-review--read-session))))
      (should (= 1 (plist-get summary :first-failure)))
      (should (= 1 (plist-get summary :excluded)))
      (should (= 0 (plist-get summary :unattempted)))
      (should (= 1 (plist-get summary :attempts))))))

(ert-deftest gnosis-agent-launch-owns-target-not-selected-summary ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (gnosis-test--add-basic-thema "B" "b" nil nil 102)
    (let ((a (gnosis-test-agent-start '(101))))
      (gnosis-test-agent-grade t)
      (gnosis-review--show-summary (gnosis-agent--session a))
      (let* ((old-summary (current-buffer))
             (b (gnosis-test-agent-start '(102)))
             (before (gnosis-test-agent-snapshot))
             (answers '("b")))
        (should (eq old-summary (current-buffer)))
        (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                   (lambda (&rest _) (pop answers)))
                  ((symbol-function 'gnosis-review--read-action) (lambda (&rest _) ?n)))
          (gnosis-agent--launch (car gnosis-agent--launches)))
        (should-not answers)
        (should (equal "completed" (plist-get (gnosis-agent-status b) :status)))
        (should (equal before (gnosis-test-agent-snapshot)))
        (with-current-buffer old-summary
          (should-error (call-interactively (local-key-binding (kbd "u")))
                        :type 'user-error))))))

(provide 'gnosis-test-agent)
;;; gnosis-test-agent.el ends here
