;;; gnosis-test-model-numeric.el --- Stable surface arithmetic -*- lexical-binding: t; -*-
(require 'ert)
(require 'gnosis-test-model-targets)

(defun gnosis-test-model-numeric-record (key value)
  (princ (format "%s=%S\n" key value)))

(ert-deftest gnosis-test-model-numeric-public-import-cyclic-and-controls ()
  (gnosis-test-with-db
    (let ((file (expand-file-name "triangle.obj" gnosis-dir)) outcomes)
      (dolist (case '(("thin-123" "0 0 0" "1 0 0" "1 0.000000001 0" "1 2 3")
                      ("thin-231" "0 0 0" "1 0 0" "1 0.000000001 0" "2 3 1")
                      ("thin-312" "0 0 0" "1 0 0" "1 0.000000001 0" "3 1 2")
                      ("ordinary" "0 0 0" "1 0 0" "1 1 0" "1 2 3")
                      ("tiny-area" "0 0 0" "1 0 0" "1 1e-200 0" "1 2 3")
                      ("tiny-scale" "0 0 0" "1e-200 0 0" "1e-200 1e-209 0" "1 2 3")
                      ("oblique" "0 0 0" "1 0 0" "1 1 1" "1 2 3")
                      ("oblique-collinear" "0 0 0" "5617 1732 9116" "28085 8660 45580" "1 2 3")
                      ("invalid-index" "0 0 0" "1 0 0" "1 1 0" "1 2 4")
                      ("translated-thin-123" "100 -20 7" "101 -20 7" "101 -19.999999999 7" "1 2 3")
                      ("translated-thin-231" "100 -20 7" "101 -20 7" "101 -19.999999999 7" "2 3 1")
                      ("translated-thin-312" "100 -20 7" "101 -20 7" "101 -19.999999999 7" "3 1 2")
                      ("collinear-123" "0 0 0" "1 0 0" "2 0 0" "1 2 3")
                      ("collinear-231" "0 0 0" "1 0 0" "2 0 0" "2 3 1")
                      ("collinear-312" "0 0 0" "1 0 0" "2 0 0" "3 1 2")
                      ("duplicate" "0 0 0" "1 0 0" "1 0 0" "1 2 3")
                      ("nan" "NaN 0 0" "1 0 0" "1 1 0" "1 2 3")
                      ("infinity" "Inf 0 0" "1 0 0" "1 1 0" "1 2 3")
                      ("overflow" "1e309 0 0" "1 0 0" "1 1 0" "1 2 3")
                      ("out-of-bounds" "1000001 0 0" "1 0 0" "1 1 0" "1 2 3")))
        (with-temp-file file
          (insert (format "v %s\nv %s\nv %s\nf %s\n" (nth 1 case) (nth 2 case) (nth 3 case) (nth 4 case))))
        (let ((result
               (condition-case err
                   (let* ((reference (gnosis-model-import-objects (list (cons file "Triangle")) "CC0" "Synthetic validator"))
                          (path (expand-file-name reference (gnosis-assets-root)))
                          (scene (gnosis-model--scene path))
                          (id (alist-get 'id (car (gnosis-model--targets scene))))
                          (resolved (gnosis-model-resolve (list reference "0" "0" "1") (list id))))
                     (list :accepted t :reference reference :counts (plist-get (nth 2 resolved) :counts)))
                 (error (list :accepted nil :error (error-message-string err))))))
          (push (cons (car case) result) outcomes)))
      (setq outcomes (nreverse outcomes))
      (gnosis-test-model-numeric-record 'public-imports outcomes)
      (dolist (entry outcomes)
        (should (eq (and (member (car entry) '("thin-123" "thin-231" "thin-312" "ordinary" "tiny-area" "tiny-scale" "oblique" "translated-thin-123" "translated-thin-231" "translated-thin-312")) t)
                    (plist-get (cdr entry) :accepted)))))))

(ert-deftest gnosis-test-model-numeric-barycentric-characterization ()
  (let ((triangles '(((0.0 0.0 0.0) (1.0 0.0 0.0) (1.0 1e-9 0.0))
                     ((1.0 0.0 0.0) (1.0 1e-9 0.0) (0.0 0.0 0.0))
                     ((1.0 1e-9 0.0) (0.0 0.0 0.0) (1.0 0.0 0.0)))) results)
    (dolist (triangle triangles)
      (push (condition-case err
                (gnosis-model--barycentric '(0.8 4e-10 0.0) triangle)
              (error (list :error (error-message-string err)))) results))
    (setq results (nreverse results))
    (gnosis-test-model-numeric-record 'barycentric results)
    (should (equal (length (car results)) 3))
    (should (< (abs (- (caar results) 0.2)) 1e-10)))
  (gnosis-test-model-numeric-record 'ordinary-off-plane
    (gnosis-model--barycentric '(0.8 0.4 0.2) '((0 0 0) (1 0 0) (1 1 1)))))

(ert-deftest gnosis-test-model-numeric-candidate-repeat-and-equivalence ()
  (gnosis-test-with-db
    (let* ((file (gnosis-test-model-targets--fixture))
           (scene (gnosis-model--scene file))
           (geometry (gnosis-model--validate-targets scene (file-name-directory file)))
           (tip (gnosis-model-target scene "tip"))
           (targets (cl-loop for (id bary) in '(("c" (0.1 0.5 0.4)) ("b" (0.2 0.4 0.4)) ("a" (0.3 0.3 0.4)))
                             collect (let ((target (copy-tree tip)))
                                       (setf (alist-get 'id target) id
                                             (alist-get 'barycentric target) bary
                                             (alist-get 'tolerance target) 10)
                                       target)))
           (get-point (symbol-function 'gnosis-model--point))
           (exponent (symbol-function 'expt)) results)
      (setf (alist-get 'targets scene) targets)
      (let ((points (mapcar (lambda (target) (cons (alist-get 'id target) (gnosis-model--point target (cdar geometry)))) targets))
            (original (copy-tree scene)))
        (dolist (verified '(nil t))
          (let ((coordinate-calls 0) (squares 0) winner)
            (cl-letf (((symbol-function 'gnosis-model--point)
                       (lambda (&rest args) (cl-incf coordinate-calls) (apply get-point args)))
                      ((symbol-function 'expt)
                       (lambda (x y) (when (= y 2) (cl-incf squares)) (funcall exponent x y))))
              (setq winner (gnosis-model--candidate scene (unless verified geometry) "c"
                                                    '(:mesh "mesh" :face 0 :point (8.1 4 0))
                                                    (and verified points))))
            (should (equal winner "b"))
            (should (= squares 12))
            (should (= coordinate-calls (if verified 0 3)))
            (should (equal original scene))
            (push (list :verified-points verified :coordinate-calls coordinate-calls :square-calls squares :winner winner) results)))
        (dolist (reversed '(nil t))
          (let ((ordered (copy-tree scene)))
            (when reversed (setf (alist-get 'targets ordered) (reverse (alist-get 'targets ordered))))
            (dolist (verified '(nil t))
              (should (equal "b" (gnosis-model--candidate ordered (unless verified geometry) "c"
                                                         '(:mesh "mesh" :face 0 :point (8.5 4 0)) (and verified points)))))))
        (gnosis-test-model-numeric-record 'candidate-counts (nreverse results))))))

(ert-deftest gnosis-test-model-numeric-scale-projection-and-degeneracy ()
  (dolist (case '((((0 0 0) (1 0 0) (1 1e-9 0)) (0.8 4e-10 0) (0.2 0.4 0.4))
                  (((0 0 0) (1e-200 0 0) (1e-200 1e-209 0)) (8e-201 4e-210 0) (0.2 0.4 0.4))
                  (((0 0 0) (1 0 0) (1 1e-200 0)) (0.8 4e-201 0) (0.2 0.4 0.4))
                  (((0 0 0) (1 0 0) (1 1 1)) (0.8 0.4 0.2) (0.2 0.5 0.3))
                  (((0 0 0) (1 0 0) (1 1 1)) (1.2 0.6 1) (0 0.3333333333333333 0.6666666666666667))
                  (((0 0 0) (1 0 0) (1 1 0)) (3 2 0) (0 0.5 0.5))))
    (dotimes (cycle 3)
      (let* ((triangle (append (nthcdr cycle (car case)) (seq-take (car case) cycle)))
             (expected (append (nthcdr cycle (nth 2 case)) (seq-take (nth 2 case) cycle))))
        (cl-mapc (lambda (a b) (should (< (abs (- a b)) 1e-10)))
                 (gnosis-model--barycentric (cadr case) triangle) expected))))
  (dolist (triangle '(((0 0 0) (5617 1732 9116) (28085 8660 45580))
                      ((0 0 0) (1 1 1) (2 2 2)) ((1 1 1) (1 1 1) (1 1 1))))
    (dotimes (cycle 3)
      (should-error (gnosis-model--barycentric '(0 0 0)
                     (append (nthcdr cycle triangle) (seq-take triangle cycle)))
                    :type 'user-error)))
  (should-error (gnosis-model--barycentric '(0 0 1)
                  '((0 0 0) (1e-320 0 0) (0 1e-320 0))) :type 'user-error))

(ert-deftest gnosis-test-model-numeric-candidate-policy-and-values ()
  (gnosis-test-with-db
    (let* ((file (gnosis-test-model-targets--fixture))
           (scene (gnosis-model--scene file))
           (geometry (gnosis-model--validate-targets scene (file-name-directory file)))
           (points (list (cons "tip" (gnosis-model--point (gnosis-model-target scene "tip") (cdar geometry)))))
           (before (copy-tree (list scene geometry points) t)))
      (dolist (verified '(nil t))
        (dolist (case '(("whole" (:mesh "mesh" :face 0) "whole")
                        ("whole" (:mesh "other" :face 0) nil)
                        ("patch" (:mesh "mesh" :face 1) "patch")
                        ("patch" (:mesh "mesh" :face 0) nil)
                        ("tip" (:mesh "mesh" :face 0 :point (9 4 0)) "tip")
                        ("tip" (:mesh "mesh" :face 0 :point (9.01 4 0)) nil)
                        ("tip" (:mesh "other" :face 0 :point (8 4 0)) nil)
                        ("tip" (:mesh "mesh" :face 0) nil)
                        ("tip" nil nil)))
          (should (equal (nth 2 case)
                         (gnosis-model--candidate scene (unless verified geometry)
                                                  (car case) (cadr case) (and verified points))))))
      (should (equal before (list scene geometry points))))))

(ert-deftest gnosis-test-model-numeric-thin-author-point-move-save-reopen ()
  (let ((fixture (symbol-function 'gnosis-test-model-targets--fixture)))
    (dolist (face '("1 2 3" "2 3 1" "3 1 2"))
      (dolist (type '("model" "model-name"))
        (cl-letf (((symbol-function 'gnosis-test-model-targets--fixture)
                   (lambda ()
                     (let ((file (funcall fixture)))
                       (with-temp-file (expand-file-name "surface.obj" (file-name-directory file))
                         (insert (format "v 0 0 0\nv 1 0 0\nv 1 1e-9 0\nv 0 1e-9 0\nf %s\nf 1 3 4\n" face)))
                       file))))
          (gnosis-test-model-targets--author-roundtrip
           (lambda ()
             (interactive)
             (setf (plist-get canvas-3d--selection :point) '(0.6 2e-10 0))
             (call-interactively #'gnosis-model-author-point)
             (setf (plist-get canvas-3d--selection :point) '(0.8 4e-10 0))
             (call-interactively #'gnosis-model-author-move)
             (let* ((context gnosis-model--author-context)
                    (target (gnosis-model-target (plist-get context :scene) (plist-get context :target)))
                    (point (gnosis-model--point target (cdar (plist-get context :geometry)))))
               (should (equal "landmark-1" (alist-get 'id target)))
               (should (= 0 (alist-get 'face target)))
               (should (= 2 (alist-get 'tolerance target)))
               (cl-mapc (lambda (a b) (should (< (abs (- a b)) 1e-15))) point '(0.8 4e-10 0))))
           type))))))

(defun gnosis-test-model-numeric-oblique-triangle ()
  "Return the finite binary64 cancellation regression triangle."
  (let ((e (ldexp 1.0 -27)))
    (list '(0.0 0.0 0.0) (list 1.0 (+ 1.0 e) 0.0)
          (list (+ 1.0 e) (+ 1.0 (* 2 e)) 0.0))))

(defun gnosis-test-model-numeric-obj (triangle face)
  "Return OBJ text with TRIANGLE vertices in the given FACE order."
  (concat (mapconcat (lambda (vertex)
                       (concat "v " (mapconcat (lambda (x) (format "%.17g" x)) vertex " ")))
                     triangle "\n")
          "\nf " face "\n"))

(ert-deftest gnosis-test-model-numeric-oblique-cyclic-import-resolve ()
  (gnosis-test-with-db
    (let ((triangle (gnosis-test-model-numeric-oblique-triangle))
          (file (expand-file-name "oblique.obj" gnosis-dir)))
      (cl-loop for face in '("1 2 3" "2 3 1" "3 1 2") for cycle from 0 do
               (with-temp-file file (insert (gnosis-test-model-numeric-obj triangle face)))
               (let* ((reference (gnosis-model-import-objects (list (cons file "Oblique")) "CC0" "Test"))
                      (scene (gnosis-model--scene (expand-file-name reference (gnosis-assets-root))))
                      (id (alist-get 'id (car (gnosis-model--targets scene))))
                      (resolved (gnosis-model-resolve (list reference "0" "0" "1") (list id)))
                      (geometry (gnosis-model--validate-targets scene (file-name-directory (car resolved)))))
                 (cl-mapc (lambda (actual expected)
                            (cl-mapc (lambda (a b) (should (= a b))) actual expected))
                          (aref (cdar geometry) 0)
                          (append (nthcdr cycle triangle) (seq-take triangle cycle))))))))

(ert-deftest gnosis-test-model-numeric-oblique-cyclic-author-save-reopen ()
  (let* ((fixture (symbol-function 'gnosis-test-model-targets--fixture))
         (triangle (gnosis-test-model-numeric-oblique-triangle))
         (e (ldexp 1.0 -27))
         ;; Both points and their weights are exactly representable.
         (point (list (+ 0.75 (* 0.5 e)) (+ 0.75 (* 1.25 e)) 0.0)))
    (cl-loop for face in '("1 2 3" "2 3 1" "3 1 2") for cycle from 0 do
             (dolist (type '("model" "model-name"))
               (cl-letf (((symbol-function 'gnosis-test-model-targets--fixture)
                          (lambda ()
                            (let ((file (funcall fixture)))
                              (with-temp-file (expand-file-name "surface.obj" (file-name-directory file))
                                (insert (gnosis-test-model-numeric-obj triangle face)
                                        ;; Keep the fixture's region face 1 valid.
                                        "f 1 2 3\n"))
                              file))))
                 ;; This fixture compares exact target weights in the published
                 ;; and reopened scenes, not only in the authoring context.
                 (gnosis-test-model-targets--author-roundtrip
                  (lambda ()
                    (interactive)
                    (setf (plist-get canvas-3d--selection :point) (nth 1 triangle))
                    (call-interactively #'gnosis-model-author-point)
                    (setf (plist-get canvas-3d--selection :point) point)
                    (call-interactively #'gnosis-model-author-move)
                    (let* ((context gnosis-model--author-context)
                           (target (gnosis-model-target (plist-get context :scene) (plist-get context :target)))
                           (weights '(0.25 0.25 0.5)))
                      (should (equal "landmark-1" (alist-get 'id target)))
                      (should (= 0 (alist-get 'face target)))
                      (should (= 2 (alist-get 'tolerance target)))
                      (should (equal (alist-get 'barycentric target)
                                     (append (nthcdr cycle weights) (seq-take weights cycle))))
                      (should (equal point (gnosis-model--point target (cdar (plist-get context :geometry)))))))
                  type))))))

(ert-deftest gnosis-test-model-numeric-oblique-cyclic-scale-and-projection ()
  "Keep compensated weights cyclic at tiny scale, translated and off-plane."
  (let* ((triangle (gnosis-test-model-numeric-oblique-triangle))
         (e (ldexp 1.0 -27))
         (point (list (+ 0.75 (* 0.5 e)) (+ 0.75 (* 1.25 e)) 0.0))
         (weights '(0.25 0.25 0.5)))
    (dolist (case '((0 (0 0 0) 0) (0 (4 -2 7) 0.25) (-600 (0 0 0) 0)))
      (let* ((transform (lambda (p)
                          (cl-mapcar (lambda (x shift) (+ (ldexp x (car case)) shift)) p (cadr case))))
             (vertices (mapcar transform triangle))
             (query (cl-mapcar #'+ (funcall transform point) (list 0 0 (nth 2 case)))))
        (dotimes (cycle 3)
          (should (equal (gnosis-model--barycentric query
                           (append (nthcdr cycle vertices) (seq-take vertices cycle)))
                         (append (nthcdr cycle weights) (seq-take weights cycle))))))))
  ;; A large finite scaled off-plane vector must not overflow the splitter.
  (let ((s (ldexp 1.0 -1010)))
    (should (equal '(1.0 0.0 0.0)
                   (gnosis-model--barycentric '(1.0 1.0 1.0)
                     (list '(0.0 0.0 0.0) (list s (- s) 0.0) (list s s (* -2 s))))))))

(provide 'gnosis-test-model-numeric)
;;; gnosis-test-model-numeric.el ends here
