;;; gnosis-test-practice-coaching.el --- Accepted coaching evidence -*- lexical-binding: t; -*-

(require 'gnosis-test-agent)
(require 'gnosis-review-test-support)

(ert-deftest gnosis-coaching-native-summary-excludes-deleted-evidence ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (gnosis-test--add-basic-thema "B" "b" nil nil 102)
    (let ((session (gnosis-test-agent-start '(101 102))))
      (gnosis-test-agent-grade t)
      (gnosis-delete-thema 101 t)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) "b"))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?n)))
        (gnosis-agent--launch (car gnosis-agent--launches)))
      (let ((summary (plist-get (gnosis-agent-results session) :summary)))
        (should (= 1 (plist-get summary :attempts)))
        (should (= 1 (plist-get summary :excluded))))
      (with-current-buffer "*Gnosis Study Summary*"
        (should (string-match-p "Unique attempted: 1   Accepted attempts: 1" (buffer-string)))
        (should (string-match-p "Skipped items (including retries): 1" (buffer-string)))))))

(ert-deftest gnosis-coaching-discover-reservation-without-launching ()
  (gnosis-test-agent
    (should-not (gnosis-agent-current-practice))
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (let* ((session (gnosis-test-agent-start '(101)))
           (before (gnosis-select '* 'study-session)))
      (should (equal session (plist-get (gnosis-agent-current-practice) :session-id)))
      (should (= 0 (plist-get (plist-get (gnosis-agent-current-practice) :summary) :attempts)))
      (should (equal before (gnosis-select '* 'study-session)))
      (mapc #'gnosis-agent--release (copy-sequence gnosis-agent--launches))
      (gnosis-sqlite-close gnosis-db)
      (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
      (should (equal session (plist-get (gnosis-agent-current-practice) :session-id)))
      (should (equal "unfinished" (plist-get (gnosis-agent-current-practice) :status)))
      (gnosis-agent-cancel session)
      (should-not (gnosis-agent-current-practice)))))

(ert-deftest gnosis-coaching-unlimited-native-retries-and-reopen ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (gnosis-test--add-basic-thema "B" "b" nil nil 102)
    (let* ((before (gnosis-test-agent-snapshot))
           (session (gnosis-test-agent-start
                     '(101 102) '(:successes-after-failure 1 :max-attempts-per-thema nil)))
           (answers (append (make-list 12 "wrong") '("a" "b"))))
      (dotimes (_ 12) (gnosis-test-agent-grade nil))
      (should (equal [101 102] (plist-get (gnosis-agent-status session) :remaining-ids)))
      (gnosis-sqlite-close gnosis-db)
      (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
      (should-not (plist-get (plist-get (gnosis-agent-status session) :policy) :max-attempts-per-thema))
      (gnosis-agent-resume session)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) (or (pop answers) (ert-fail "Unexpected retry"))))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?n)))
        (gnosis-agent--launch (car gnosis-agent--launches)))
      (should-not answers)
      (should (equal "completed" (plist-get (gnosis-agent-status session) :status)))
      (should (equal before (gnosis-test-agent-snapshot)))
      (should (string-match-p "\"max-attempts-per-thema\":null"
                              (json-serialize (gnosis-agent-results session)
                                              :false-object :false :null-object nil)))
      (with-current-buffer "*Gnosis Study Summary*"
        (should (string-match-p "cap: unlimited" (buffer-string)))))))

(defun gnosis-test-coaching-item (session)
  "Return the first item from exact SESSION's public result."
  (aref (plist-get (gnosis-agent-results session) :items) 0))

(ert-deftest gnosis-coaching-typed-response-context-and-corrections ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "Question λ" "correct" nil nil 101)
    (gnosis-update 'themata '(= hypothesis '("Shown hint")) '(= id 101))
    (gnosis-update 'themata '(= accepted-aliases '("alias")) '(= id 101))
    (gnosis-update 'extras '(= parathema "Explanation [[id:synthetic][Source]]") '(= id 101))
    (let* ((session (gnosis-test-agent-start
                     '(101) '(:successes-after-failure 1 :max-attempts-per-thema nil)))
           (answers '("Wrong λ\nsecond line" "alias")))
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) (pop answers)))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?n)))
        (gnosis-agent--launch (car gnosis-agent--launches)))
      (let* ((item (gnosis-test-coaching-item session))
             (events (plist-get item :events))
             (encounter (plist-get (aref events 0) :encounter)))
        (should (equal "Wrong λ\nsecond line" (plist-get (plist-get encounter :response) :text)))
        (should (equal "Question λ" (plist-get encounter :prompt)))
        (should (equal ["correct"] (plist-get encounter :expected-answers)))
        (should (equal ["alias"] (plist-get encounter :accepted-aliases)))
        (should (equal ["Shown hint"] (plist-get encounter :hints-available)))
        (should (equal ["Shown hint"] (plist-get encounter :hints-shown)))
        (should (equal "Explanation [[id:synthetic][Source]]" (plist-get encounter :parathema)))
        (should-not (plist-get encounter :coaching))
        (should (equal "failure" (plist-get item :first-outcome)))
        (should (= 2 (plist-get item :attempts-to-first-correct)))
        (should (= 1 (plist-get item :retries-to-first-correct)))
        (gnosis-review-undo)
        (let ((after (gnosis-test-coaching-item session)))
          (should (= 2 (plist-get after :total-attempts)))
          (should (= 1 (plist-get after :attempts)))
          (should-not (plist-get after :attempts-to-first-correct))
          (should (equal encounter (plist-get (aref (plist-get after :events) 0) :encounter)))))
      (mapc #'gnosis-agent--release (copy-sequence gnosis-agent--launches))
      (let ((before (gnosis-agent-results session)))
        (gnosis-sqlite-close gnosis-db)
        (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
        (gnosis-db-init)
        (should (equal before (gnosis-agent-results session)))))))

(ert-deftest gnosis-coaching-choice-and-cloze-structure ()
  (dolist (kind '("mcq" "mc-cloze" "cloze"))
    (gnosis-test-agent
      (gnosis-add-thema-fields kind "The alpha and beta" '("hint-a" "hint-b")
                               (if (equal kind "cloze") '("alpha" "beta") '("alpha"))
                               "Context" nil 0 nil nil 101)
      (let* ((session (gnosis-test-agent-start '(101) '(:max-attempts-per-thema 1)))
             (answers '("beta" "wrong")))
        (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                   (lambda (&rest _) (pop answers)))
                  ((symbol-function 'gnosis-completing-read) (lambda (&rest _) "hint-b"))
                  ((symbol-function 'read-char-choice) (lambda (&rest _) ?n)))
          (gnosis-agent--launch (car gnosis-agent--launches)))
        (let* ((item (gnosis-test-coaching-item session))
               (encounter (plist-get (aref (plist-get item :events) 0) :encounter))
               (response (plist-get encounter :response)))
          (if (equal kind "cloze")
              (let ((inputs (plist-get response :inputs)))
                (should (equal "blanks" (plist-get response :kind)))
                (should (= 2 (length inputs)))
                (should (equal [0 1] (plist-get (aref inputs 0) :remaining-blank-indices)))
                (should (= 1 (plist-get (aref inputs 0) :matched-blank-index)))
                (should (equal [0] (plist-get (aref inputs 1) :remaining-blank-indices)))
                (should-not (plist-get (aref inputs 1) :matched-blank-index)))
            (should (equal "choice" (plist-get response :kind)))
            (should (equal "hint-b" (plist-get response :selected)))
            (should (equal ["hint-a" "hint-b"] (plist-get response :choices)))
            (should (equal [] (plist-get encounter :hints-shown))))
          (should-not (plist-get item :attempts-to-first-correct))
          (should (json-parse-string (json-serialize (gnosis-agent-results session)
                                                   :false-object :false :null-object nil))))))))

(ert-deftest gnosis-coaching-duplicate-conflict-rollback-and-deletion ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "correct" nil nil 101)
    (gnosis-test--add-basic-thema "B" "other" nil nil 102)
    (pop-to-buffer (get-buffer-create gnosis-review-buffer-name))
    (let* ((session (gnosis-test-agent-start '(101 102)))
           (gnosis-review--state (gnosis-review--read-session))
           (answer (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                              (lambda (&rest _) "wrong")))
                     (gnosis-review-basic 101)))
           (result (gnosis-review--override-result (cdr answer) t)))
      ;; An override changes acceptance, never the answer or initial comparison.
      (should (equal "failure" (plist-get (plist-get result :encounter) :original-outcome)))
      (cl-letf (((symbol-function 'gnosis-review--save-history)
                 (lambda (_) (error "Checkpoint fault"))))
        (should-error (gnosis-review-result 101 t result)))
      (should-not (gnosis-select '* 'practice-events))
      (should-not (gnosis-select '* 'practice-encounters))
      (gnosis-review-result 101 t result)
      (gnosis-review-result 101 t result)
      (should (= 1 (length (gnosis-select '* 'practice-encounters))))
      (let* ((different (copy-tree result t))
             (encounter (plist-get different :encounter)))
        (setf (plist-get encounter :response) '(:kind "text" :text "different"))
        (should-error (gnosis-review-result 101 t different)))
      (gnosis-test-agent-grade t)
      (gnosis-delete-thema 101 t)
      (should-not (gnosis-select '* 'practice-encounters))
      (should (= 1 (length (gnosis-select '* 'practice-events))))
      (let ((item (aref (plist-get (gnosis-agent-results session) :items) 1)))
        (should (= 1 (plist-get item :attempts)))
        (should-not (plist-get (aref (plist-get item :events) 0) :encounter))))))

(ert-deftest gnosis-coaching-native-edit-retains-answered-facts ()
  (dolist (final '(?n ?q))
    (gnosis-test-agent
      (gnosis-test-content--add "basic")
      (let ((session (gnosis-test-agent-start '(222))))
        (with-temp-buffer
          (setq-local gnosis-review--state (gnosis-review--read-session))
          (let* ((answer (gnosis-test-content--answer "basic" nil "wrong"))
                 (original (copy-tree (plist-get (cdr answer) :encounter) t))
                 (accepted
                  (gnosis-test-content--edit-actions
                   answer '((("Keimenon" . "The new answer") ("Answer" . "new")
                             ("Parathema" . "New explanation"))) (list final))))
            (gnosis-review-result 222 (car accepted) (cdr accepted))
            (let ((encounter (plist-get
                              (aref (plist-get (gnosis-test-coaching-item session) :events) 0)
                              :encounter)))
              (should (equal original encounter))
              (should (equal "The old answer" (plist-get encounter :prompt)))
              (should (equal ["old"] (plist-get encounter :expected-answers)))
              (should (equal "wrong" (plist-get (plist-get encounter :response) :text)))
              (should (equal "Explanation" (plist-get encounter :parathema)))
              (should (equal "failure" (plist-get encounter :original-outcome)))
              (should (equal "The new answer" (gnosis-get 'keimenon 'themata '(= id 222)))))))))))

(ert-deftest gnosis-coaching-cloze-hints-record-only-visible-content ()
  (gnosis-test-agent
    (gnosis-add-thema-fields "cloze" "The alpha and beta" '("" "shown" "not displayed")
                             '("alpha" "beta") "Context" nil 0 nil nil 101)
    (let ((session (gnosis-test-agent-start '(101) '(:max-attempts-per-thema 1))))
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method) (lambda (&rest _) "wrong"))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?n)))
        (gnosis-agent--launch (car gnosis-agent--launches)))
      (let ((encounter (plist-get (aref (plist-get (gnosis-test-coaching-item session) :events) 0)
                                 :encounter)))
        (should (equal ["" "shown" "not displayed"] (plist-get encounter :hints-available)))
        (should (equal ["shown"] (plist-get encounter :hints-shown)))))))

(ert-deftest gnosis-coaching-discovery-follows-database-not-old-launch ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (let* ((session (gnosis-test-agent-start '(101)))
           (database (plist-get (gnosis-agent-current-practice) :database)))
      (should (equal (file-truename gnosis-test--db-file) (file-truename database)))
      (gnosis-test-with-db
        (should-not (gnosis-agent-current-practice))
        (should-error (gnosis-agent-results session)))
      (should (equal session (plist-get (gnosis-agent-current-practice) :session-id)))
      (let ((empty (gnosis-agent-start-practice :thema-ids '(999) :limit 1)))
        (should (equal "completed" (plist-get empty :status)))
        (should (equal session (plist-get (gnosis-agent-current-practice) :session-id)))))))

(ert-deftest gnosis-coaching-self-grade-is-not-a-typed-response ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "Checklist" "answer" nil nil 101)
    (let* ((gnosis-review-basic-input 'self-grade)
           (session (gnosis-test-agent-start '(101) '(:max-attempts-per-thema nil)))
           (keys '(?\s ?n ?q)))
      (cl-letf (((symbol-function 'read-char-choice)
                 (lambda (&rest _) (or (pop keys) (ert-fail "Unexpected input")))))
        (gnosis-agent--launch (car gnosis-agent--launches)))
      (should-not keys)
      (let* ((item (gnosis-test-coaching-item session))
             (encounter (plist-get (aref (plist-get item :events) 0) :encounter))
             (response (plist-get encounter :response))
             (decoded (json-parse-string (json-serialize response :false-object :false :null-object nil)
                                         :object-type 'plist :false-object :false)))
        (should (equal '(:kind "self-grade" :recalled :false) decoded))
        (should-not (plist-member response :text))
        (should (equal "unfinished" (plist-get (gnosis-agent-status session) :status)))
        (should-not (plist-get item :attempts-to-first-correct)))
      (gnosis-agent-resume session)
      (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) (signal 'quit nil))))
        (gnosis-agent--launch (car gnosis-agent--launches)))
      (should (= 1 (length (gnosis-select '* 'practice-encounters)))))))

(ert-deftest gnosis-coaching-unknown-evidence-and-incomplete-policy-fail-closed ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "a" nil nil 101)
    (let ((session (gnosis-test-agent-start '(101))))
      (gnosis-test-agent-grade nil)
      (should-not (plist-get (aref (plist-get (gnosis-test-coaching-item session) :events) 0)
                            :encounter))
      (let ((event (gnosis-get 'event-id 'practice-events)))
        (gnosis-sqlite-execute gnosis-db "INSERT INTO practice_encounters VALUES (?, ?)"
                               (list event '(:version 99))))
      (should-error (gnosis-agent-results session))
      (let* ((data (gnosis-get 'data 'study-history `(= session-id ,session)))
             (policy (plist-get data :policy)))
        (setf (plist-get data :policy) (seq-take policy 6))
        (gnosis-update 'study-history `(= data ',data) `(= session-id ,session))
        (should-error (gnosis-agent-status session))))))

(ert-deftest gnosis-coaching-records-observed-copy-practice ()
  (gnosis-test-agent
    (gnosis-test--add-basic-thema "A" "correct" nil nil 101)
    (let* ((session (gnosis-test-agent-start '(101) '(:max-attempts-per-thema 1)))
           (gnosis-monkeytype-enable t)
           (gnosis-monkeytype-themata '("basic"))
           shown)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method) (lambda (&rest _) "wrong"))
                ((symbol-function 'gnosis-monkeytype) (lambda (text) (setq shown text)))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?n)))
        (gnosis-agent--launch (car gnosis-agent--launches)))
      (should (equal "correct" shown))
      (let ((encounter (plist-get (aref (plist-get (gnosis-test-coaching-item session) :events) 0)
                                 :encounter)))
        (should (equal [(:kind "copy-practice" :text "correct")] (plist-get encounter :coaching)))))))

(provide 'gnosis-test-practice-coaching)
;;; gnosis-test-practice-coaching.el ends here
