;;; gnosis-test-study.el --- Study workflow regressions -*- lexical-binding: t; -*-

(require 'ert)
(require 'gnosis-review)
(require 'gnosis-study)
(require 'gnosis-dashboard)
(require 'gnosis-export-import)
(require 'gnosis-test-helpers)
(require 'gnosis-test-schema-v8)

(defmacro gnosis-test-study (&rest body)
  "Run BODY with real writers and disposable buffers and database."
  (declare (indent 0) (debug t))
  `(gnosis-test-with-db
     (let ((buffers (buffer-list))
           (gnosis-review-buffer-name "*Gnosis Test Recall*")
           (gnosis-monkeytype-enable nil)
           (gnosis-center-content nil)
           (register-alist nil))
       (save-window-excursion
         (unwind-protect (progn ,@body)
           (dolist (buf (seq-difference (buffer-list) buffers))
             (when (buffer-live-p buf)
               (with-current-buffer buf (set-buffer-modified-p nil))
               (kill-buffer buf))))))))

(defun gnosis-test-study-snapshot ()
  "Snapshot every scheduling authority and activity row."
  (mapcar (lambda (table) (gnosis-sqlite-select gnosis-db
                           (format "SELECT * FROM %s ORDER BY 1" table)))
          '(scheduler_config scheduler_active scheduler_baseline scheduler_state
            review_events review_voids review_activity_baseline)))

(defun gnosis-test-study-node (id &optional title)
  "Insert node ID with TITLE into the disposable index."
  (gnosis--insert-into 'nodes `([,id "fixture.org" ,(or title "Same title") "1" nil nil nil])))

(defun gnosis-test-study-state (ids mode)
  "Create a persisted session for IDS in MODE, returning its buffer."
  (let ((buf (gnosis-review--setup-buffer ids mode)))
    (with-current-buffer buf
      (setf (gnosis-review-state-persistent-p gnosis-review--state) t)
      (gnosis-review--save-session gnosis-review--state))
    buf))

(ert-deftest gnosis-study-selection-identity-cycle-and-composition ()
  (gnosis-test-study
    (gnosis-test-study-node "one")
    (gnosis-test-study-node "two")
    (gnosis--insert-into 'node-links '(["one" "two"] ["two" "one"]))
    (let* ((a (gnosis-test--add-basic-thema "due" "a"))
           (b (gnosis-test--add-basic-thema "future" "b"))
           (c (gnosis-test--add-basic-thema "suspended" "c" nil nil nil 1))
           (gnosis-new-themata-limit 0))
      (gnosis-update 'scheduler-state `(= due-day ,(gnosis--date-to-int (gnosis-date 3))) `(= thema-id ,b))
      (gnosis--insert-into 'thema-links `([,a "one"] [,a "two"] [,b "two"] [,c "one"]))
      (should (= 2 (length (gnosis-study-topic-candidates))))
      (should (equal '("one" "two") (mapcar #'cdr (gnosis-study-topic-candidates))))
      (should (equal (list a) (gnosis-study-topic-ids '("one"))))
      (should (equal (sort (list a b) #'<) (sort (gnosis-study-topic-ids '("one") nil 8 8) #'<)))
      (should (equal (list a) (gnosis-study-topic-ids '("one" "two") t)))
      (should (equal '(:total 2 :eligible 2 :suspended 0 :new 2 :due 1 :not-due 1)
                     (gnosis-study-composition (list a b a))))
      (cl-letf (((symbol-function 'completing-read-multiple)
                 (lambda (_ candidates &rest _) (mapcar #'car candidates))))
        (should (equal '("one" "two") (gnosis-study-read-topics))))
      (should-error (gnosis-study-topic-ids '("one") nil -1)))))

(ert-deftest gnosis-study-topic-labels-hide-ids-and-preserve-identity ()
  (gnosis-test-study
    (gnosis-test-study-node "unique-id" "Καρδιολογία")
    (gnosis-test-study-node "first-id" "Same title")
    (gnosis-test-study-node "second-id" "Same title")
    (gnosis-test-study-node "literal-id" "Same title — fixture.org")
    (let* ((candidates (gnosis-study-topic-candidates))
           (labels (mapcar #'car candidates)))
      (should (equal "unique-id" (cdr (assoc "Καρδιολογία" candidates))))
      (should (equal "literal-id" (cdr (assoc "Same title — fixture.org" candidates))))
      (should (= 4 (length (delete-dups (copy-sequence labels)))))
      (dolist (label labels)
        (should-not (string-match-p "id:" label)))
      (should (equal (car (rassoc "first-id" candidates))
                     (caar (gnosis-study-topic-candidates '("first-id"))))))
    (cl-letf (((symbol-function 'completing-read-multiple)
               (lambda (_ candidates &rest _)
                 (list (car (rassoc "second-id" candidates))
                       (car (rassoc "unique-id" candidates))))))
      (should (equal '("second-id" "unique-id") (gnosis-study-read-topics))))))

(ert-deftest gnosis-study-preview-cancel-and-empty-write-nothing ()
  (gnosis-test-study
    (gnosis-test-study-node "one")
    (let ((id (gnosis-test--add-basic-thema "Q" "A")) prompt)
      (gnosis--insert-into 'thema-links `([,id "one"]))
      (cl-letf (((symbol-function 'y-or-n-p) (lambda (s) (setq prompt s) nil)))
        (gnosis-practice-topic '("one")))
      (should (string-match-p (regexp-quote "1 thema (1 new, 0 not due)") prompt))
      (should (string-prefix-p "Practise without rescheduling: Same title" prompt))
      (should-not (string-match-p (rx (or "id:" "no cap" "Link depth")) prompt))
      (cl-letf (((symbol-function 'y-or-n-p) (lambda (s) (setq prompt s) nil)))
        (gnosis-practice-topic '("one") 1 2))
      (should (string-match-p "Link depth: 1 forward, 2 backward" prompt))
      (should-not (gnosis-select '* 'practice-events))
      (should-not (gnosis-select '* 'study-session))
      (gnosis-practice-topic '("missing"))
      (should-not (gnosis-select '* 'study-session)))))

(ert-deftest gnosis-study-real-practice-finite-tail-and-no-rescheduling ()
  (gnosis-test-study
    (let* ((a (gnosis-test--add-basic-thema "Q1" "A1"))
           (b (gnosis-test--add-basic-thema "Q2" "A2"))
           (before (gnosis-test-study-snapshot))
           (answers '("wrong" "A2" "wrong"))
           (calls 0) state)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) (pop answers)))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?n)))
        (setq state (gnosis-review-loop (lambda () (cl-incf calls) (list a b a)) 'practice)))
      (should (= 1 calls))
      (should-not answers)
      (should (equal before (gnosis-test-study-snapshot)))
      (should (= 3 (length (gnosis-select '* 'practice-events))))
      (should (equal (list a b a) (gnosis-select 'thema-id 'practice-events nil t)))
      (should (equal '(:selected 2 :unique 2 :attempts 3 :first-success 1 :first-failure 1
                       :retry-success 0 :retry-failure 1 :needs-work 1 :excluded 0 :unattempted 0)
                     (gnosis-review-summary state)))
      (should-not (gnosis-review-state-remaining (gnosis-review--read-session))))))

(ert-deftest gnosis-study-self-grade-reveal-both-modes-and-override ()
  (gnosis-test-study
    (dolist (mode '(practice due))
      (dolist (grade '(?y ?n))
        (let* ((id (gnosis-test--add-basic-thema "Explain mechanism" "Secret checklist" nil "Secret explanation"))
               (gnosis-review-basic-input 'self-grade)
               (before (gnosis-test-study-snapshot))
               (source (generate-new-buffer "*secret source*"))
               (keys (list ?\s grade ?o ?q))
               (checks 0))
          (with-current-buffer source (insert "Secret checklist"))
          (switch-to-buffer source)
          (delete-other-windows)
          (split-window-right)
          (cl-letf (((symbol-function 'read-char-choice)
                     (lambda (prompt &rest _)
                       (when (string-prefix-p "Recall first" prompt)
                         (cl-incf checks)
                         (should-not (get-buffer-window source))
                         (should-not (string-match-p "Secret" (buffer-string))))
                       (when (string-prefix-p "Recalled" prompt)
                         (should (string-match-p "Secret checklist" (buffer-string)))
                         (should (string-match-p "Secret explanation" (buffer-string))))
                       (pop keys))))
            (gnosis-review-loop (list id) mode))
          (should (= checks 1))
          (should (= 1 (gnosis-review-state-reviewed (gnosis-review--read-session))))
          (if (eq mode 'practice)
              (progn (should (equal before (gnosis-test-study-snapshot)))
                     (should (= (if (= grade ?y) 1 3)
                                (gnosis-get 'rating 'practice-events `(= thema-id ,id)))))
            (should (= (if (= grade ?y) 1 3)
                       (gnosis-get 'rating 'review-events `(= thema-id ,id)))))
          ;; Quit after a failure retains a retry; discard only the batch.
          (gnosis--delete 'study-session))))))

(ert-deftest gnosis-study-cancel-before-reveal-and-after-reveal ()
  (gnosis-test-study
    (dolist (reveal '(nil t))
      (let* ((id (gnosis-test--add-basic-thema "Q" "Answer"))
             (gnosis-review-basic-input 'self-grade)
             (before (gnosis-test-study-snapshot))
             (calls 0))
        (cl-letf (((symbol-function 'read-char-choice)
                   (lambda (&rest _) (cl-incf calls)
                     (if (and reveal (= calls 1)) ?\s (signal 'quit nil)))))
          (should (eq 'cancelled (condition-case nil (gnosis-review-loop (list id) 'practice)
                                   (quit 'cancelled)))))
        (should (equal before (gnosis-test-study-snapshot)))
        (should-not (gnosis-select '* 'practice-events))
        (should (equal (list id) (gnosis-review-state-remaining (gnosis-review--read-session))))
        (gnosis--delete 'study-session)))))

(ert-deftest gnosis-study-mid-session-removal-and-new-authoring ()
  (gnosis-test-study
    (let* ((a (gnosis-test--add-basic-thema "A" "a"))
           (b (gnosis-test--add-basic-thema "B" "b"))
           (c (gnosis-test--add-basic-thema "C" "c")) state)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) "a"))
                ((symbol-function 'read-char-choice)
                 (lambda (&rest _)
                   (gnosis--delete 'themata `(= id ,b))
                   (gnosis-toggle-suspend-themata (list c) 1 t)
                   (gnosis-test--add-basic-thema "New mid-batch" "d")
                   ?n)))
        (setq state (gnosis-review-loop (list a b c) 'practice)))
      (should (= 1 (plist-get (gnosis-review-summary state) :unique)))
      (should (= 2 (plist-get (gnosis-review-summary state) :excluded)))
      (should (= 2 (plist-get (gnosis-review-summary state) :unattempted)))
      (should (= 1 (length (gnosis-select '* 'practice-events)))))))

(ert-deftest gnosis-study-grade-checkpoint-atomic-failure-retry-and-reopen ()
  (gnosis-test-study
    (dolist (mode '(due practice))
      (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
             (buf (gnosis-test-study-state (list id) mode))
             (before (gnosis-test-study-snapshot)))
        (with-current-buffer buf
          (let ((pending (gnosis-review-algorithm id t))
                (saved (gnosis-get 'data 'study-session '(= id 1))))
            (cl-letf (((symbol-function 'gnosis-review--save-session)
                       (lambda (_) (error "Injected checkpoint failure"))))
              (should-error (gnosis-review-result id t pending)))
            (should (equal saved (gnosis-get 'data 'study-session '(= id 1))))
            (should (equal before (gnosis-test-study-snapshot)))
            (should-not (gnosis-select '* 'practice-events))
            (let ((real (symbol-function 'gnosis-review--write-result)) (calls 0))
              (cl-letf (((symbol-function 'gnosis-review--write-result)
                         (lambda (&rest args)
                           (cl-incf calls)
                           (if (= calls 1) (error "Transient write failure") (apply real args))))
                        ((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
                (gnosis-review--accept id t pending))
              (should (= calls 2)))
            (gnosis-review-result id t pending)
            (should (= 1 (gnosis-review-state-reviewed gnosis-review--state)))
            (gnosis-sqlite-close gnosis-db)
            (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
            (gnosis-db-init)
            (should-not (gnosis-review-state-remaining (gnosis-review--read-session)))
            (should (= 1 (gnosis-review-state-reviewed (gnosis-review--read-session))))))
      (gnosis--delete 'study-session)))))

(ert-deftest gnosis-study-undo-preserves-evidence-and-reanswers ()
  (gnosis-test-study
    (dolist (mode '(practice due))
      (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
             (buf (gnosis-test-study-state (list id) mode))
             (before (gnosis-test-study-snapshot)))
        (with-current-buffer buf
          (let* ((pending (gnosis-review-algorithm id nil)) event correction)
            (gnosis-review-result id nil pending)
            (let ((slot (gnosis-review-state-undo gnosis-review--state)))
              (setq event (plist-get slot :event-id) correction (plist-get slot :correction-id)))
            (gnosis-toggle-suspend-themata (list id) 1 t)
            (setq gnosis-review--state (gnosis-review-undo event correction))
            (gnosis-review-undo event correction)
            (should (gnosis-suspended-p id))
            (should (= 0 (gnosis-review-state-reviewed gnosis-review--state)))
            (should-error (gnosis-review-result id nil pending))
            (should-not (equal event (gnosis-review-state-event-id gnosis-review--state)))
            (gnosis-toggle-suspend-themata (list id) 0 t)
            (let ((next (gnosis-review-algorithm id t)))
              (gnosis-review-result id t next))
            (should (= 1 (gnosis-review-state-reviewed gnosis-review--state)))
            (if (eq mode 'practice)
                (should (equal before (gnosis-test-study-snapshot)))
              (should (= 1 (gnosis-get 'reps 'scheduler-state `(= thema-id ,id))))
              (should (= 2 (length (gnosis-select '* 'review-events `(= thema-id ,id)))))
              (should (= 1 (plist-get (gnosis-scheduler-replay-thema id 0) :reps))))))
      (gnosis--delete 'study-session)))))

(ert-deftest gnosis-study-retention-versioning-preview-race-and-replay ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
           (gnosis-review--state nil)
           (pending (gnosis-review-algorithm id t))
           (before (gnosis-test-study-snapshot)))
      (dolist (invalid '(0 1 -1 2 "0.9" 0.0e+NaN 1.0e+INF))
        (should-error (gnosis-scheduler-set-retention invalid)))
      (should (equal before (gnosis-test-study-snapshot)))
      (let ((new (gnosis-scheduler-set-retention 0.95)))
        (should (= new (gnosis-scheduler-set-retention 0.95)))
        (should-error (gnosis-review-result id t pending))
        (should (= 0 (gnosis-get 'reps 'scheduler-state `(= thema-id ,id))))
        (let ((pending (gnosis-review-algorithm id t))) (gnosis-review-result id t pending))
        (should (= new (gnosis-get 'config-id 'review-events `(= thema-id ,id))))
        (should (= new (gnosis-get 'config-id 'scheduler-state `(= thema-id ,id))))
        (gnosis-scheduler-set-retention 0.8)
        (let ((pending (gnosis-review-algorithm id t))) (gnosis-review-result id t pending))
        (should (= 2 (plist-get (gnosis-scheduler-replay-thema id 0) :reps)))
        (let ((new-id (gnosis-test--add-basic-thema "New" "Answer")))
          (should (= (gnosis-scheduler-active-config)
                     (gnosis-get 'config-id 'scheduler-state `(= thema-id ,new-id)))))
        (gnosis-sqlite-close gnosis-db)
        (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
        (should (= 0.8 (gnosis-scheduler--config-retention gnosis-db (gnosis-scheduler-active-config))))))))

(ert-deftest gnosis-study-backup-keeps-evidence-content-export-does-not ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A" '("needs_work")))
           (buf (gnosis-test-study-state (list id) 'practice))
           (backup (expand-file-name "full.db" gnosis-dir))
           (content (expand-file-name "content.gnosis" gnosis-dir)))
      (with-current-buffer buf (gnosis-review-result id t (gnosis-review-algorithm id t)))
      (gnosis-backup-db backup)
      (should-error (gnosis-backup-db backup))
      (let ((copy (gnosis-sqlite-open backup)))
        (unwind-protect
            (progn
              (should (equal (gnosis-select '* 'practice-events)
                             (gnosis-sqlite-select copy "SELECT * FROM practice_events")))
              (should (equal (gnosis-select '* 'study-session)
                             (gnosis-sqlite-select copy "SELECT * FROM study_session"))))
          (gnosis-sqlite-close copy)))
      (gnosis-export-db content nil nil t)
      (let ((copy (gnosis-sqlite-open content)))
        (unwind-protect
            (progn (should-not (sqlite-select copy "SELECT name FROM sqlite_master WHERE name = 'practice_events'"))
                   (should (equal '(("needs_work")) (gnosis-sqlite-select copy "SELECT tag FROM thema_tag"))))
          (gnosis-sqlite-close copy))))))

(ert-deftest gnosis-study-repair-tag-real-editor-and-content-import ()
  (gnosis-test-study
    (let* ((gnosis-save-hook nil)
           (gnosis-review-editing-p nil)
           (id (gnosis-test--add-basic-thema "Original wording" "Answer"))
           (other (gnosis-test--add-basic-thema "Unrelated" "Other"))
           (before (gnosis-test-study-snapshot))
           (file (expand-file-name "flag.gnosis" gnosis-dir)))
      (gnosis-study-flag id)
      (gnosis-edit-thema id)
      (delete-region (line-beginning-position) (line-end-position))
      (insert "Clearer wording")
      (should (member "needs_work" (nth 6 (car (gnosis-export-parse-themata)))))
      (gnosis-save)
      (should (equal "Clearer wording" (gnosis-get 'keimenon 'themata `(= id ,id))))
      (should (member "needs_work" (gnosis-get-tags-for-ids (list id))))
      (should (equal "Unrelated" (gnosis-get 'keimenon 'themata `(= id ,other))))
      (should (equal before (gnosis-test-study-snapshot)))
      (gnosis-export-db file '("needs_work") nil t)
      (gnosis-study-flag id t)
      (gnosis-import--apply-changes file nil (list id)
                                    (gnosis-import--file-sha256 file))
      (should (member "needs_work" (gnosis-get-tags-for-ids (list id))))
      (gnosis-study-repair)
      (should (equal (list id) (mapcar #'car tabulated-list-entries)))
      (should (eq (keymap-lookup (current-local-map) "RET") #'gnosis-study-edit)))))

(ert-deftest gnosis-study-repair-binding-save-cancel-and-draft ()
  (dolist (source-kind '(standalone unindexed linked))
    (gnosis-test-study
      (let* ((gnosis-save-hook nil)
             (gnosis-review-editing-p nil)
             (gnosis-nodes-dir gnosis-dir)
             (org-id-track-globally nil)
             (context (if (eq source-kind 'standalone) ""
                        "[[id:source][Source]]"))
             (id (gnosis-test--add-basic-thema "Original wording" "Answer"
                                               '("needs_work") context))
             (file (expand-file-name "source.org" gnosis-dir))
             (source-text "#+title: Source\n* Source\n:PROPERTIES:\n:ID: source\n:END:\nSource passage\n"))
        (unless (eq source-kind 'standalone)
          (gnosis--insert-into 'thema-links `([,id "source"])))
        (when (eq source-kind 'linked)
          (with-temp-file file (insert source-text))
          (gnosis-nodes-update-file file))
        ;; Nonempty retained evidence makes deletion as well as writes visible.
        (gnosis-scheduler-accept-review (gnosis-scheduler-event-id) id
                                       'failure 1 20260901)
        (with-current-buffer (gnosis-test-study-state (list id) 'practice)
          (gnosis-review-result id nil (gnosis-review-algorithm id nil)))
        (let ((before (gnosis-test-study-snapshot))
              (practice (gnosis-select '* 'practice-events))
              (voids (gnosis-select '* 'practice-voids))
              (session (gnosis-select '* 'study-session)))
          (gnosis-study-repair)
          (goto-char (point-min))
          (should (equal id (tabulated-list-get-id)))
          (let ((repair (current-buffer)))
            (unless (eq source-kind 'linked)
              (should (equal '(user-error "No indexed source for this thema")
                             (should-error
                              (call-interactively (key-binding (kbd "v")))
                              :type 'user-error))))
            (call-interactively (key-binding (kbd "RET")))
            (should (derived-mode-p 'gnosis-edit-mode))
            (should (equal "*Gnosis Edit*" (buffer-name)))
            (when (eq source-kind 'linked)
              (should (get-buffer-window (get-file-buffer file)))
              (should (equal source-text
                             (with-current-buffer (get-file-buffer file)
                               (buffer-string)))))
            (delete-region (line-beginning-position) (line-end-position))
            (insert "Clearer wording")
            (let ((editor (current-buffer))
                  (draft (buffer-string))
                  (register (get-register :gnosis-edit)))
              (switch-to-buffer repair)
              (should-error (call-interactively (key-binding (kbd "RET")))
                            :type 'user-error)
              (should (eq (current-buffer) repair))
              (should (equal draft (with-current-buffer editor (buffer-string))))
              (should (eq register (get-register :gnosis-edit)))
              (switch-to-buffer editor))
            (call-interactively (key-binding (kbd "C-c C-c")))
            (should (equal "Clearer wording"
                           (gnosis-get 'keimenon 'themata `(= id ,id))))
            (should (equal context (gnosis-get 'parathema 'extras `(= id ,id))))
            (should (member "needs_work" (gnosis-get-tags-for-ids (list id))))
            (should (equal before (gnosis-test-study-snapshot)))
            (should (equal practice (gnosis-select '* 'practice-events)))
            (should (equal voids (gnosis-select '* 'practice-voids)))
            (should (equal session (gnosis-select '* 'study-session)))
            (switch-to-buffer repair)
            (call-interactively (key-binding (kbd "RET")))
            (should (derived-mode-p 'gnosis-edit-mode))
            (insert "Cancelled change ")
            (call-interactively (key-binding (kbd "C-c C-k")))
            (should-not (get-buffer "*Gnosis Edit*"))
            (if (eq source-kind 'linked)
                (progn
                  (should (equal file buffer-file-name))
                  (should (equal "source" (org-entry-get nil "ID")))
                  (should (equal source-text (buffer-string)))
                  (should-not (buffer-modified-p)))
              (should (eq repair (current-buffer))))
            (should (equal "Clearer wording"
                           (gnosis-get 'keimenon 'themata `(= id ,id))))
            (should (equal context (gnosis-get 'parathema 'extras `(= id ,id))))
            (should (equal before (gnosis-test-study-snapshot)))
            (should (equal practice (gnosis-select '* 'practice-events)))
            (should (equal voids (gnosis-select '* 'practice-voids)))
            (should (equal session (gnosis-select '* 'study-session)))))))))

(ert-deftest gnosis-study-delayed-evidence-excludes-practice-and-immediate ()
  (gnosis-test-study
    (let ((id (gnosis-test--add-basic-thema "Q" "A")))
      (cl-loop for day in '(20260901 20260903 20260903 20260905)
               for time from 1
               do (gnosis-scheduler-accept-review (gnosis-scheduler-event-id) id 'failure time day))
      (with-current-buffer (gnosis-test-study-state (list id) 'practice)
        (gnosis-review-result id nil (gnosis-review-algorithm id nil)))
      (should (equal (list (list id 2 2)) (gnosis-study-delayed-evidence)))
      (gnosis-study-repair)
      (should (equal (list id) (mapcar #'car tabulated-list-entries)))
      (should (equal "2 / 2" (aref (cadar tabulated-list-entries) 3))))))

(ert-deftest gnosis-study-source-id-and-editor-cancel ()
  (gnosis-test-study
    (gnosis-test-study-node "one")
    (gnosis-test-study-node "two")
    (let* ((id (gnosis-test--add-basic-thema "Q" "A" nil "[[id:two][Same title]]"))
           (source (generate-new-buffer "*Disposable source*"))
           (before (gnosis-test-study-snapshot)) visited)
      (gnosis--insert-into 'thema-links `([,id "two"]))
      (with-current-buffer source
        (org-mode)
        (insert "* Same title\n:PROPERTIES:\n:ID: two\n:END:\nSource content"))
      (gnosis-study-topic "two")
      (goto-char (point-min))
      (cl-letf (((symbol-function 'gnosis-nodes-goto-id)
                 (lambda (node) (setq visited node) (switch-to-buffer source))))
        (gnosis-study-edit)
        (should (equal "two" visited))
        (should (get-buffer-window source))
        (set-buffer-modified-p nil)
        (gnosis-edit-quit))
      (should (eq (current-buffer) source))
      (should (equal before (gnosis-test-study-snapshot)))
      (should-not (gnosis-select '* 'practice-events)))))

(ert-deftest gnosis-study-undo-stale-and-checkpoint-failure ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
           (buf (gnosis-test-study-state (list id) 'due)))
      (with-current-buffer buf
        (gnosis-review-result id t (gnosis-review-algorithm id t))
        (let* ((slot (gnosis-review-state-undo gnosis-review--state))
               (before (gnosis-test-study-snapshot))
               (data (gnosis-get 'data 'study-session '(= id 1))))
          (cl-letf (((symbol-function 'gnosis-review--save-session) (lambda (_) (error "Undo checkpoint failed"))))
            (should-error (gnosis-review-undo)))
          (should (equal before (gnosis-test-study-snapshot)))
          (should (equal data (gnosis-get 'data 'study-session '(= id 1))))
          (gnosis-scheduler-accept-review (gnosis-scheduler-event-id) id 'success
                                          (car (time-convert nil 1000000)) (gnosis--today-int))
          (should-error (gnosis-review-undo))
          (should-not (gnosis-select '* 'review-voids))
          (should-error (gnosis-review-undo (gnosis-scheduler-event-id) (plist-get slot :correction-id))))))))

(ert-deftest gnosis-study-resume-freezes-membership-and-input-style ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
           (gnosis-review-basic-input 'self-grade)
           (buf (gnosis-test-study-state (list id) 'practice))
           (state (with-current-buffer buf gnosis-review--state)))
      (should-error (gnosis-review-loop (lambda () (user-error "Selection cancelled")) 'practice))
      (gnosis-test--add-basic-thema "New since pause" "B")
      (gnosis-sqlite-close gnosis-db)
      (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
      (let ((gnosis-review-basic-input 'typed) (keys '(?\s ?y ?n)))
        (cl-letf (((symbol-function 'read-char-choice) (lambda (&rest _) (pop keys)))
                  ((symbol-function 'gnosis--read-string-with-input-method)
                   (lambda (&rest _) (ert-fail "Resume lost input policy"))))
          (gnosis-review-resume))
        (should-not keys))
      (should (equal (gnosis-review-state-session-id state)
                     (gnosis-review-state-session-id (gnosis-review--read-session))))
      (should (equal (list id) (gnosis-select 'thema-id 'practice-events nil t)))
      (should-not (gnosis-review-state-remaining (gnosis-review--read-session))))))

(ert-deftest gnosis-study-retention-rollback-and-immutable-configs ()
  (gnosis-test-study
    (let ((before (gnosis-test-study-snapshot))
          (real (symbol-function 'gnosis-sqlite-execute)))
      (cl-letf (((symbol-function 'gnosis-sqlite-execute)
                 (lambda (db sql &optional values)
                   (if (string-prefix-p "UPDATE scheduler_active" sql)
                       (error "Active pointer failed")
                     (funcall real db sql values)))))
        (should-error (gnosis-scheduler-set-retention 0.95)))
      (should (equal before (gnosis-test-study-snapshot)))
      (gnosis-scheduler-set-retention 0.95)
      (should (equal (car (car before)) (car (gnosis-select '* 'scheduler-config)))))))

(ert-deftest gnosis-study-post-commit-projection-failure-retry ()
  (gnosis-test-study
    (dolist (mode '(due practice))
      (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
             (buf (gnosis-test-study-state (list id) mode)))
        (with-current-buffer buf
          (let ((pending (gnosis-review-algorithm id nil))
                (read-session (symbol-function 'gnosis-review--read-session))
                (calls 0))
            (cl-letf (((symbol-function 'gnosis-review--read-session)
                       (lambda ()
                         (if (= (cl-incf calls) 2)
                             (error "Reply lost after commit")
                           (funcall read-session)))))
              (should-error (gnosis-review-result id nil pending)))
            (should (= 0 (gnosis-review-state-reviewed gnosis-review--state)))
            (let ((saved (gnosis-get 'data 'study-session '(= id 1))))
              (should (= 1 (plist-get saved :reviewed)))
              (gnosis-scheduler-set-retention 0.95)
              ;; A retained retry ignores later configuration changes.
              (gnosis-review-result id nil pending)
              (should (equal saved (gnosis-get 'data 'study-session '(= id 1)))))
            (should (= 1 (gnosis-review-state-reviewed gnosis-review--state)))
            (should (equal (list id) (gnosis-review-state-requeued gnosis-review--state)))
            (should (equal (list id) (gnosis-review-state-remaining gnosis-review--state)))
            (should (= 1 (length (gnosis-select '* (if (eq mode 'due) 'review-events 'practice-events)
                                                 `(= thema-id ,id)))))
            (should (gnosis-review-state-undo gnosis-review--state))))))))

(ert-deftest gnosis-study-stale-skip-preserves-authoritative-session ()
  (gnosis-test-study
    (dolist (mode '(due practice))
      (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
             (buf (gnosis-test-study-state (list id) mode))
             (stale (gnosis-review--read-session)))
        (with-current-buffer buf (gnosis-review-result id t (gnosis-review-algorithm id t)))
        (gnosis-toggle-suspend-themata (list id) 1 t)
        (let ((saved (gnosis-get 'data 'study-session '(= id 1))))
          (should-error (gnosis-review-session stale))
          (should (equal saved (gnosis-get 'data 'study-session '(= id 1)))))
        (gnosis-test-study-state (list id) mode)
        (let ((replacement (gnosis-get 'data 'study-session '(= id 1))))
          (should-error (gnosis-review--skip stale id))
          (should (equal replacement (gnosis-get 'data 'study-session '(= id 1)))))))))

(ert-deftest gnosis-study-preview-invalidated-by-review-void ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
           (event (gnosis-scheduler-event-id)))
      (gnosis-scheduler-accept-review event id 'success 1 20260901)
      (with-current-buffer (gnosis-test-study-state (list id) 'due)
        (let ((pending (gnosis-review--pending-result id t nil 2 20260905)))
          (gnosis-scheduler-void-review (gnosis-scheduler-event-id) event)
          (let ((before (gnosis-test-study-snapshot))
                (saved (gnosis-get 'data 'study-session '(= id 1))))
            (should-error (gnosis-review-result id t pending))
            (should (equal before (gnosis-test-study-snapshot)))
            (should (equal saved (gnosis-get 'data 'study-session '(= id 1))))))))))

(ert-deftest gnosis-study-practice-identity-conflict-and-write-rollback ()
  (gnosis-test-study
    (let ((id (gnosis-test--add-basic-thema "Q" "A")))
      (with-current-buffer (gnosis-test-study-state (list id) 'practice)
        (let ((pending (gnosis-review-algorithm id t))
              (execute (symbol-function 'gnosis-sqlite-execute))
              (before (gnosis-test-study-snapshot)))
          (cl-letf (((symbol-function 'gnosis-sqlite-execute)
                     (lambda (db sql &optional values)
                       (prog1 (funcall execute db sql values)
                         (when (string-prefix-p "INSERT INTO practice_events" sql)
                           (error "Failure after event insertion"))))))
            (should-error (gnosis-review-result id t pending)))
          (should-not (gnosis-select '* 'practice-events))
          (should (= 0 (gnosis-review-state-reviewed (gnosis-review--read-session))))
          (gnosis-review-result id t pending)
          (should-error (gnosis-study-accept-practice
                         (plist-put (copy-sequence pending) :outcome 'failure)))
          (should (equal before (gnosis-test-study-snapshot)))
          (should (= 1 (length (gnosis-select '* 'practice-events)))))))))

(ert-deftest gnosis-study-editor-preserves-source-and-existing-draft ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A" '("needs_work") "[[id:source][Source]]"))
           (source (generate-new-buffer "*Study source*"))
           (text "Source text must not be replaced"))
      (switch-to-buffer source)
      (insert text)
      (gnosis-edit-thema id)
      (should (equal "*Gnosis Edit*" (buffer-name)))
      (should (member "needs_work" (nth 6 (car (gnosis-export-parse-themata)))))
      (insert "Reworded ")
      (let ((draft (buffer-string)) (register (get-register :gnosis-edit)))
        (should-error (gnosis-edit-thema id))
        (should (equal draft (buffer-string)))
        (should (eq register (get-register :gnosis-edit))))
      (should (equal text (with-current-buffer source (buffer-string))))
      (let ((gnosis-save-hook nil)) (gnosis-save))
      (should (equal text (with-current-buffer source (buffer-string))))
      (should (equal "[[id:source][Source]]" (gnosis-get 'parathema 'extras `(= id ,id)))))))

(ert-deftest gnosis-study-replacement-and-discard-races ()
  (gnosis-test-study
    (let ((id (gnosis-test--add-basic-thema "Q" "A")) saved)
      (should-error
       (gnosis-review-loop
        (lambda ()
          (gnosis-test-study-state (list id) 'practice)
          (setq saved (gnosis-get 'data 'study-session '(= id 1)))
          (list id)) 'practice))
      (should (equal saved (gnosis-get 'data 'study-session '(= id 1))))
      (cl-letf (((symbol-function 'y-or-n-p)
                 (lambda (&rest _)
                   (gnosis-test-study-state (list id) 'practice)
                   (setq saved (gnosis-get 'data 'study-session '(= id 1)))
                   t)))
        (should-error (gnosis-review-discard)))
      (should (equal saved (gnosis-get 'data 'study-session '(= id 1)))))))

(ert-deftest gnosis-study-summary-flag-distinction-and-commit ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A" '("needs_work")))
           committed state)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method) (lambda (&rest _) "A"))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?n))
                ((symbol-function 'gnosis-review-commit) (lambda (n) (setq committed n))))
        (setq state (gnosis-review-loop (list id) 'practice)))
      (should (= 1 committed))
      (should (= 0 (plist-get (gnosis-review-summary state) :needs-work)))
      (gnosis-review--show-summary state)
      (should (string-match-p "Last-attempt failures (not manual flags): 0" (buffer-string)))
      (should (member "needs_work" (gnosis-get-tags-for-ids (list id)))))))

(ert-deftest gnosis-study-native-subtree-membership ()
  (gnosis-test-study
    (with-temp-buffer
      (org-mode)
      (insert "* Parent\n:PROPERTIES:\n:ID: root\n:END:\n** Child\n:PROPERTIES:\n:ID: child\n:END:\n*** ID-less\nProse\n* Outside\n:PROPERTIES:\n:ID: outside\n:END:\n")
      (goto-char (point-min))
      (search-forward "** Child")
      (let (selected)
        (cl-letf (((symbol-function 'gnosis-study--start)
                   (lambda (ids mode &rest _) (setq selected (cons mode ids)))))
          (gnosis-study-subtree)
          (should (equal '(practice "child") selected))
          (gnosis-study-subtree t)
          (should (equal '(due "child") selected)))))))

(ert-deftest gnosis-study-owned-buffer-boundaries ()
  (gnosis-test-study
    (let ((buf (get-buffer-create gnosis-review-buffer-name))
          (audit (get-buffer-create "*Gnosis History Evidence*")))
      (with-current-buffer buf (insert "Unrelated draft"))
      (with-current-buffer audit (insert "Unrelated history draft"))
      (should-error (gnosis-review--setup-buffer nil))
      (gnosis-study-history-audit)
      (should (equal "Unrelated draft" (with-current-buffer buf (buffer-string))))
      (should (equal "Unrelated history draft" (with-current-buffer audit (buffer-string)))))))

(ert-deftest gnosis-study-undo-refreshes-summary-after-commit ()
  (gnosis-test-study
    (dolist (mode '(due practice))
      (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
             (buf (gnosis-test-study-state (list id) mode)))
        (with-current-buffer buf
          (gnosis-review-result id t (gnosis-review-algorithm id t)))
        (let* ((slot (gnosis-review-state-undo (gnosis-review--read-session)))
               (event (plist-get slot :event-id))
               (correction (plist-get slot :correction-id))
               (show (symbol-function 'gnosis-review--show-summary)))
          (cl-letf (((symbol-function 'gnosis-review--show-summary)
                     (lambda (_) (error "Summary failed after correction commit"))))
            (should-error (gnosis-review-undo event correction)))
          (should (= 0 (gnosis-review-state-reviewed (gnosis-review--read-session))))
          (cl-letf (((symbol-function 'gnosis-review--show-summary)
                     (lambda (state)
                       (should (equal (gnosis-review--state-data state)
                                      (gnosis-get 'data 'study-session '(= id 1))))
                       (funcall show state))))
            (let ((restored (gnosis-review-undo event correction)))
              (should (= 0 (gnosis-review-state-reviewed restored)))
              (should (equal (list id) (gnosis-review-state-remaining restored)))
              (with-current-buffer (window-buffer (selected-window))
                (should (string-match-p "Accepted attempts: 0" (buffer-string)))))))
        (gnosis--delete 'study-session)))))

(ert-deftest gnosis-study-large-identities-in-checkpoint-and-evidence ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A" nil nil (1+ most-positive-fixnum)))
           (buf (gnosis-test-study-state (list id) 'practice)))
      (with-current-buffer buf
        (gnosis-review-result id nil (gnosis-review-algorithm id nil))
        (setq gnosis-review--state (gnosis-review--read-session))
        (let ((decoded (car (gnosis-review-state-remaining gnosis-review--state))))
          (should (equal id decoded))
          (should-not (eq id decoded))
          (gnosis-review-result decoded t (gnosis-review-algorithm decoded t))))
      (let ((summary (gnosis-review-summary (gnosis-review--read-session))))
        (should (= 1 (plist-get summary :unique)))
        (should (= 1 (plist-get summary :first-failure)))
        (should (= 1 (plist-get summary :retry-success)))
        (should (= 0 (plist-get summary :needs-work))))
      (cl-loop for day in '(20260901 20260903 20260905)
               for time from 1
               do (gnosis-scheduler-accept-review (gnosis-scheduler-event-id) id 'failure time day))
      (gnosis-study-repair)
      (should (equal "2 / 2" (aref (cadar tabulated-list-entries) 3))))))

(defun gnosis-test-study-reject-alternate-replacement (table migrated)
  "Check TABLE alternate-key replacement and hard deletion after MIGRATED setup."
  (gnosis-test-with-old-db
    (when migrated
      (gnosis-test--create-v8-schema)
      (should (= 8 (gnosis--db-version))))
    (gnosis-db-init)
    (should (= gnosis-db-version (gnosis--db-version)))
    ;; REPLACE must be rejected without depending on recursive delete triggers.
    (gnosis-sqlite-execute gnosis-db "PRAGMA recursive_triggers = OFF")
    (should (equal '((0)) (gnosis-sqlite-select gnosis-db "PRAGMA recursive_triggers")))
    (let ((id (gnosis-test--add-basic-thema "Q" "A")))
      (gnosis-scheduler-accept-review (make-string 64 ?a) id 'success 100 20260907)
      (gnosis-sqlite-execute gnosis-db
        "INSERT INTO practice_events VALUES ('practice-old', ?, 'session', 1, 100, 3)"
        (list id))
      (gnosis-sqlite-execute gnosis-db
        "INSERT INTO practice_voids VALUES ('practice-correction', 'practice-old')")
      (gnosis-sqlite-execute gnosis-db
        "INSERT INTO review_voids SELECT 'review-correction', event_id FROM review_events")
      (let* ((tables '(review_events review_voids practice_events practice_voids))
             (snapshot (lambda ()
                         (mapcar (lambda (name)
                                   (gnosis-sqlite-select gnosis-db
                                     (format "SELECT * FROM %s ORDER BY 1" name)))
                                 tables)))
             (before (funcall snapshot))
             (schedule (gnosis-test-study-snapshot)))
        (should (seq-every-p #'consp before))
        (should-error
         (gnosis-sqlite-execute gnosis-db
           (pcase-exhaustive table
             ('practice_events
              "INSERT OR REPLACE INTO practice_events
               SELECT 'practice-new', thema_id, session_id, attempt, 200, 1
                 FROM practice_events WHERE event_id = 'practice-old'")
             ('practice_voids
              "INSERT OR REPLACE INTO practice_voids
               VALUES ('practice-correction-new', 'practice-old')")
             ('review_voids
              "INSERT OR REPLACE INTO review_voids
               SELECT 'review-correction-new', event_id FROM review_events")))
         :type 'sqlite-error)
        (should (equal before (funcall snapshot)))
        (should (equal schedule (gnosis-test-study-snapshot)))
        (gnosis--delete 'themata `(= id ,id))
        (should-not (gnosis-select '* 'themata))
        (should (seq-every-p #'null (funcall snapshot)))
        (should-not (gnosis-sqlite-select gnosis-db "PRAGMA foreign_key_check"))))))

(ert-deftest gnosis-study-practice-event-alternate-replacement-fresh ()
  (gnosis-test-study-reject-alternate-replacement 'practice_events nil))

(ert-deftest gnosis-study-practice-event-alternate-replacement-from-v8 ()
  (gnosis-test-study-reject-alternate-replacement 'practice_events t))

(ert-deftest gnosis-study-practice-void-alternate-replacement-fresh ()
  (gnosis-test-study-reject-alternate-replacement 'practice_voids nil))

(ert-deftest gnosis-study-practice-void-alternate-replacement-from-v8 ()
  (gnosis-test-study-reject-alternate-replacement 'practice_voids t))

(ert-deftest gnosis-study-review-void-alternate-replacement-fresh ()
  (gnosis-test-study-reject-alternate-replacement 'review_voids nil))

(ert-deftest gnosis-study-review-void-alternate-replacement-from-v8 ()
  (gnosis-test-study-reject-alternate-replacement 'review_voids t))

(ert-deftest gnosis-study-summary-skipped-retry-is-not-unattempted ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "Q" "A"))
           (before (gnosis-test-study-snapshot))
           state)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) "wrong"))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?q)))
        (setq state (gnosis-review-loop (list id) 'practice)))
      (should (equal (list id) (gnosis-review-state-remaining state)))
      (gnosis-toggle-suspend-themata (list id) 1 t)
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) (ert-fail "Suspended retry must not prompt"))))
        (gnosis-review-resume))
      (setq state (gnosis-review--read-session))
      (let ((summary (gnosis-review-summary state)))
        (should (= 1 (plist-get summary :selected)))
        (should (= 1 (plist-get summary :unique)))
        (should (= 1 (gnosis-review-state-reviewed state)))
        (should (= 0 (plist-get summary :unattempted)))
        (should (= 1 (plist-get summary :excluded))))
      (gnosis-review--show-summary state)
      (should (string-match-p "Unattempted: 0\nSkipped items (including retries): 1\n"
                              (buffer-string)))
      (gnosis-toggle-suspend-themata (list id) 0 t)
      (should (equal before (gnosis-test-study-snapshot))))))

(ert-deftest gnosis-study-repair-help-offers-only-contextual-actions ()
  (gnosis-test-study
    (gnosis-test-study-node "topic")
    (let (help)
      (cl-letf (((symbol-function 'keymap-popup)
                 (lambda (map &rest _)
                   (setq help (keymap-popup--render (keymap-popup--meta map 'descriptions))))))
        (gnosis-study-repair)
        (call-interactively (key-binding (kbd "?")))
        (dolist (text '("Review due" "Practise (no rescheduling)" "Create thema"))
          (should-not (string-match-p (regexp-quote text) help)))
        (dolist (key '("d" "p" "c"))
          (should (memq (key-binding (kbd key)) '(nil undefined))))
        (should (string-match-p "Open topic" help))
        (should (eq 'gnosis-study-topic (key-binding (kbd "o"))))
        (should (eq 'gnosis-study-edit (key-binding (kbd "RET"))))
        (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Same title")))
          (call-interactively (key-binding (kbd "o"))))
        (should (equal "topic" gnosis-study--topic))
        (call-interactively (key-binding (kbd "?")))
        (dolist (text '("Review due" "Practise (no rescheduling)" "Create thema"))
          (should (string-match-p (regexp-quote text) help)))
        (dolist (entry '(("d" . gnosis-study-due) ("p" . gnosis-study-practice)
                         ("c" . gnosis-study-create)))
          (should (eq (cdr entry) (key-binding (kbd (car entry))))))))))

(defun gnosis-test-study-all-evidence ()
  "Return schedules, accepted evidence, checkpoints and retained history."
  (cons (gnosis-test-study-snapshot)
        (mapcar (lambda (table)
                  (gnosis-sqlite-select gnosis-db
                    (format "SELECT * FROM %s ORDER BY 1" table)))
                '(practice_events practice_voids study_session study_history))))

(defun gnosis-test-study-summary (ids mode)
  "Accept the first of IDS in MODE and display its summary buffer."
  (with-current-buffer (gnosis-test-study-state ids mode)
    (let ((id (car ids)))
      (gnosis-review-result id t (gnosis-review-algorithm id t)))
    (gnosis-review--show-summary gnosis-review--state)
    (current-buffer)))

(defun gnosis-test-study-stale-summary-action (key)
  "Require native KEY to reject superseded scheduled and practice summaries."
  (dolist (mode '(due practice))
    (dolist (historical '(nil t))
      (gnosis-test-study
        (let* ((a (gnosis-test--add-basic-thema "A" "A"))
               (b (gnosis-test--add-basic-thema "B" "B"))
               (old (gnosis-test-study-summary (list a) mode))
               (session (gnosis-review-state-session-id (gnosis-review--read-session))))
          ;; B has both an undo slot and an unfinished queue.
          (gnosis-test-study-summary (list b a) mode)
          (when historical
            (gnosis-review--show-summary
             (apply #'gnosis-review-state-create :persistent-p t :database gnosis-db
                    (cddr (gnosis-get 'data 'study-history `(= session-id ,session)))))
            (setq old (current-buffer)))
          (let ((before (gnosis-test-study-all-evidence)))
            (with-current-buffer old
              (should (derived-mode-p 'gnosis-review-summary-mode))
              (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t))
                        ((symbol-function 'gnosis--read-string-with-input-method)
                         (lambda (&rest _) (ert-fail "Stale summary entered input"))))
                (should-error (call-interactively (local-key-binding (kbd key)))
                              :type 'user-error)))
            (should (equal before (gnosis-test-study-all-evidence)))))))))

(ert-deftest gnosis-study-summary-undo-rejects-newer-session ()
  (gnosis-test-study-stale-summary-action "u"))

(ert-deftest gnosis-study-summary-resume-rejects-newer-session ()
  (gnosis-test-study-stale-summary-action "r"))

(ert-deftest gnosis-study-summary-discard-rejects-newer-session ()
  (gnosis-test-study-stale-summary-action "d"))

(ert-deftest gnosis-study-summary-rejects-identical-checkpoint-in-other-db ()
  (gnosis-test-study
    (dolist (mode '(due practice))
      (let* ((id (gnosis-test--add-basic-thema "A" "A"))
             (summary (gnosis-test-study-summary (list id id) mode))
             (copy (expand-file-name "other.db" gnosis-dir)))
        ;; Copying preserves numeric thema IDs and all opaque session/event IDs.
        (gnosis-backup-db copy)
        (let ((gnosis-db (gnosis-sqlite-open copy)))
          (unwind-protect
              (let ((before (gnosis-test-study-all-evidence)))
                (dolist (key '("u" "r" "d"))
                  (with-current-buffer summary
                    (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t))
                              ((symbol-function 'gnosis--read-string-with-input-method)
                               (lambda (&rest _) (ert-fail "Wrong database entered input"))))
                      (should-error (call-interactively (local-key-binding (kbd key)))
                                    :type 'user-error)))
                  (should (equal before (gnosis-test-study-all-evidence)))))
            (gnosis-sqlite-close gnosis-db)))
        (delete-file copy)))))

(ert-deftest gnosis-study-summary-discard-captures-owner-before-prompt ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "A" "A"))
           (summary (gnosis-test-study-summary (list id id) 'practice))
           (copy (expand-file-name "other.db" gnosis-dir))
           (original gnosis-db))
      (gnosis-backup-db copy)
      (let ((other (gnosis-sqlite-open copy)))
        (unwind-protect
            (let ((before (gnosis-test-study-all-evidence)))
              (with-current-buffer summary
                (cl-letf (((symbol-function 'y-or-n-p)
                           (lambda (&rest _)
                             (setq gnosis-db other)
                             (set-buffer (get-buffer-create "*Different owner*"))
                             t)))
                  (should-error (call-interactively (local-key-binding (kbd "d")))
                                :type 'user-error)))
              (should (equal before (gnosis-test-study-all-evidence)))
              (setq gnosis-db original)
              (should (equal before (gnosis-test-study-all-evidence))))
          (setq gnosis-db original)
          (gnosis-sqlite-close other))))))

(ert-deftest gnosis-study-summary-owned-actions-and-public-resume ()
  (gnosis-test-study
    (dolist (mode '(due practice))
      (let* ((id (gnosis-test--add-basic-thema "A" "A"))
             (schedule (gnosis-test-study-snapshot))
             (summary (gnosis-test-study-summary (list id) mode)))
        (switch-to-buffer summary)
        (call-interactively (local-key-binding (kbd "u")))
        (should (= 0 (gnosis-review-state-reviewed (gnosis-review--read-session))))
        (let ((before (gnosis-test-study-all-evidence)))
          ;; The old same-session view must not act on a changed checkpoint.
          (with-current-buffer summary
            (should-error (call-interactively (local-key-binding (kbd "u")))
                          :type 'user-error))
          (should (equal before (gnosis-test-study-all-evidence))))
        ;; Exercise both the native binding and public resume away from summaries.
        (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                   (lambda (&rest _) "A"))
                  ((symbol-function 'read-char-choice) (lambda (&rest _) ?n)))
          (if (eq mode 'due)
              (progn
                (gnosis-review--show-summary (gnosis-review--read-session))
                (call-interactively (local-key-binding (kbd "r"))))
            (with-temp-buffer (call-interactively #'gnosis-review-resume))))
        (should (= 1 (gnosis-review-state-reviewed (gnosis-review--read-session))))
        ;; A fresh accepted grade in the SAME session still supersedes the old view.
        (let ((before (gnosis-test-study-all-evidence)))
          (with-current-buffer summary
            (should-error (call-interactively (local-key-binding (kbd "u")))
                          :type 'user-error))
          (should (equal before (gnosis-test-study-all-evidence))))
        (when (eq mode 'practice)
          (should (equal schedule (gnosis-test-study-snapshot))))
        (gnosis-review--show-summary (gnosis-review--read-session))
        (cl-letf (((symbol-function 'y-or-n-p)
                   (lambda (&rest _)
                     (set-buffer (get-buffer-create "*Different owner*")) t)))
          (call-interactively (local-key-binding (kbd "d"))))
        (should-not (gnosis-review--read-session))
        (when (eq mode 'practice)
          (should (equal schedule (gnosis-test-study-snapshot))))))))

(ert-deftest gnosis-study-summary-keeps-source-database-before-render ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "A" "A"))
           (_summary (gnosis-test-study-summary (list id) 'practice))
           (state (gnosis-review--read-session))
           (source gnosis-db)
           (copy (expand-file-name "other.db" gnosis-dir)))
      (setf (gnosis-review-state-policy state) (gnosis-review-practice-policy))
      (gnosis-review--save-session state)
      (gnosis-backup-db copy)
      ;; The foreign database still owns colliding IDs and accepted evidence.
      ;; Render the source's deletion, not that evidence or the old checkpoint.
      (gnosis-delete-thema id t)
      (let ((source-before (gnosis-test-study-all-evidence))
            (checkpoint (gnosis-review--state-data state))
            (gnosis-db (gnosis-sqlite-open copy)))
        (unwind-protect
            (let ((before (gnosis-test-study-all-evidence))
                  (foreign gnosis-db))
              (gnosis-review--show-summary state)
              (should (eq gnosis-db foreign))
              (should (eq (car gnosis-review--summary-target) source))
              (should (equal checkpoint (gnosis-review--state-data state)))
              (should (string-match-p "Unique attempted: 0   Accepted attempts: 0"
                                      (buffer-string)))
              (should (string-match-p "Remaining due backlog: 0" (buffer-string)))
              (should (string-match-p
                       "Targets reached: 0   Attempt limit (target unmet): 0   Unfinished: 0   Excluded: 1"
                       (buffer-string)))
              (should-error (call-interactively (local-key-binding (kbd "u")))
                            :type 'user-error)
              (should (equal before (gnosis-test-study-all-evidence)))
              (let ((gnosis-db source))
                (should (equal source-before (gnosis-test-study-all-evidence)))))
          (gnosis-sqlite-close gnosis-db))))))

(ert-deftest gnosis-study-summary-resume-rejects-db-change-during-input ()
  (gnosis-test-study
    (dolist (mode '(due practice))
      (let* ((id (gnosis-test--add-basic-thema "A" "A"))
             (summary (gnosis-test-study-summary (list id id) mode))
             (copy (expand-file-name "other.db" gnosis-dir))
             (original gnosis-db))
        (gnosis-backup-db copy)
        (let ((other (gnosis-sqlite-open copy)))
          (unwind-protect
              (let ((before (gnosis-test-study-all-evidence)))
                (switch-to-buffer summary)
                (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                           (lambda (&rest _) (setq gnosis-db other) "A"))
                          ((symbol-function 'read-char-choice) (lambda (&rest _) ?n))
                          ((symbol-function 'y-or-n-p) (lambda (&rest _) nil)))
                  (should-error (call-interactively (local-key-binding (kbd "r")))
                                :type 'user-error))
                (should (equal before (gnosis-test-study-all-evidence)))
                (setq gnosis-db original)
                (should (equal before (gnosis-test-study-all-evidence))))
            (setq gnosis-db original)
            (gnosis-sqlite-close other)))
        (delete-file copy)))))

(ert-deftest gnosis-study-summary-resumes-legacy-checkpoint-defaults ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "A" "A"))
           (buf (gnosis-test-study-state (list id) 'practice))
           (state (buffer-local-value 'gnosis-review--state buf))
           ;; Version 1 predates optional practice policy and launch metadata.
           (data (cl-loop for (key value) on (gnosis-review--state-data state)
                          by #'cddr when value append (list key value))))
      (gnosis-sqlite-execute gnosis-db "UPDATE study_session SET data = ?"
                             (list data))
      (gnosis-review--show-summary (gnosis-review--read-session))
      (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                 (lambda (&rest _) "A"))
                ((symbol-function 'read-char-choice) (lambda (&rest _) ?n)))
        (call-interactively (local-key-binding (kbd "r"))))
      (should-not (gnosis-review-state-remaining (gnosis-review--read-session)))
      (should (= 1 (gnosis-review-state-reviewed (gnosis-review--read-session)))))))

(ert-deftest gnosis-study-monkeytype-public-selection-no-study-writes ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "[[id:source][Question]]" "Answer" '("chosen")))
           (_other (gnosis-test--add-basic-thema "Other" "Other" '("other")))
           (before (gnosis-test-study-all-evidence))
           (review (symbol-function 'gnosis-review))
           seen)
      (cl-letf (((symbol-function 'gnosis-completing-read)
                 (lambda (&rest _) "All themata of tag(s)"))
                ((symbol-function 'gnosis-tags-filter-prompt)
                 (lambda (&rest _) '(("chosen"))))
                ((symbol-function 'recursive-edit)
                 (lambda ()
                   (should (derived-mode-p 'gnosis-monkeytype-mode))
                   (should (eq review (symbol-function 'gnosis-review)))
                   (push (buffer-substring-no-properties (point-min) (point-max)) seen))))
        (call-interactively #'gnosis-monkeytype-start))
      (should (equal '("Question Answer") seen))
      (should (gnosis-get 'id 'themata `(= id ,id)))
      (should (equal before (gnosis-test-study-all-evidence))))))

(ert-deftest gnosis-study-review-and-monkeytype-share-selection ()
  (gnosis-test-study
    (dolist (row '((101 "New" "chosen") (102 "Overdue" "chosen")
                   (103 "Future" "chosen") (104 "Other" "other")))
      (gnosis-test--add-basic-thema (nth 1 row) "Answer"
                                    (list (nth 2 row)) nil (car row)))
    (gnosis-sqlite-execute gnosis-db
      "UPDATE scheduler_state SET reps = 1, due_day = ? WHERE thema_id = 102"
      (list (gnosis--date-to-int (gnosis-date -1))))
    (gnosis-sqlite-execute gnosis-db
      "UPDATE scheduler_state SET due_day = ? WHERE thema_id = 103"
      (list (gnosis--date-to-int (gnosis-date 1))))
    (let ((before (gnosis-test-study-all-evidence))
          (gnosis-new-themata-limit nil))
      (dolist (case '(("Due themata" "d" (101 102 104))
                      ("Due themata of specified tag(s)" "t" (101 102))
                      ("Overdue themata" "o" (102))
                      ("Due themata (Without Overdue)" "w" (101 104))
                      ("All themata of tag(s)" "T" (101 102 103))))
        (let (typing review)
          (cl-letf (((symbol-function 'gnosis-completing-read)
                     (lambda (&rest _) (car case)))
                    ((symbol-function 'gnosis-tags-filter-prompt)
                     (lambda (&rest _) '(("chosen"))))
                    ((symbol-function 'gnosis-monkeytype-thema)
                     (lambda (id) (push id typing)))
                    ((symbol-function 'gnosis-review-loop)
                     (lambda (collector &rest _)
                       (setq review (if (functionp collector)
                                        (funcall collector) collector)))))
            (call-interactively #'gnosis-monkeytype-start)
            (call-interactively (keymap-lookup gnosis-review-map (nth 1 case))))
          (should (equal (nth 2 case) (sort typing #'<)))
          (should (equal (nth 2 case) (sort review #'<)))
          (should (equal before (gnosis-test-study-all-evidence))))))))

(ert-deftest gnosis-study-monkeytype-cancel-selection-keeps-checkpoint ()
  (gnosis-test-study
    (let* ((id (gnosis-test--add-basic-thema "A" "A"))
           (_summary (gnosis-test-study-summary (list id id) 'practice))
           (before (gnosis-test-study-all-evidence)))
      (cl-letf (((symbol-function 'gnosis-completing-read)
                 (lambda (&rest _) (signal 'quit nil))))
        (should (eq 'cancelled
                    (condition-case nil (call-interactively #'gnosis-monkeytype-start)
                      (quit 'cancelled)))))
      (should (equal before (gnosis-test-study-all-evidence))))))

(defun gnosis-test-study-view-fixture (label)
  "Insert colliding row identities with distinctive LABEL content."
  (gnosis-test-study-node "topic" label)
  (gnosis-test--add-basic-thema label "Answer" '("needs_work") nil 42)
  (gnosis-test--add-basic-thema "Unrelated" "Other" '("other") nil 43)
  (gnosis--insert-into 'thema-links '([42 "topic"])))

(defun gnosis-test-study-view-snapshot ()
  "Return content and all study evidence for collection command checks."
  (cons (mapcar (lambda (table) (gnosis-select '* table))
                '(themata extras thema-tag thema-links nodes))
        (gnosis-test-study-all-evidence)))

(defun gnosis-test-study-open-view (kind)
  "Open KIND of collection and select its first row."
  (if (eq kind 'topic) (gnosis-study-topic "topic") (gnosis-study-repair))
  (goto-char (point-min))
  (should (= 42 (tabulated-list-get-id))))

(defun gnosis-test-study-view-stale-binding (key)
  "Require KEY to refuse foreign databases in both collection kinds."
  (dolist (kind '(topic repair))
    (gnosis-test-study
      (gnosis-test-study-view-fixture "A displayed")
      (gnosis-test-study-open-view kind)
      (let ((buffer (current-buffer))
            (text (buffer-string))
            (header header-line-format)
            (before (gnosis-test-study-view-snapshot)))
        (gnosis-test-with-db
          (gnosis-test-study-view-fixture "B not selected")
          (let ((other (gnosis-test-study-view-snapshot)))
            (cl-letf (((symbol-function 'y-or-n-p)
                       (lambda (&rest _) (ert-fail "Stale view prompted")))
                      ((symbol-function 'gnosis-nodes-goto-id)
                       (lambda (&rest _) (ert-fail "Stale view navigated")))
                      ((symbol-function 'gnosis-edit-thema)
                       (lambda (&rest _) (ert-fail "Stale view opened editor"))))
              (should-error (call-interactively (key-binding (kbd key)))
                            :type 'user-error))
            (should (equal other (gnosis-test-study-view-snapshot)))
            (should (eq buffer (current-buffer)))
            (should (equal text (buffer-string)))
            (should (equal header header-line-format))))
        (should (equal before (gnosis-test-study-view-snapshot)))))))

(ert-deftest gnosis-study-view-flag-rejects-foreign-database ()
  (gnosis-test-study-view-stale-binding "f"))

(ert-deftest gnosis-study-view-suspend-rejects-foreign-database ()
  (gnosis-test-study-view-stale-binding "s"))

(ert-deftest gnosis-study-view-edit-rejects-foreign-database ()
  (gnosis-test-study-view-stale-binding "RET"))

(ert-deftest gnosis-study-view-suspend-rechecks-prompt-owner ()
  (dolist (kind '(topic repair))
    (dolist (change '(database repurpose refresh))
      (gnosis-test-study
        (gnosis-test-study-view-fixture "A displayed")
        (gnosis-test-study-open-view kind)
        (let ((original gnosis-db)
              (directory gnosis-dir)
              (buffer (current-buffer))
              (before (gnosis-test-study-view-snapshot)))
          (gnosis-test-with-db
            (gnosis-test-study-view-fixture "B not selected")
            (let ((other gnosis-db)
                  (other-dir gnosis-dir)
                  (other-before (gnosis-test-study-view-snapshot)))
              (let ((gnosis-db original) (gnosis-dir directory))
                (cl-letf (((symbol-function 'y-or-n-p)
                           (lambda (&rest _)
                             (pcase change
                               ('database (setq gnosis-db other gnosis-dir other-dir))
                               ('repurpose (fundamental-mode)
                                           (setq buffer-read-only nil)
                                           (erase-buffer) (insert "Successor draft"))
                               ('refresh (gnosis-study-refresh)))
                             t)))
                  (should-error (call-interactively (key-binding (kbd "s")))
                                :type 'user-error)))
              (should (equal other-before (gnosis-test-study-view-snapshot)))))
          (should (equal before (gnosis-test-study-view-snapshot)))
          (when (eq change 'repurpose)
            (should (eq buffer (current-buffer)))
            (should (equal "Successor draft" (buffer-string)))
            (should (eq major-mode 'fundamental-mode))))))))

(ert-deftest gnosis-study-view-edit-rechecks-source-prompt-owner ()
  (dolist (change '(database repurpose refresh))
    (gnosis-test-study
      (gnosis-test-study-view-fixture "A displayed")
      (gnosis-test-study-node "second" "Second source")
      (gnosis--insert-into 'thema-links '([42 "second"]))
      (gnosis-study-repair)
      (goto-char (point-min))
      (let ((original gnosis-db) (directory gnosis-dir)
            (before (gnosis-test-study-view-snapshot)))
        (gnosis-test-with-db
          (gnosis-test-study-view-fixture "B not selected")
          (let ((other gnosis-db) (other-dir gnosis-dir)
                (other-before (gnosis-test-study-view-snapshot)))
            (let ((gnosis-db original) (gnosis-dir directory))
              (cl-letf (((symbol-function 'completing-read)
                         (lambda (&rest _)
                           (pcase change
                             ('database (setq gnosis-db other gnosis-dir other-dir))
                             ('repurpose (fundamental-mode)
                                         (setq buffer-read-only nil)
                                         (erase-buffer) (insert "Successor draft"))
                             ('refresh (gnosis-study-refresh)))
                           "A displayed"))
                        ((symbol-function 'gnosis-nodes-goto-id)
                         (lambda (&rest _) (ert-fail "Stale source navigated")))
                        ((symbol-function 'gnosis-edit-thema)
                         (lambda (&rest _) (ert-fail "Stale source opened editor"))))
                (should-error (call-interactively (key-binding (kbd "RET")))
                              :type 'user-error)))
            (should (equal other-before (gnosis-test-study-view-snapshot)))))
        (should (equal before (gnosis-test-study-view-snapshot)))))))

(ert-deftest gnosis-study-view-owned-actions-cancel-and-fresh-refresh ()
  (dolist (kind '(topic repair))
    (gnosis-test-study
      (gnosis-test-study-view-fixture "A displayed")
      (gnosis-test-study-open-view kind)
      (let ((before (gnosis-test-study-view-snapshot))
            (text (buffer-string)))
        (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) nil)))
          (call-interactively (key-binding (kbd "s"))))
        (should (equal before (gnosis-test-study-view-snapshot)))
        (should (equal text (buffer-string)))
        (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) (signal 'quit nil))))
          (should (eq 'cancelled
                      (condition-case nil
                          (call-interactively (key-binding (kbd "s")))
                        (quit 'cancelled)))))
        (should (equal before (gnosis-test-study-view-snapshot)))
        (should (equal text (buffer-string))))
      (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
        (call-interactively (key-binding (kbd "s")))
        (should (gnosis-suspended-p 42))
        (should (equal "Suspended" (aref (cadar tabulated-list-entries) 2)))
        (call-interactively (key-binding (kbd "s")))
        (should-not (gnosis-suspended-p 42)))
      (call-interactively (key-binding (kbd "f")))
      (should-not (member "needs_work" (gnosis-get-tags-for-ids '(42))))
      (should (equal '("other") (gnosis-get-tags-for-ids '(43))))
      (gnosis-test-with-db
        (gnosis-test-study-view-fixture "B deliberately refreshed")
        (call-interactively (key-binding (kbd "g")))
        (goto-char (point-min))
        (should (string-match-p "B deliberately refreshed" (buffer-string)))
        (call-interactively (key-binding (kbd "f")))
        (should-not (member "needs_work" (gnosis-get-tags-for-ids '(42))))))))

(ert-deftest gnosis-study-view-edit-rechecks-after-source-navigation ()
  (gnosis-test-study
    (gnosis-test-study-view-fixture "A displayed")
    (gnosis-test-study-open-view 'topic)
    (let ((original gnosis-db) (directory gnosis-dir)
          (before (gnosis-test-study-view-snapshot)))
      (gnosis-test-with-db
        (gnosis-test-study-view-fixture "B not selected")
        (let ((other gnosis-db) (other-dir gnosis-dir)
              (other-before (gnosis-test-study-view-snapshot)))
          (let ((gnosis-db original) (gnosis-dir directory))
            (cl-letf (((symbol-function 'gnosis-nodes-goto-id)
                       (lambda (&rest _)
                         (switch-to-buffer (generate-new-buffer " *Source*"))
                         (setq gnosis-db other gnosis-dir other-dir)))
                      ((symbol-function 'gnosis-edit-thema)
                       (lambda (&rest _) (ert-fail "Navigation retargeted edit"))))
              (should-error (call-interactively (key-binding (kbd "RET")))
                            :type 'user-error)))
          (should (equal other-before (gnosis-test-study-view-snapshot)))))
      (should (equal before (gnosis-test-study-view-snapshot))))))

(ert-deftest gnosis-study-view-repurposed-buffer-rejects-retained-bindings ()
  (dolist (kind '(topic repair))
    (gnosis-test-study
      (gnosis-test-study-view-fixture "A displayed")
      (gnosis-test-study-open-view kind)
      (let ((commands (mapcar (lambda (key) (key-binding (kbd key))) '("f" "s" "RET")))
            (before (gnosis-test-study-view-snapshot)))
        (fundamental-mode)
        (setq buffer-read-only nil)
        (erase-buffer)
        (insert "Successor draft")
        (dolist (command commands)
          (should-error (call-interactively command) :type 'user-error)
          (should (equal "Successor draft" (buffer-string)))
          (should (eq major-mode 'fundamental-mode)))
        (should (equal before (gnosis-test-study-view-snapshot)))))))

(defun gnosis-test-study-view-successor (&optional detach)
  "Associate the current collection with a successor file, then DETACH it."
  (with-temp-file (expand-file-name "successor.txt" gnosis-dir)
    (insert "Saved successor"))
  (set-visited-file-name (expand-file-name "successor.txt" gnosis-dir) t)
  (when detach (set-visited-file-name nil t))
  (let ((inhibit-read-only t))
    (erase-buffer)
    (insert "Unsaved successor λ")))

(ert-deftest gnosis-study-view-file-association-retires-collection ()
  (dolist (kind '(topic repair))
    (dolist (detach '(nil t))
      (gnosis-test-study
        (gnosis-test-study-view-fixture "Displayed")
        (gnosis-test-study-open-view kind)
        (let ((commands (mapcar (lambda (key) (key-binding (kbd key)))
                               (append '("g" "f" "s" "RET" "v")
                                       (when (eq kind 'topic) '("c" "p" "d")))))
              (before (gnosis-test-study-view-snapshot)))
          (gnosis-test-study-view-successor detach)
          (let ((text (buffer-string)) (file buffer-file-name)
                (modified (buffer-modified-p)))
            (dolist (command commands)
              (should-error (call-interactively command) :type 'user-error)
              (should (equal text (buffer-string)))
              (should (equal file buffer-file-name))
              (should (eq modified (buffer-modified-p))))
            (should-error (revert-buffer nil t) :type 'user-error)
            (should (equal text (buffer-string)))
            (should (equal file buffer-file-name))
            (should (eq modified (buffer-modified-p))))
          (should-not gnosis-study--owner)
          (should-not gnosis-study--topic)
          (should-not gnosis-study--repair-p)
          (should (equal before (gnosis-test-study-view-snapshot))))))))

(ert-deftest gnosis-study-view-file-association-during-confirmation ()
  (dolist (kind '(topic repair))
    (dolist (detach '(nil t))
      (gnosis-test-study
        (gnosis-test-study-view-fixture "Displayed")
        (gnosis-test-study-open-view kind)
        (let ((before (gnosis-test-study-view-snapshot)) file)
          (cl-letf (((symbol-function 'y-or-n-p)
                     (lambda (&rest _)
                       (gnosis-test-study-view-successor detach)
                       (setq file buffer-file-name)
                       t)))
            (should-error (call-interactively (key-binding (kbd "s")))
                          :type 'user-error))
          (should (equal "Unsaved successor λ" (buffer-string)))
          (should (equal file buffer-file-name))
          (should (buffer-modified-p))
          (should (equal before (gnosis-test-study-view-snapshot))))))))

(ert-deftest gnosis-study-view-launch-rechecks-confirmation ()
  (dolist (key '("p" "d"))
    (dolist (change '(file detach refresh))
      (gnosis-test-study
        (gnosis-test-study-view-fixture "Displayed")
        (gnosis-test-study-summary '(43 42) 'practice)
        (gnosis-test-study-open-view 'topic)
        (let ((before (gnosis-test-study-view-snapshot)))
          (cl-letf (((symbol-function 'y-or-n-p)
                     (lambda (&rest _)
                       (if (eq change 'refresh) (gnosis-study-refresh)
                         (gnosis-test-study-view-successor (eq change 'detach)))
                       t))
                    ((symbol-function 'gnosis-review--run-state)
                     (lambda (_ state) state)))
            (should-error (call-interactively (key-binding (kbd key)))
                          :type 'user-error))
          (should (equal before (gnosis-test-study-view-snapshot))))))))

(defun gnosis-test-study-nodes-open ()
  "Display and select the fixture's node in the native dashboard."
  (gnosis-dashboard-output-nodes '("topic"))
  (goto-char (point-min))
  (should (equal "topic" (tabulated-list-get-id))))

(defun gnosis-test-study-nodes-stale (key)
  "Require node KEY to refuse a foreign database before selection prompts."
  (gnosis-test-study
    (let ((gnosis-dashboard-buffer-name " *Gnosis node ownership*"))
      (gnosis-test-study-view-fixture "A displayed")
      (gnosis-test-study-summary '(43 42) 'practice)
      (gnosis-test-study-nodes-open)
      (let ((buffer (current-buffer)) (text (buffer-string))
            (before (gnosis-test-study-view-snapshot)))
        (gnosis-test-with-db
          (gnosis-test-study-view-fixture "B foreign")
          (let ((other (gnosis-test-study-view-snapshot)))
            (cl-letf (((symbol-function 'read-number)
                       (lambda (&rest _) (ert-fail "Stale view prompted for depth")))
                      ((symbol-function 'y-or-n-p)
                       (lambda (&rest _) (ert-fail "Stale view prompted to launch"))))
              (should-error (call-interactively (key-binding (kbd key)))
                            :type 'user-error))
            (should (equal other (gnosis-test-study-view-snapshot)))
            (should (eq buffer (current-buffer)))
            (should (equal text (buffer-string)))))
        (should (equal before (gnosis-test-study-view-snapshot)))))))

(ert-deftest gnosis-study-nodes-stale-study ()
  (gnosis-test-study-nodes-stale "S"))
(ert-deftest gnosis-study-nodes-stale-practice ()
  (gnosis-test-study-nodes-stale "p"))
(ert-deftest gnosis-study-nodes-stale-due ()
  (gnosis-test-study-nodes-stale "r"))
(ert-deftest gnosis-study-nodes-stale-review ()
  (gnosis-test-study-nodes-stale "a"))
(ert-deftest gnosis-study-nodes-stale-depth ()
  (gnosis-test-study-nodes-stale "R"))

(ert-deftest gnosis-study-nodes-file-association-retires-fresh-commands ()
  (dolist (key '("p" "r" "S" "a" "R"))
    (dolist (detach '(t nil))
      (dolist (marked '(t nil))
        (dolist (replace-text '(t nil))
          (gnosis-test-study
            (let ((gnosis-dashboard-buffer-name " *Gnosis node ownership*"))
              (gnosis-test-study-view-fixture "Displayed")
              (gnosis-test-study-summary '(43 42) 'due)
              (gnosis-test-study-summary '(43 42) 'practice)
              (gnosis-test-study-nodes-open)
              (when marked
                (call-interactively (key-binding (kbd "m"))))
              (let ((before (gnosis-test-study-view-snapshot)))
                (set-visited-file-name
                 (expand-file-name "successor.txt" gnosis-dir) t)
                (when detach (set-visited-file-name nil t))
                (when replace-text
                  (let ((inhibit-read-only t))
                    (erase-buffer)
                    (insert "Unsaved successor λ")))
                (let ((buffer (current-buffer)) (text (buffer-string))
                      (file buffer-file-name) (modified (buffer-modified-p))
                      (position (point)))
                  (cl-letf (((symbol-function 'read-number)
                             (lambda (&rest _) (ert-fail "Retired view prompted for depth")))
                            ((symbol-function 'y-or-n-p)
                             (lambda (&rest _) (ert-fail "Retired view prompted to launch"))))
                    ;; Resolve a fresh binding after both native transitions.
                    (should-error (call-interactively (key-binding (kbd key)))
                                  :type 'user-error))
                  (should (eq buffer (current-buffer)))
                  (should (equal text (buffer-string)))
                  (should (equal file buffer-file-name))
                  (should (eq modified (buffer-modified-p)))
                  (should (= position (point))))
                (should-not gnosis-dashboard--selected-ids)
                (should (equal before (gnosis-test-study-view-snapshot)))))))))))

(ert-deftest gnosis-study-nodes-launch-rechecks-owner ()
  (dolist (key '("p" "r" "a" "R"))
    (dolist (change '(refresh mode file detach buffer))
      (gnosis-test-study
        (let ((gnosis-dashboard-buffer-name " *Gnosis node ownership*"))
          (gnosis-test-study-view-fixture "Displayed")
          (gnosis-test-study-summary '(43 42) 'practice)
          (gnosis-test-study-nodes-open)
          (setq gnosis-dashboard--selected-ids '("topic"))
          (let ((before (gnosis-test-study-view-snapshot)))
            (cl-letf (((symbol-function 'read-number) (lambda (&rest _) 0))
                      ((symbol-function 'y-or-n-p)
                       (lambda (&rest _)
                         (pcase change
                           ('refresh (gnosis-dashboard-nodes-refresh))
                           ('mode (fundamental-mode))
                           ('file (gnosis-test-study-view-successor))
                           ('detach (gnosis-test-study-view-successor t))
                           ('buffer (switch-to-buffer (generate-new-buffer " *Successor*"))))
                         t))
                      ((symbol-function 'gnosis-review--run-state)
                       (lambda (_ state) state)))
              (should-error (call-interactively (key-binding (kbd key)))
                            :type 'user-error))
            (should (equal before (gnosis-test-study-view-snapshot)))))))))

(ert-deftest gnosis-study-nodes-depth-rechecks-before-confirmation ()
  (gnosis-test-study
    (let ((gnosis-dashboard-buffer-name " *Gnosis node ownership*"))
      (gnosis-test-study-view-fixture "Displayed")
      (gnosis-test-study-nodes-open)
      (let ((before (gnosis-test-study-view-snapshot)))
        (cl-letf (((symbol-function 'read-number)
                   (lambda (&rest _) (gnosis-dashboard-nodes-refresh) 0))
                  ((symbol-function 'y-or-n-p)
                   (lambda (&rest _) (ert-fail "Retired depth prompt launched confirmation"))))
          (should-error (call-interactively (key-binding (kbd "R")))
                        :type 'user-error))
        (should (equal before (gnosis-test-study-view-snapshot)))))))

(ert-deftest gnosis-study-nodes-launch-rechecks-after-setup-hooks ()
  (gnosis-test-study
    (let ((gnosis-dashboard-buffer-name " *Gnosis node ownership*"))
      (gnosis-test-study-view-fixture "Displayed")
      (gnosis-test-study-summary '(43 42) 'practice)
      ;; Force the replacement's normal major-mode hook to run.
      (kill-buffer gnosis-review-buffer-name)
      (gnosis-test-study-nodes-open)
      (let* ((owner (current-buffer))
             (before (gnosis-test-study-view-snapshot))
             (gnosis-mode-hook
              (list (lambda ()
                      (with-current-buffer owner (gnosis-dashboard-nodes-refresh))))))
        (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t))
                  ((symbol-function 'gnosis-review--run-state)
                   (lambda (_ state) state)))
          (should-error (call-interactively (key-binding (kbd "p")))
                        :type 'user-error))
        (should (equal before (gnosis-test-study-view-snapshot)))))))

(ert-deftest gnosis-study-nodes-owned-launch-and-cancel ()
  (dolist (key '("p" "r" "a" "R"))
    (dolist (answer '(nil quit t))
      (gnosis-test-study
        (let ((gnosis-dashboard-buffer-name " *Gnosis node ownership*"))
          (gnosis-test-study-view-fixture "Displayed")
          (gnosis-test-study-summary '(43 42) 'practice)
          (gnosis-test-study-nodes-open)
          (setq gnosis-dashboard--selected-ids '("topic"))
          (let ((before (gnosis-test-study-view-snapshot))
                (old (gnosis-review-state-session-id (gnosis-review--read-session))))
            (cl-letf (((symbol-function 'read-number) (lambda (&rest _) 0))
                      ((symbol-function 'y-or-n-p)
                       (lambda (&rest _) (if (eq answer 'quit) (signal 'quit nil) answer)))
                      ((symbol-function 'gnosis-review--run-state)
                       (lambda (_ state) state)))
              (if (eq answer 'quit)
                  (should (eq 'cancelled
                              (condition-case nil
                                  (call-interactively (key-binding (kbd key)))
                                (quit 'cancelled))))
                (call-interactively (key-binding (kbd key)))))
            (if (eq answer t)
                (progn
                  (should (equal '(42) (gnosis-review-state-selected (gnosis-review--read-session))))
                  (should (plist-get (gnosis-get 'data 'study-history `(= session-id ,old))
                                     :cancelled-p)))
              (should (equal before (gnosis-test-study-view-snapshot))))))))))


(ert-deftest gnosis-study-nodes-marked-membership-and-input-preservation ()
  (dolist (key '("p" "r"))
    (gnosis-test-study
      (let ((gnosis-dashboard-buffer-name " *Gnosis node ownership*"))
        (gnosis-test-study-view-fixture "Displayed")
        (gnosis-test-study-node "second" "Second")
        (gnosis--insert-into 'thema-links '([43 "second"]))
        (gnosis-test-study-nodes-open)
        (let* ((selected (list "topic" "second"))
               (original (copy-tree selected)))
          (setq gnosis-dashboard--selected-ids selected)
          (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t))
                    ((symbol-function 'gnosis-review--run-state)
                     (lambda (_ state) state)))
            (call-interactively (key-binding (kbd key))))
          (should (equal '(42 43)
                         (sort (copy-sequence
                                (gnosis-review-state-selected (gnosis-review--read-session))) #'<)))
          (should (equal original selected)))))))

(ert-deftest gnosis-study-nodes-explicit-refresh-adopts-current-database ()
  (gnosis-test-study
    (let ((gnosis-dashboard-buffer-name " *Gnosis node ownership*"))
      (gnosis-test-study-view-fixture "A displayed")
      (gnosis-test-study-nodes-open)
      (gnosis-test-with-db
        (gnosis-test-study-view-fixture "B refreshed")
        (call-interactively (key-binding (kbd "g")))
        (goto-char (point-min))
        (should (string-match-p "B refreshed" (buffer-string)))
        (call-interactively (key-binding (kbd "S")))
        (should (eq major-mode 'gnosis-study-mode))
        (should (string-match-p "B refreshed" (buffer-string)))
        (should (eq (cdr gnosis-study--owner) gnosis-db))))))


(defun gnosis-test-study-action-owner-case (mode action boundary)
  "Exercise MODE ACTION after database replacement at BOUNDARY.
Use real pending answers and writers with accepted evidence in both databases."
  (gnosis-test-study
    (gnosis-test-study-view-fixture "A encountered")
    (gnosis-study-flag 42 t)
    (gnosis-test-study-summary '(42 43) 'due)
    (gnosis-test-study-summary '(42 43) 'practice)
    (let ((original gnosis-db) (directory gnosis-dir)
          (gnosis-review-basic-input 'typed))
      (gnosis-test-with-db
        (gnosis-test-study-view-fixture "B unrelated")
        (gnosis-study-flag 42 t)
        (gnosis-test-study-summary '(42 43) 'due)
        (gnosis-test-study-summary '(42 43) 'practice)
        (let ((other gnosis-db) (other-directory gnosis-dir)
              (other-before (gnosis-test-study-view-snapshot)) before termination)
          (let ((gnosis-db original) (gnosis-dir directory))
            (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                       (lambda (&rest _) "Answer"))
                      ((symbol-function 'read-char-choice)
                       (lambda (&rest _)
                         (if before (signal 'quit nil)
                           (setq before (gnosis-test-study-view-snapshot))
                           (when (eq boundary 'action)
                             (setq gnosis-db other gnosis-dir other-directory))
                           action)))
                      ((symbol-function 'y-or-n-p)
                       (lambda (&rest _)
                         (when (eq boundary 'confirmation)
                           (setq gnosis-db other gnosis-dir other-directory))
                         t)))
              (condition-case err (gnosis-review-loop '(42) mode)
                ((error quit) (setq termination (car err))))))
          (should before)
          (should (equal other-before (gnosis-test-study-view-snapshot)))
          (let ((gnosis-db original) (gnosis-dir directory))
            (should (equal before (gnosis-test-study-view-snapshot)))
            (should (equal '(42) (gnosis-review-state-remaining (gnosis-review--read-session)))))
          (should (memq termination '(user-error gnosis-review-content-changed))))))))

(ert-deftest gnosis-study-action-delete-rejects-foreign-owner ()
  (dolist (mode '(due practice))
    (dolist (boundary '(action confirmation))
      (gnosis-test-study-action-owner-case mode ?d boundary))))

(ert-deftest gnosis-study-action-suspend-rejects-foreign-owner ()
  (dolist (mode '(due practice))
    (dolist (boundary '(action confirmation))
      (gnosis-test-study-action-owner-case mode ?s boundary))))

(ert-deftest gnosis-study-action-flag-rejects-foreign-owner ()
  (dolist (mode '(due practice))
    (gnosis-test-study-action-owner-case mode ?f 'action)))

(ert-deftest gnosis-study-action-owned-mutations-and-cancel ()
  (dolist (mode '(due practice))
    (dolist (action '(?d ?s ?f))
      (dolist (answer (if (= action ?f) '(t) '(nil quit t)))
        (gnosis-test-study
          (gnosis-test-study-view-fixture "Encountered")
          (gnosis-study-flag 42 t)
          (let ((gnosis-review-basic-input 'typed) before)
            (cl-letf (((symbol-function 'gnosis--read-string-with-input-method)
                       (lambda (&rest _) "Answer"))
                      ((symbol-function 'read-char-choice)
                       (lambda (&rest _)
                         (if before (signal 'quit nil)
                           (setq before (gnosis-test-study-view-snapshot)) action)))
                      ((symbol-function 'y-or-n-p)
                       (lambda (&rest _) (if (eq answer 'quit) (signal 'quit nil) answer))))
              (condition-case nil (gnosis-review-loop '(42) mode) (quit nil)))
            (if (not (eq answer t))
                (should (equal before (gnosis-test-study-view-snapshot)))
              (pcase action
                (?d (should-not (gnosis-get 'id 'themata '(= id 42)))
                    (should (equal '(42) (gnosis-review-state-skipped (gnosis-review--read-session)))))
                (?s (should (gnosis-suspended-p 42)))
                (?f (should (member "needs_work" (gnosis-get-tags-for-ids '(42)))))))
            (should (gnosis-get 'id 'themata '(= id 43)))
            (should-not (gnosis-select '* 'review-events))
            (should-not (gnosis-select '* 'practice-events))))))))


(ert-deftest gnosis-study-action-delete-rechecks-final-confirmation ()
  (dolist (mode '(due practice))
    (gnosis-test-study-action-owner-case mode ?d 'confirmation)))

(ert-deftest gnosis-study-action-suspend-rechecks-final-confirmation ()
  (dolist (mode '(due practice))
    (gnosis-test-study-action-owner-case mode ?s 'confirmation)))

(provide 'gnosis-test-study)
;;; gnosis-test-study.el ends here
