;;; gnosis-test-session-replacement.el --- Batch replacement -*- lexical-binding: t; -*-

(require 'ert)
(require 'gnosis-agent)
(require 'gnosis-test-helpers)

(defmacro gnosis-test-replacement (&rest body)
  "Run BODY with disposable study data, buffers and captured agent timers."
  (declare (indent 0) (debug t))
  `(gnosis-test-with-db
     (let ((buffers (buffer-list))
           (gnosis-review-buffer-name "*Gnosis Replacement Test*")
           (gnosis-review--running nil)
           (gnosis-agent--launches nil)
           (gnosis-center-content nil)
           (register-alist nil))
       (save-window-excursion
         (unwind-protect
             (cl-letf (((symbol-function 'gnosis-review--run-state)
                        (lambda (_buffer state) state))
                       ((symbol-function 'run-with-timer) (lambda (&rest _) nil)))
               (gnosis-test--add-basic-thema "A" "a" nil nil 101)
               (gnosis-test--add-basic-thema "B" "b" nil nil 102)
               (gnosis-test--add-basic-thema "C" "c" nil nil 103)
               ,@body)
           (mapc #'gnosis-agent--release (copy-sequence gnosis-agent--launches))
           (dolist (buffer (seq-difference (buffer-list) buffers))
             (when (buffer-live-p buffer) (kill-buffer buffer))))))))

(defun gnosis-test-replacement-start (mode ids)
  "Start MODE with IDS through its native entry point."
  (if (eq mode 'agent)
      (gnosis-agent-start-practice :thema-ids ids :limit (length ids))
    (gnosis-review-loop ids mode))
  (gnosis-review--read-session))

(defun gnosis-test-replacement-evidence ()
  "Snapshot scheduling and accepted practice evidence."
  (mapcar (lambda (table) (gnosis-select '* table))
          '(scheduler-config scheduler-active scheduler-baseline scheduler-state
            review-events review-voids review-activity-baseline
            practice-events practice-voids)))

(ert-deftest gnosis-replacement-preserves-evidence-and-ends-old-batch ()
  (dolist (old-mode '(due practice agent))
    (dolist (new-mode '(due practice agent))
      (gnosis-test-replacement
        (gnosis-test-replacement-start 'due '(103))
        (let ((gnosis-review--state (gnosis-review--read-session)))
          (gnosis-review-result 103 t (gnosis-review-algorithm 103 t)))
        (let* ((old (gnosis-test-replacement-start old-mode '(101 102)))
               (id (gnosis-review-state-session-id old)))
          (let ((gnosis-review--state old))
            (gnosis-review-result 101 nil (gnosis-review-algorithm 101 nil)))
          ;; Resume remains available until an actual replacement succeeds.
          (gnosis-review-resume)
          (let* ((before (gnosis-review--state-data (gnosis-review--read-session)))
                 (evidence (gnosis-test-replacement-evidence))
                 (next (gnosis-test-replacement-start new-mode '(103)))
                 (history (gnosis-get 'data 'study-history `(= session-id ,id))))
            (should-not (equal id (gnosis-review-state-session-id next)))
            (should (equal '(103) (gnosis-review-state-remaining next)))
            (should (plist-get history :cancelled-p))
            (should-not (plist-get history :launch-token))
            ;; Historical remaining membership is evidence, not an active queue.
            (should (equal (plist-get before :remaining) (plist-get history :remaining)))
            (should (equal (plist-get before :outcomes) (plist-get history :outcomes)))
            (should (equal evidence (gnosis-test-replacement-evidence)))
            (when (eq old-mode 'agent)
              (should (equal "cancelled" (plist-get (gnosis-agent-status id) :status)))
              (should-error (gnosis-agent-resume id) :type 'user-error))))))))

(ert-deftest gnosis-replacement-continue-dispatches-new-batch ()
  (gnosis-test-replacement
    (let ((old (gnosis-test-replacement-start 'practice '(101 102))))
      (gnosis-review--show-summary old)
      (should (eq #'gnosis-review-continue (key-binding (kbd "c"))))
      (cl-letf (((symbol-function 'keymap-popup)
                 (lambda (map &rest _)
                   ;; Exercise the public review menu's actual due binding.
                   (with-temp-buffer
                     (use-local-map map)
                     (call-interactively (key-binding (kbd "d"))))))
                ((symbol-function 'gnosis-review--selection-ids)
                 (lambda (selection) (should (equal selection '(due))) '(103))))
        (call-interactively (key-binding (kbd "c"))))
      (should (equal '(103) (gnosis-review-state-remaining (gnosis-review--read-session))))
      (should (plist-get (gnosis-get 'data 'study-history
                                    `(= session-id ,(gnosis-review-state-session-id old)))
                         :cancelled-p)))))

(ert-deftest gnosis-replacement-empty-keeps-visible-summary-resumable ()
  (let ((run-state (symbol-function 'gnosis-review--run-state)))
    (gnosis-test-replacement
      (let* ((old (gnosis-test-replacement-start 'practice '(101 102)))
             (review-buffer (get-buffer gnosis-review-buffer-name))
             (review-state (buffer-local-value 'gnosis-review--state review-buffer)))
        (gnosis-review--show-summary old)
        (let ((summary (current-buffer))
              (text (buffer-string))
              (target gnosis-review--summary-target))
          ;; Do not mock presentation here: an accidental empty run used to
          ;; select an ephemeral summary whose Resume command had no owner.
          (cl-letf (((symbol-function 'gnosis-review--run-state) run-state))
            (dolist (mode '(due practice))
              (should-not (gnosis-review-loop '(999) mode))))
          (should (eq summary (current-buffer)))
          (should (equal text (buffer-string)))
          (should (equal target gnosis-review--summary-target))
          (should (eq review-state (buffer-local-value 'gnosis-review--state review-buffer)))
          (call-interactively (key-binding (kbd "r")))
          (should (equal (gnosis-review-state-session-id old)
                         (gnosis-review-state-session-id (gnosis-review--read-session)))))))))

(ert-deftest gnosis-replacement-selection-failure-and-empty-preserve-current ()
  (gnosis-test-replacement
    (gnosis-test-replacement-start 'agent '(101 102))
    (let ((before (gnosis-review--state-data (gnosis-review--read-session)))
          (launches (copy-sequence gnosis-agent--launches))
          (evidence (gnosis-test-replacement-evidence)))
      (dolist (mode '(due practice))
        (dolist (failure '(error quit))
          (let (caught)
            (condition-case err
                (gnosis-review-loop (lambda () (signal failure '("Selection stopped"))) mode)
              ((error quit) (setq caught (car err))))
            (should (eq failure caught))))
        (gnosis-review-loop '(999) mode))
      (should-error (gnosis-agent-start-practice :thema-ids '(101) :limit 1
                                               :policy '(:successes-required 0)))
      (should-error (gnosis-agent-start-practice :topic-ids '("unknown") :limit 1))
      (let ((status (gnosis-agent-start-practice :thema-ids '(999) :limit 3)))
        (should (equal "completed" (plist-get status :status)))
        (should (= 3 (plist-get (plist-get status :selection) :shortfall)))
        (should (equal [] (plist-get status :selected-ids))))
      (should (equal before (gnosis-review--state-data (gnosis-review--read-session))))
      (should (equal launches gnosis-agent--launches))
      (should (equal evidence (gnosis-test-replacement-evidence)))
      (gnosis-review--show-summary (gnosis-review--read-session))
      (let (opened)
        (cl-letf (((symbol-function 'keymap-popup)
                   (lambda (&rest _) (setq opened t) (signal 'quit nil))))
          (condition-case nil (call-interactively (key-binding (kbd "c"))) (quit nil)))
        (should opened))
      (should (equal before (gnosis-review--state-data (gnosis-review--read-session))))
      (call-interactively (key-binding (kbd "r")))
      (should (equal (plist-get before :session-id)
                     (gnosis-review-state-session-id (gnosis-review--read-session)))))))

(ert-deftest gnosis-replacement-rollback-keeps-history-checkpoint-and-launch ()
  (dolist (mode '(due practice agent))
    (dolist (failure '(error quit))
      (gnosis-test-replacement
        (gnosis-test-replacement-start 'agent '(101 102))
        (let ((gnosis-review--state (gnosis-review--read-session)))
          (gnosis-review-result 101 nil (gnosis-review-algorithm 101 nil)))
        (let* ((before (gnosis-review--state-data (gnosis-review--read-session)))
               (id (plist-get before :session-id))
               (history (gnosis-select '* 'study-history))
               (launches (copy-sequence gnosis-agent--launches))
               (evidence (gnosis-test-replacement-evidence))
               (save (symbol-function 'gnosis-review--save-history))
               caught retired)
          (cl-letf (((symbol-function 'gnosis-review--save-history)
                     (lambda (state)
                       (funcall save state)
                       (if (equal id (gnosis-review-state-session-id state))
                           (setq retired t)
                         ;; Fail after both historical retirement and new insertion.
                         (signal failure '("Replacement disk fault"))))))
            (condition-case err (gnosis-test-replacement-start mode '(103))
              ((error quit) (setq caught (car err)))))
          (should retired)
          (should (eq failure caught))
          (should (equal before (gnosis-review--state-data (gnosis-review--read-session))))
          (should (equal history (gnosis-select '* 'study-history)))
          (should (equal launches gnosis-agent--launches))
          (should (equal evidence (gnosis-test-replacement-evidence))))))))

(ert-deftest gnosis-replacement-invalidates-pending-launch-and-stale-actions ()
  (dolist (mode '(due practice agent))
    (gnosis-test-replacement
      (let* ((old (gnosis-test-replacement-start 'agent '(101 102)))
             (record (car gnosis-agent--launches))
             (pending (let ((gnosis-review--state old)) (gnosis-review-algorithm 101 t))))
        (gnosis-review--show-summary old)
        (let ((summary (current-buffer)))
          (gnosis-test-replacement-start mode '(103))
          (let ((before (gnosis-review--state-data (gnosis-review--read-session)))
                (evidence (gnosis-test-replacement-evidence))
                launched)
            (cl-letf (((symbol-function 'gnosis-review--resume)
                       (lambda (&rest _) (setq launched t))))
              (gnosis-agent--launch record))
            (should-not launched)
            (with-current-buffer summary
              (dolist (key '("r" "d" "u"))
                (should-error (call-interactively (key-binding (kbd key))) :type 'user-error)))
            (let ((gnosis-review--state old))
              (should-error (gnosis-review-result 101 t pending)))
            (gnosis-update 'scheduler-state '(= suspended 1) '(= thema-id 101))
            (should-error (gnosis-review--skip old 101) :type 'user-error)
            (gnosis-update 'scheduler-state '(= suspended 0) '(= thema-id 101))
            (should (equal before (gnosis-review--state-data (gnosis-review--read-session))))
            (should (equal evidence (gnosis-test-replacement-evidence)))
            (gnosis-sqlite-close gnosis-db)
            (setq gnosis-db (gnosis-sqlite-open gnosis-test--db-file))
            (should (equal before (gnosis-review--state-data (gnosis-review--read-session))))
            (should (equal "cancelled"
                           (plist-get (gnosis-agent-status (gnosis-review-state-session-id old))
                                      :status)))))))))

(ert-deftest gnosis-replacement-rechecks-owner-after-selection-and-setup ()
  (gnosis-test-replacement
    (gnosis-test-replacement-start 'practice '(101 102))
    (let ((setup (symbol-function 'gnosis-review--setup-buffer)) successor)
      (cl-letf (((symbol-function 'gnosis-review--setup-buffer)
                 (lambda (&rest args)
                   (let ((state (gnosis-review--read-session)))
                     (setf (gnosis-review-state-launch-token state) "intervening-owner")
                     (gnosis-review--save-session state)
                     (setq successor (gnosis-review--state-data state)))
                   (apply setup args))))
        (should-error (gnosis-review-loop '(103)) :type 'user-error))
      (should (equal successor (gnosis-review--state-data (gnosis-review--read-session)))))
    (let ((eligible (symbol-function 'gnosis-study--eligible-ids)) successor)
      (cl-letf (((symbol-function 'gnosis-study--eligible-ids)
                 (lambda (&rest args)
                   (let ((state (gnosis-review--read-session)))
                     (setf (gnosis-review-state-launch-token state) "agent-selection-drift")
                     (gnosis-review--save-session state)
                     (setq successor (gnosis-review--state-data state)))
                   (apply eligible args))))
        (should-error (gnosis-agent-start-practice :thema-ids '(103) :limit 1) :type 'user-error))
      (should (equal successor (gnosis-review--state-data (gnosis-review--read-session)))))))

(ert-deftest gnosis-replacement-rechecks-database-after-collector ()
  (gnosis-test-replacement
    (gnosis-test-replacement-start 'practice '(101 102))
    (let* ((original gnosis-db)
           (before (gnosis-review--state-data (gnosis-review--read-session)))
           (file (make-temp-file "gnosis-replacement-other-"))
           (other (gnosis-sqlite-open file)))
      (unwind-protect
          (progn
            (let ((gnosis-db other))
              (gnosis-db-init)
              (gnosis-test--add-basic-thema "Other" "a" nil nil 103))
            (should-error (gnosis-review-loop (lambda () (setq gnosis-db other) '(103)))
                          :type 'user-error)
            (should-not (gnosis-review--read-session))
            (setq gnosis-db original)
            (should (equal before (gnosis-review--state-data (gnosis-review--read-session)))))
        (setq gnosis-db original)
        (gnosis-sqlite-close other)
        (delete-file file)))))

(ert-deftest gnosis-replacement-refuses-active-input ()
  (gnosis-test-replacement
    (gnosis-test-replacement-start 'agent '(101 102))
    (let ((before (gnosis-review--state-data (gnosis-review--read-session)))
          (gnosis-review--running "active"))
      (dolist (mode '(due practice agent))
        (should-error (gnosis-test-replacement-start mode '(103)) :type 'user-error))
      (should-error (call-interactively #'gnosis-review-continue) :type 'user-error)
      (should (equal before (gnosis-review--state-data (gnosis-review--read-session)))))))

(defun gnosis-test-replacement-dispatch (key)
  "Invoke KEY through the public review map."
  (with-temp-buffer
    (use-local-map gnosis-review-map)
    (call-interactively (key-binding (kbd key)))))

(ert-deftest gnosis-replacement-public-tag-prompt-keeps-successor ()
  (dolist (key '("t" "T"))
    (gnosis-test-replacement
      (gnosis-test-replacement-start 'agent '(101 102))
      (let (successor evidence)
        (cl-letf (((symbol-function 'completing-read-multiple)
                   (lambda (&rest _)
                     (gnosis-test-replacement-start 'agent '(102))
                     (setq successor (gnosis-review--state-data (gnosis-review--read-session))
                           evidence (gnosis-test-replacement-evidence))
                     '("+test"))))
          (should-error (gnosis-test-replacement-dispatch key) :type 'user-error))
        (should (equal successor (gnosis-review--state-data (gnosis-review--read-session))))
        (should (equal evidence (gnosis-test-replacement-evidence)))
        (should-not (plist-get (gnosis-get 'data 'study-history
                                          `(= session-id ,(plist-get successor :session-id)))
                               :cancelled-p))))))

(ert-deftest gnosis-replacement-public-selection-callback-keeps-successor ()
  (dolist (key '("d" "o" "w"))
    (gnosis-test-replacement
      (gnosis-test-replacement-start 'practice '(101 102))
      (let (successor)
        (cl-letf (((symbol-function 'gnosis-review--selection-ids)
                   (lambda (_)
                     (gnosis-test-replacement-start 'agent '(102))
                     (setq successor (gnosis-review--state-data (gnosis-review--read-session)))
                     '(103))))
          (should-error (gnosis-test-replacement-dispatch key) :type 'user-error))
        (should (equal successor (gnosis-review--state-data (gnosis-review--read-session))))))))

(ert-deftest gnosis-replacement-public-topic-confirmation-keeps-successor ()
  (dolist (command '(gnosis-practice-topic gnosis-review-due-topic gnosis-review-topic))
    (gnosis-test-replacement
      (gnosis--insert-into 'nodes '(["node" "fixture.org" "Topic" "1" nil nil nil]))
      (gnosis--insert-into 'thema-links '([103 "node"]))
      (gnosis-test-replacement-start 'agent '(101 102))
      (let (successor evidence)
        (cl-letf (((symbol-function 'y-or-n-p)
                   (lambda (&rest _)
                     (gnosis-test-replacement-start 'agent '(102))
                     (setq successor (gnosis-review--state-data (gnosis-review--read-session))
                           evidence (gnosis-test-replacement-evidence))
                     t)))
          (should-error (funcall command (if (eq command 'gnosis-review-topic)
                                            "node" '("node")))
                        :type 'user-error))
        (should (equal successor (gnosis-review--state-data (gnosis-review--read-session))))
        (should (equal evidence (gnosis-test-replacement-evidence)))))))

(ert-deftest gnosis-replacement-public-topic-input-keeps-successor ()
  (dolist (command '(gnosis-practice-topic gnosis-review-due-topic gnosis-review-topic
                     gnosis-dashboard-nodes-review-with-depth))
    (dolist (stage '(topic depth))
      (gnosis-test-replacement
        (require 'gnosis-dashboard)
        (gnosis--insert-into 'nodes '(["node" "fixture.org" "Topic" "1" nil nil nil]))
        (gnosis--insert-into 'thema-links '([103 "node"]))
        (gnosis-test-replacement-start 'agent '(101 102))
        (when (eq command 'gnosis-dashboard-nodes-review-with-depth)
          (gnosis-dashboard-output-nodes '("node"))
          (goto-char (point-min)))
        (let ((current-prefix-arg '(4)) successor)
          (cl-labels ((replace-once ()
                        (unless successor
                          (gnosis-test-replacement-start 'agent '(102))
                          (setq successor (gnosis-review--state-data
                                           (gnosis-review--read-session))))))
            (cl-letf (((symbol-function 'read-number)
                       (lambda (&rest _)
                         (when (or (eq stage 'depth)
                                   (eq command 'gnosis-dashboard-nodes-review-with-depth))
                           (replace-once))
                         0))
                      ((symbol-function 'completing-read-multiple)
                       (lambda (&rest _) (when (eq stage 'topic) (replace-once)) '("Topic")))
                      ((symbol-function 'gnosis-completing-read)
                       (lambda (&rest _) (when (eq stage 'topic) (replace-once)) "Topic"))
                      ((symbol-function 'tabulated-list-get-id) (lambda () "node"))
                      ((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
              (should-error (call-interactively command) :type 'user-error)))
          (should successor)
          (should (equal successor (gnosis-review--state-data (gnosis-review--read-session)))))))))

(ert-deftest gnosis-replacement-public-prompts-keep-database-owner ()
  (dolist (key '("T" "p" "n" "a"))
    (gnosis-test-replacement
      (gnosis--insert-into 'nodes '(["node" "fixture.org" "Topic" "1" nil nil nil]))
      (gnosis--insert-into 'thema-links '([103 "node"]))
      (gnosis-test-replacement-start 'practice '(101 102))
      (let* ((original gnosis-db)
             (before (gnosis-review--state-data (gnosis-review--read-session)))
             (file (make-temp-file "gnosis-public-prompt-other-"))
             (other (gnosis-sqlite-open file)))
        (unwind-protect
            (progn
              (let ((gnosis-db other))
                (gnosis-db-init)
                (gnosis-test--add-basic-thema "Other" "a" nil nil 103))
              (cl-letf (((symbol-function 'completing-read-multiple)
                         (lambda (&rest _)
                           (if (equal key "T") (progn (setq gnosis-db other) '("+test"))
                             '("Topic"))))
                        ((symbol-function 'gnosis-completing-read) (lambda (&rest _) "Topic"))
                        ((symbol-function 'y-or-n-p)
                         (lambda (&rest _) (setq gnosis-db other) t)))
                (should-error (gnosis-test-replacement-dispatch key) :type 'user-error))
              (should-not (gnosis-review--read-session))
              (setq gnosis-db original)
              (should (equal before (gnosis-review--state-data (gnosis-review--read-session)))))
          (setq gnosis-db original)
          (gnosis-sqlite-close other)
          (delete-file file))))))

(provide 'gnosis-test-session-replacement)
;;; gnosis-test-session-replacement.el ends here
