;;; gnosis-test-image-drafts.el --- Complete media draft ownership -*- lexical-binding: t; -*-
(require 'ert)
(require 'gnosis-image-test-support)
(require 'gnosis-model-test-support)

(defun gnosis-test-image-drafts-clean ()
  (when-let* ((b (get-buffer "*Gnosis Edit*")))
    (with-current-buffer b (set-buffer-modified-p nil)) (kill-buffer b)))
(defun gnosis-test-image-drafts-evidence ()
  (mapcar (lambda (table) (sqlite-select gnosis-db (format "SELECT * FROM %s ORDER BY 1" table)))
          '(scheduler_baseline scheduler_state review_events review_voids practice_events
            practice_voids study_session study_history)))
(defun gnosis-test-image-drafts-rows ()
  (cons (mapcar (lambda (table) (sqlite-select gnosis-db (format "SELECT * FROM %s ORDER BY 1" table)))
                '(themata extras thema_tag thema_links)) (gnosis-test-image-drafts-evidence)))
(defun gnosis-test-image-drafts-fixture (type)
  (let* ((image (string-prefix-p "image" type))
         (source (if image (gnosis-test-image--file) (gnosis-test-model-targets--fixture)))
         (reference (if image (gnosis-image-import source gnosis-test-image--regions)
                      (gnosis-model-import source)))
         (name (member type '("image-occlusion" "model-name")))
         (hypothesis (pcase type
                       ("image-region" (list reference))
                       ("image-occlusion" (list reference "left" "hide-all"))
                       ("model" (list reference "0" "0" "1"))
                       ("model-name" (list reference "whole" "0" "0" "1"))))
         (answer (if name "Authored answer" (if image "left" "whole"))))
    (gnosis-add-thema-fields type "Question" hypothesis (list answer) "Hidden explanation"
                            '("test") 0 nil nil 12345 (and name '("Hidden alias")))
    (gnosis-scheduler-accept-review (make-string 64 ?a) 12345 'success 1000000 (gnosis--today-int))
    (sqlite-execute gnosis-db "INSERT INTO practice_events VALUES ('practice', 12345, 'session', 1, 1000000, 3)")
    (list source reference)))
(defun gnosis-test-image-drafts-attach (type)
  (should (eq (key-binding (kbd "C-c C-a"))
              (if (string-prefix-p "image" type) 'gnosis-image-attach 'gnosis-model-attach)))
  (execute-kbd-macro (kbd (if (string-prefix-p "image" type) "C-c C-a" "C-u C-c C-a"))))
(defun gnosis-test-image-drafts-save-reopen ()
  (should (eq (key-binding (kbd "C-c C-c")) 'gnosis-save))
  (execute-kbd-macro (kbd "C-c C-c"))
  (gnosis-sqlite-close gnosis-db)
  (setq gnosis-db (gnosis-db--open gnosis-dir))
  (gnosis-edit-thema 12345))
(defmacro gnosis-test-image-drafts-input (&rest body)
  `(cl-letf (((symbol-function 'read-number) (lambda (_ initial) initial))
             ((symbol-function 'completing-read)
              (lambda (prompt choices &rest _)
                (if (string-prefix-p "Label visibility" prompt) "hide-all" (caar choices))))
             ((symbol-function 'gnosis-image-edit-regions)
              (lambda (_) (copy-tree gnosis-test-image--regions))))
     ,@body))

(ert-deftest gnosis-test-image-drafts-b3-hidden-fields-preserved ()
  (dolist (type '("image-region" "image-occlusion" "model" "model-name"))
    (dolist (narrow '(nil fields partial))
      (gnosis-test-with-db
        (save-window-excursion
          (let* ((fixture (gnosis-test-image-drafts-fixture type)) (reference (cadr fixture))
                 (evidence (gnosis-test-image-drafts-evidence)) (gnosis-save-hook nil))
            (unwind-protect
                (progn
                  (gnosis-edit-thema 12345)
                  (let ((before (car (gnosis-export-parse-themata))))
                    (when narrow
                      (goto-char (point-min)) (search-forward "** Parathema") (beginning-of-line)
                      (narrow-to-region (if (eq narrow 'partial)
                                            (save-excursion (goto-char (point-min))
                                                            (search-forward "Question") (- (point) 4))
                                          (point-min))
                                        (point)))
                    (let ((draft (save-restriction (widen) (buffer-string)))
                          (rows (gnosis-test-image-drafts-rows))
                          (resources (directory-files (gnosis-assets-root)))
                          (restriction (cons (point-min) (point-max))))
                      (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) (signal 'quit nil))))
                        (should (eq 'quit (condition-case nil
                                              (gnosis-test-image-drafts-attach type)
                                            (quit 'quit)))))
                      (should (equal-including-properties draft (save-restriction (widen) (buffer-string))))
                      (should (equal restriction (cons (point-min) (point-max))))
                      (should (equal rows (gnosis-test-image-drafts-rows)))
                      (should (equal resources (directory-files (gnosis-assets-root)))))
                    (gnosis-test-image-drafts-input
                     (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t))
                               ((symbol-function 'read-string) (lambda (_ initial &rest _) initial)))
                       (gnosis-test-image-drafts-attach type)))
                    (widen)
                    (let ((after (car (gnosis-export-parse-themata))))
                      (should (equal (nth 3 before) (nth 3 after)))
                      (should (equal (nth 4 before) (nth 4 after)))
                      (should (equal (nth 5 after) "Hidden explanation"))
                      (when (member type '("image-occlusion" "model-name"))
                        (should (equal (nth 8 after) '("Hidden alias")))))
                    (gnosis-test-image-drafts-save-reopen)
                    (should (equal (gnosis-get 'parathema 'extras '(= id 12345))
                                   "Hidden explanation"))
                    (when (member type '("image-occlusion" "model-name"))
                      (should (equal (gnosis-get 'accepted-aliases 'themata '(= id 12345))
                                     '("Hidden alias"))))
                    (should (equal reference (car (gnosis-get 'hypothesis 'themata '(= id 12345)))))
                    (should (equal evidence (gnosis-test-image-drafts-evidence)))
                    (message "EXTRA B3 %s narrowed=%S: reopened parathema=%S aliases=%S; reference, answer and nonempty evidence preserved"
                             type narrow (gnosis-get 'parathema 'extras '(= id 12345))
                             (gnosis-get 'accepted-aliases 'themata '(= id 12345)))))
              (gnosis-test-image-drafts-clean))))))))

(ert-deftest gnosis-test-image-drafts-b3-hidden-second-thema-refused ()
  (dolist (type '("image-region" "model"))
    (gnosis-test-with-db
      (save-window-excursion
        (let ((gnosis-save-hook nil))
          (gnosis-test-image-drafts-fixture type)
          (unwind-protect
              (progn
                (gnosis-edit-thema 12345)
                (let ((end (point-max)) (rows (gnosis-test-image-drafts-rows)) before)
                  (gnosis-export--insert-thema "NEW" "basic" "Hidden second question" nil "Answer" "Second explanation")
                  (should (= 2 (length (gnosis-export-parse-themata))))
                  (setq before (buffer-string))
                  (narrow-to-region (point-min) end)
                  (gnosis-test-image-drafts-input
                   (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t))
                             ((symbol-function 'read-string) (lambda (_ initial &rest _) initial)))
                     (should-error (gnosis-test-image-drafts-attach type))))
                  (widen)
                  (should (equal-including-properties before (buffer-string)))
                  (should (= 2 (length (gnosis-export-parse-themata))))
                  (should (string-match-p "Hidden second question" (buffer-string)))
                  (should (equal rows (gnosis-test-image-drafts-rows)))
                  (message "EXTRA B3 %s: hidden second unsaved thema preserved by refused native attachment; persisted rows unchanged before save" type)))
            (gnosis-test-image-drafts-clean)))))))

(ert-deftest gnosis-test-image-drafts-b4-missing-old-repair-and-controls ()
  (dolist (type '("image-region" "image-occlusion" "model-name" "model"))
    (dolist (missing '(nil missing corrupt))
      (gnosis-test-with-db
        (save-window-excursion
          (let* ((fixture (gnosis-test-image-drafts-fixture type))
                 (file (car fixture)) (reference (cadr fixture))
                 (evidence (gnosis-test-image-drafts-evidence))
                 (gnosis-save-hook nil) prompted decision)
            (unwind-protect
                (progn
                  (pcase missing
                    ('missing (delete-file (expand-file-name reference (gnosis-assets-root))))
                    ('corrupt (with-temp-file (expand-file-name reference (gnosis-assets-root))
                                (insert "corrupt"))))
                  (gnosis-edit-thema 12345)
                  (gnosis-test-image-drafts-input
                   (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) (setq decision t) nil))
                             ((symbol-function 'read-file-name) (lambda (&rest _) (setq prompted t) file))
                             ((symbol-function 'read-string) (lambda (&rest _) "Distinct replacement metadata")))
                     (gnosis-test-image-drafts-attach type)))
                  (should decision)
                  (should prompted)
                  (let ((new (car (nth 3 (car (gnosis-export-parse-themata))))))
                    (should-not (equal new reference))
                    (gnosis-test-image-drafts-save-reopen)
                    (should (equal new (car (gnosis-get 'hypothesis 'themata '(= id 12345)))))
                    (should (equal "Hidden explanation" (gnosis-get 'parathema 'extras '(= id 12345))))
                    (when (member type '("model-name" "image-occlusion"))
                      (should (equal '("Authored answer") (gnosis-get 'answer 'themata '(= id 12345))))
                      (should (equal '("Hidden alias") (gnosis-get 'accepted-aliases 'themata '(= id 12345)))))
                    (should (equal evidence (gnosis-test-image-drafts-evidence)))))
              (gnosis-test-image-drafts-clean))))))))

(ert-deftest gnosis-test-image-drafts-unavailable-refusal-and-cancel ()
  (dolist (type '("image-region" "image-occlusion" "model" "model-name"))
    (gnosis-test-with-db
      (save-window-excursion
        (let* ((fixture (gnosis-test-image-drafts-fixture type))
               (reference (cadr fixture)) (gnosis-save-hook nil))
          (unwind-protect
              (progn
                (with-temp-file (expand-file-name reference (gnosis-assets-root)) (insert "broken"))
                (gnosis-edit-thema 12345)
                (let ((before (buffer-string)) (rows (gnosis-test-image-drafts-rows)))
                  (should (eq (key-binding (kbd "C-c C-c")) 'gnosis-save))
                  (should-error (execute-kbd-macro (kbd "C-c C-c")))
                  (should (equal-including-properties before (buffer-string)))
                  (should (equal rows (gnosis-test-image-drafts-rows)))
                  (dolist (action '(reuse invalid cancel))
                    (gnosis-test-image-drafts-input
                     (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) (eq action 'reuse)))
                               ((symbol-function 'read-file-name)
                                (lambda (&rest _)
                                  (when (eq action 'reuse) (ert-fail "Reuse must not choose another file"))
                                  (if (eq action 'cancel) (signal 'quit nil)
                                    (expand-file-name "missing.png" gnosis-dir))))
                               ((symbol-function 'read-string) (lambda (&rest _) "")))
                       (should (memq (condition-case err
                                         (progn (gnosis-test-image-drafts-attach type) 'accepted)
                                       ((error quit) (car err)))
                                     '(user-error file-missing quit json-parse-error)))))
                    (should (equal-including-properties before (buffer-string)))
                    (should (equal rows (gnosis-test-image-drafts-rows)))))
                ;; The corrupt immutable destination is not repairable by retry.
                (should-error
                 (if (string-prefix-p "image" type)
                     (gnosis-image-import (car fixture) gnosis-test-image--regions)
                   (gnosis-model-import (car fixture))))
                (should (equal "broken" (with-temp-buffer
                                          (insert-file-contents (expand-file-name reference (gnosis-assets-root)))
                                          (buffer-string)))))
            (gnosis-test-image-drafts-clean)))))))

(ert-deftest gnosis-test-image-drafts-legacy-missing-answer-is-not-guessed ()
  (gnosis-test-with-db
    (save-window-excursion
      (let* ((fixture (gnosis-test-image-drafts-fixture "image-occlusion"))
             (reference (cadr fixture)))
        (unwind-protect
            (progn
              (gnosis-edit-thema 12345)
              (let ((inhibit-read-only t))
                (erase-buffer)
                (gnosis-export--insert-thema "12345" "image-region" "Legacy" reference "left")
                (goto-char (point-min))
                (search-forward ":GNOSIS_TYPE: image-region")
                (replace-match ":GNOSIS_TYPE: image-occlusion" t t))
              (delete-file (expand-file-name reference (gnosis-assets-root)))
              (let ((before (buffer-string)))
                (should-error (gnosis-test-image-drafts-attach "image-occlusion") :type 'user-error)
                (should (equal-including-properties before (buffer-string)))))
          (gnosis-test-image-drafts-clean))))))

(ert-deftest gnosis-test-image-drafts-native-editor-cancel-retry-save ()
  (skip-unless (display-graphic-p))
  (dolist (type '("image-region" "image-occlusion"))
    (gnosis-test-with-db
      (save-window-excursion
        (let* ((fixture (gnosis-test-image-drafts-fixture type))
               (reference (cadr fixture))
               (scene (gnosis-image-resolve reference))
               (hash (gnosis-assets-hash (alist-get 'path scene)))
               (evidence (gnosis-test-image-drafts-evidence))
               (read-text (symbol-function 'read-string))
               (gnosis-save-hook nil) viewer)
          (unwind-protect
              (progn
                (gnosis-edit-thema 12345)
                (let ((before (buffer-string)))
                  (dolist (cancel '(t nil))
                    (let ((gnosis-image-mode-hook
                           (list (lambda ()
                                   (setq viewer (current-buffer))
                                   (should (gnosis-image--owned-p))
                                   (should (eq (key-binding (kbd "n")) #'gnosis-image-next-rectangle))
                                   (should (eq (key-binding (kbd "l")) #'gnosis-image-rename-target))
                                   (should (eq (key-binding (kbd "RET")) #'gnosis-image-submit))
                                   (setq unread-command-events
                                         (listify-key-sequence
                                          (kbd (if cancel "q" "n l C-a C-k R e n a m e d RET RET"))))))))
                      (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t))
                                ((symbol-function 'read-string)
                                 (lambda (prompt &rest args)
                                   (if (string-prefix-p "Target label" prompt)
                                       (apply read-text prompt args) (car args))))
                                ((symbol-function 'completing-read)
                                 (lambda (prompt choices &rest _)
                                   (if (string-prefix-p "Label visibility" prompt) "hide-all" (caar choices)))))
                        (should (eq (key-binding (kbd "C-c C-a")) #'gnosis-image-attach))
                        (if cancel
                            (progn
                              (should (eq 'quit (condition-case nil
                                                    (call-interactively (key-binding (kbd "C-c C-a")))
                                                  (quit 'quit))))
                              (should (equal-including-properties before (buffer-string))))
                          (call-interactively (key-binding (kbd "C-c C-a"))))))
                    (should-not (buffer-live-p viewer))))
                (let* ((new (car (nth 3 (car (gnosis-export-parse-themata)))))
                       (new-scene (gnosis-image-resolve new)))
                  (should-not (equal reference new))
                  (should (equal "Renamed" (alist-get 'label (gnosis-image-target new-scene "left"))))
                  (should (equal hash (gnosis-assets-hash (alist-get 'path new-scene))))
                  (should (gnosis-image--decode new-scene))
                  (gnosis-test-image-drafts-save-reopen)
                  (should (equal new (car (gnosis-get 'hypothesis 'themata '(= id 12345)))))
                  (should (equal "Hidden explanation" (gnosis-get 'parathema 'extras '(= id 12345))))
                  (when (equal type "image-occlusion")
                    (should (equal '("Authored answer") (gnosis-get 'answer 'themata '(= id 12345))))
                    (should (equal '("Hidden alias") (gnosis-get 'accepted-aliases 'themata '(= id 12345)))))
                  (should (equal evidence (gnosis-test-image-drafts-evidence)))
                  (should (gnosis-image-resolve reference))))
            (setq unread-command-events nil)
            (gnosis-test-image-drafts-clean)))))))

(ert-deftest gnosis-test-image-drafts-canonical-occlusion-save-validates-target ()
  (gnosis-test-with-db
    (let* ((reference (cadr (gnosis-test-image-drafts-fixture "image-occlusion")))
           (before (gnosis-test-image-drafts-rows)))
      (dolist (hypothesis (list (list reference "unknown" "hide-all")
                                (list reference "left" "invalid-policy")))
        (should-error (gnosis-update-thema 12345 "Question" hypothesis '("Authored answer")
                                            "Hidden explanation" nil nil) :type 'user-error)
        (should (equal before (gnosis-test-image-drafts-rows)))))))

(provide 'gnosis-test-image-drafts)
;;; gnosis-test-image-drafts.el ends here
