;;; gnosis-test-model-lookahead.el --- One-card preparation tests -*- lexical-binding: t; -*-

(require 'gnosis-test-model)

(ert-deftest gnosis-model-lookahead-ready-and-pending-transfer ()
  (dolist (ready '(nil t))
    (gnosis-test-with-db
      (let* ((first (gnosis-test-model--add))
             (next (gnosis-test-model--add))
             (buffer (gnosis-review--setup-buffer (list first next) 'practice))
             (before (gnosis-select '* 'scheduler-state))
             (row (car (gnosis-review--answer-thema next)))
             (fields (gnosis-model-fields (car row) (nth 2 row) (nth 3 row)))
             callback delivered (starts 0))
        (unwind-protect
            (with-current-buffer buffer
              (let* ((gnosis-review--running (gnosis-review-state-session-id gnosis-review--state))
                     (snapshot (copy-tree (gnosis-review--state-data gnosis-review--state)))
                     (context (list :buffer buffer :id next :preparation nil)))
                (cl-letf (((symbol-function 'gnosis-model-prepare)
                           (lambda (_type _hypothesis _answer cb)
                             (cl-incf starts) (setq callback cb) (list :cancelled nil)))
                          ((symbol-function 'gnosis-review--model-prepared)
                           (lambda (owner result failure)
                             (should (eq context owner))
                             (should-not failure) (setq delivered result))))
                  (gnosis-review--lookahead-start)
                  (gnosis-review--lookahead-start)
                  (should (= starts 1))
                  (when ready (funcall callback fields nil))
                  (should-not delivered)
                  (should-not (string-match-p "Triangle" (buffer-string)))
                  (setf (gnosis-review-state-remaining gnosis-review--state) (list next))
                  (gnosis-review--lookahead-advance snapshot)
                  (should (gnosis-review--lookahead-take context))
                  (should-not gnosis-review--lookahead)
                  (unless ready (funcall callback fields nil))
                  (should (eq fields delivered))
                  (should (= starts 1))
                  (should (equal before (gnosis-select '* 'scheduler-state)))
                  (should-not (gnosis-select '* 'practice-events))
                  (should-not (gnosis-select '* 'review-events)))))
          (kill-buffer buffer))))))

(ert-deftest gnosis-model-lookahead-stale-and-quit-retire-work ()
  (dolist (mutation '(queue session thema extras suspended deleted quit database mode killed))
    (gnosis-test-with-db
      (let* ((first (gnosis-test-model--add))
             (next (gnosis-test-model--add))
             (buffer (gnosis-review--setup-buffer (list first next) 'practice))
             (database gnosis-db)
             callback slot job)
        (unwind-protect
            (with-current-buffer buffer
              (let ((gnosis-review--running (gnosis-review-state-session-id gnosis-review--state)))
                (cl-letf (((symbol-function 'gnosis-model-prepare)
                           (lambda (_type _hypothesis _answer cb)
                             (setq callback cb job (list :cancelled nil)))))
                  (gnosis-review--lookahead-start)
                  (setq slot gnosis-review--lookahead)
                  (should slot)
                  (pcase mutation
                    ('queue (setf (gnosis-review-state-remaining gnosis-review--state) (list first)))
                    ('session (setf (gnosis-review-state-session-id gnosis-review--state) "other"))
                    ('thema (gnosis-update 'themata '(= keimenon "Changed") `(= id ,next)))
                    ('extras (gnosis-update 'extras '(= parathema "Changed") `(= id ,next)))
                    ('mode (fundamental-mode))
                    ('killed (kill-buffer buffer))
                    ('suspended (gnosis-toggle-suspend-themata (list next) 1 t))
                    ('deleted (gnosis-delete-thema next t))
                    ('quit (gnosis-review--lookahead-cancel))
                    ('database (setq gnosis-db nil)))
                  (gnosis-review--lookahead-poll slot)
                  (funcall callback '(:future secret) nil)
                  (should-not gnosis-review--lookahead)
                  (should (plist-get job :cancelled))
                  (should-not (plist-get slot :fields)))))
          (setq gnosis-db database)
          (kill-buffer buffer))
        (should-not (gnosis-select '* 'practice-events))
        (should-not (gnosis-select '* 'review-events))))))

(ert-deftest gnosis-model-lookahead-public-session-reuses-child-and-keeps-retry-order ()
  (dolist (mode '(practice due))
    (gnosis-test-with-db
      (save-window-excursion
        (let* ((first (gnosis-test-model--add))
               (next (gnosis-test-model--add))
               (buffer (gnosis-review--setup-buffer (list first next) mode))
               (prepare (symbol-function 'gnosis-model-prepare))
               (starts 0) (depth 0) seen)
          (unwind-protect
              (with-current-buffer buffer
                (setf (gnosis-review-state-persistent-p gnosis-review--state) t)
                (gnosis-review--save-session gnosis-review--state)
                (let ((gnosis-review--running (gnosis-review-state-session-id gnosis-review--state)))
                  (cl-letf (((symbol-function 'gnosis-model-prepare)
                             (lambda (&rest args) (cl-incf starts) (apply prepare args)))
                            ((symbol-function 'gnosis-model-open) #'gnosis-test-model--canvas)
                            ((symbol-function 'gnosis-model--canvas-size) (lambda () 400))
                            ((symbol-function 'recursion-depth) (lambda () depth))
                            ((symbol-function 'exit-recursive-edit) #'ignore)
                            ((symbol-function 'gnosis-review-actions)
                             (lambda (success id result) (gnosis-review--accept id success result)))
                            ((symbol-function 'recursive-edit)
                             (lambda ()
                               (setq depth 1)
                               (gnosis-test-model--wait-for-preparation)
                               (let ((id (plist-get gnosis-review--model-context :id)))
                                 (push id seen)
                                 (when (equal id first)
                                   (should gnosis-review--lookahead)
                                   (let ((deadline (+ (float-time) 5)))
                                     (while (and (not (plist-get gnosis-review--lookahead :fields))
                                                 (< (float-time) deadline))
                                       (accept-process-output nil 0.01)))
                                   (should (plist-get gnosis-review--lookahead :fields))
                                   (should-not (gnosis-select '* 'practice-events))
                                   (should-not (gnosis-select '* 'review-events)))
                                 (gnosis-test-model--review-pick
                                  (if (equal id first) "other" "triangle") canvas-3d--process)
                                 (gnosis-review-model-submit)))))
                    (gnosis-review-process-thema first gnosis-review--state)
                    (should (equal (gnosis-review-state-remaining gnosis-review--state)
                                   (list next first)))
                    (should (plist-get gnosis-review--lookahead :advanced))
                    (setq depth 0)
                    (gnosis-review-process-thema next gnosis-review--state)
                    ;; Next's prepared child is reused; only its retry lookahead
                    ;; starts another child, not another parse of NEXT.
                    (should (= starts 3))
                    (should (equal seen (list next first)))
                    (should (equal (gnosis-review-state-remaining gnosis-review--state)
                                   (list first)))
                    (should (= 2 (length (gnosis-select '* (if (eq mode 'practice)
                                                              'practice-events 'review-events)))))
                    (when (eq mode 'practice)
                      (should-not (gnosis-select '* 'review-events))))))
            (kill-buffer buffer)))))))

(ert-deftest gnosis-model-lookahead-ready-bytes-still-checked-before-display ()
  (gnosis-test-with-db
    (save-window-excursion
      (let* ((first (gnosis-test-model--add))
             (next (gnosis-test-model--add))
             (buffer (gnosis-review--setup-buffer (list first next) 'practice))
             (row (car (gnosis-review--answer-thema next)))
             (fields (gnosis-model-fields (car row) (nth 2 row) (nth 3 row)))
             callback opened)
        (unwind-protect
            (with-current-buffer buffer
              (set-window-buffer (selected-window) buffer)
              (let ((gnosis-review--running (gnosis-review-state-session-id gnosis-review--state))
                    (snapshot (copy-tree (gnosis-review--state-data gnosis-review--state))))
                (cl-letf (((symbol-function 'gnosis-model-prepare)
                           (lambda (_type _hypothesis _answer cb)
                             (setq callback cb) (list :cancelled nil)))
                          ((symbol-function 'gnosis-model-open)
                           (lambda (&rest _) (setq opened t)))
                          ((symbol-function 'recursive-edit) #'ignore))
                  (gnosis-review--lookahead-start)
                  (funcall callback fields nil)
                  (write-region "\n" nil (plist-get fields :scene) t 'silent)
                  (setf (gnosis-review-state-remaining gnosis-review--state) (list next))
                  (gnosis-review--lookahead-advance snapshot)
                  (should-error (gnosis-review-model next) :type 'user-error)
                  (should-not opened)
                  (should-not gnosis-review--lookahead)
                  (should-not (gnosis-select '* 'practice-events))
                  (should-not (gnosis-select '* 'review-events)))))
          (kill-buffer buffer))))))

(ert-deftest gnosis-model-lookahead-next-mismatch-and-run-quit ()
  (dolist (quit '(nil t))
    (gnosis-test-with-db
      (let* ((first (gnosis-test-model--add))
             (next (gnosis-test-model--add))
             (buffer (gnosis-review--setup-buffer (list first next) 'practice))
             job)
        (unwind-protect
            (with-current-buffer buffer
              (cl-letf (((symbol-function 'gnosis-model-prepare)
                         (lambda (&rest _) (setq job (list :cancelled nil))))
                        ((symbol-function 'gnosis-review--show-summary) #'ignore)
                        ((symbol-function 'gnosis-review-session)
                         (lambda (_state)
                           (gnosis-review--lookahead-start)
                           (should gnosis-review--lookahead)
                           (if quit (throw 'review-loop nil)
                             (let ((snapshot (copy-tree (gnosis-review--state-data gnosis-review--state))))
                               (setf (gnosis-review-state-remaining gnosis-review--state) (list first))
                               (gnosis-review--lookahead-advance snapshot)
                               (should-not gnosis-review--lookahead))))))
                (gnosis-review--run-state buffer gnosis-review--state)
                (should-not gnosis-review--lookahead)
                (should (plist-get job :cancelled))))
          (kill-buffer buffer))))))

(provide 'gnosis-test-model-lookahead)
;;; gnosis-test-model-lookahead.el ends here
