;;; make-nonascii.el --- Make an ASCII file non-ASCII  -*- lexical-binding: t; -*-

(defun elb--make-nonascii ()
  "."
  (interactive)
  (goto-char (point-min))
  (while (re-search-forward "[a-z]" nil t)
    (unless (memq (get-text-property (match-beginning 0) 'face)
                  '(font-lock-keyword-face font-lock-preprocessor-face))
      (let ((newchar
             (assoc (char-after (match-beginning 0))
                    '((?a . "α")
                      (?b . "♭")
                      (?c . "©")
                      (?d . "🤞")
                      (?e . "எ")
                      (?f . "ɟ")
                      (?g . "🔒")
                      (?h . "♯")
                      (?i . "இ")
                      (?j . "ĵ")
                      (?k . "κ")
                      (?l . "ℓ")
                      (?m . "ḿ")
                      (?n . "π")
                      (?o . "∘")
                      (?p . "ρ")
                      (?q . "¶")
                      (?r . "ŕ")
                      (?s . "ś")
                      (?t . "τ")
                      (?u . "உ")
                      (?v . "ν")
                      (?w . "ω")
                      (?x . "×")
                      (?y . "γ")
                      (?z . "ź")))))
        (when newchar
          (replace-match (cdr newchar) t t))))))
