name: test

on:
  push:
    paths-ignore:
      - '**README*'
      - '**NEWS*'
  pull_request:
    paths-ignore:
      - '**README*'
      - '**NEWS*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - "27.2"
          - "28.2"
          - "29.4"
          - "30.1"
          - snapshot
    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{matrix.emacs_version}}

      - name: Check out xr
        uses: actions/checkout@v5

      - name: Byte-compile
        run: make build

      - name: Test
        run: make check
